#!/usr/bin/env python3
"""RET n of every function of the Steam listing (the callee-popped argument bytes of the
stdcall / thiscall functions), as the TranslatedPops table bulk_fallback.cpp gives the bulk
translation: a translated call to a native service returns through it with the callee's pops.
usage: pops_table.py steam_text.asm functions.csv > src/platform/bulk_pops.inc"""
import bisect, csv, re, sys
asm, fcsv = sys.argv[1], sys.argv[2]
starts = sorted(int(r['address'], 16) for r in csv.DictReader(open(fcsv)))
pops = {}
rx = re.compile(r'\s+([0-9a-f]+):\t(ret|repz ret)\s*(0x[0-9a-f]+)?')
for l in open(asm, encoding='utf-8', errors='replace'):
    m = rx.match(l)
    if not m: continue
    a = int(m.group(1), 16); k = bisect.bisect_right(starts, a) - 1
    if k < 0: continue
    f = starts[k]; n = int(m.group(3), 16) if m.group(3) else 0
    pops.setdefault(f, n)
print('// Generated by tools/x86tr/pops_table.py from the Steam listing: {pc, RET n} of the functions')
print('// whose first RET pops arguments (stdcall / thiscall).')
for f in sorted(pops):
    if pops[f]: print('{0x%06xu,0x%xu},' % (f, pops[f]))
