// Generated by tools/generate_pc_shaders.py from the hash-pinned EXE. Do not edit.
#version 460

layout(std140,binding=0) uniform PsConstants{vec4 PC[8];};
layout(std140,binding=1) uniform PsProgram{ivec4 program[4];ivec4 info;ivec4 stage_kind[2];vec4 bump[8];vec4 lum[2];};
layout(std140,binding=2) uniform PsFixed{vec4 fog_colour;vec4 fog_params;vec4 alpha_test;};
layout(location=0) in vec4 in_d0;
layout(location=1) in vec4 in_d1;
layout(location=2) in vec4 in_t0;
layout(location=3) in vec4 in_t1;
layout(location=4) in vec4 in_t2;
layout(location=5) in vec4 in_t3;
layout(location=6) in vec4 in_t4;
layout(location=7) in vec4 in_t5;
layout(location=8) in vec4 in_t6;
layout(location=9) in vec4 in_t7;
layout(location=10) in float in_fog;
layout(location=0) out vec4 out_colour;
layout(binding=0) uniform sampler2D tex2d0;
layout(binding=6) uniform samplerCube texcube0;
layout(binding=1) uniform sampler2D tex2d1;
layout(binding=7) uniform samplerCube texcube1;
layout(binding=2) uniform sampler2D tex2d2;
layout(binding=8) uniform samplerCube texcube2;
layout(binding=3) uniform sampler2D tex2d3;
layout(binding=9) uniform samplerCube texcube3;
layout(binding=4) uniform sampler2D tex2d4;
layout(binding=10) uniform samplerCube texcube4;
layout(binding=5) uniform sampler2D tex2d5;
layout(binding=11) uniform samplerCube texcube5;
vec4 R[2];vec4 T[4];vec4 TC[4];vec4 VC[2];float M3[4];

vec4 d3d_rcp(float v){float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):1.0/v);return vec4(f);}
vec4 d3d_rsq(float v){v=abs(v);float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):inversesqrt(v));return vec4(f);}
vec4 d3d_lit(vec4 s){vec4 d=vec4(1.0,0.0,0.0,1.0);float p=clamp(s.w,-127.9961,127.9961);
    if(s.x>0.0){d.y=s.x;if(s.y>0.0)d.z=pow(s.y,p);}return d;}
vec4 d3d_dst(vec4 a,vec4 b){return vec4(1.0,a.y*b.y,a.z,b.w);}

vec4 sample_stage(int n,vec4 c){
    if(n==0)return stage_kind[0][0]==1?texture(texcube0,c.xyz):texture(tex2d0,c.xy);
    if(n==1)return stage_kind[0][1]==1?texture(texcube1,c.xyz):texture(tex2d1,c.xy);
    if(n==2)return stage_kind[0][2]==1?texture(texcube2,c.xyz):texture(tex2d2,c.xy);
    if(n==3)return stage_kind[0][3]==1?texture(texcube3,c.xyz):texture(tex2d3,c.xy);
    if(n==4)return stage_kind[1][0]==1?texture(texcube4,c.xyz):texture(tex2d4,c.xy);
    if(n==5)return stage_kind[1][1]==1?texture(texcube5,c.xyz):texture(tex2d5,c.xy);
    return vec4(0.0);}
vec4 sample_bump(int n,vec4 tc,vec4 t){
    vec4 m=bump[n];vec2 uv=tc.xy+vec2(m.x*t.x+m.z*t.y,m.y*t.x+m.w*t.y);
    vec4 c=sample_stage(n,vec4(uv,0.0,1.0));vec4 l=lum[n>>1];float s=(n&1)==0?l.x:l.z;float o=(n&1)==0?l.y:l.w;
    c.rgb*=clamp(t.z*s+o,0.0,1.0);return c;}
vec4 sample_vspec(int n,vec3 nrm,vec3 eye){vec3 r=2.0*nrm*dot(nrm,eye)/dot(nrm,nrm)-eye;return sample_stage(n,vec4(r,1.0));}
void f0(){ // 61E7C4
    vec4 t0=VC[0];
    R[0]=t0;
}
void f1(){ // 61E7D8
    T[0]=sample_stage(0,TC[0]);
    vec4 t0=(T[0]*VC[0]);
    R[0]=t0;
}
void f2(){ // 61E7F8
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    vec4 t0=(T[0]*VC[0]);
    R[0]=t0;
    vec4 t1=(T[1]*R[0]);
    R[0]=t1;
}
void f3(){ // 61E830
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
    vec4 t0=(T[0]*VC[0]);
    R[0]=t0;
    vec4 t1=(T[1]*R[0]);
    R[0]=t1;
    vec4 t2=(T[2]*R[0]);
    R[0]=t2;
}
void f4(){ // 61E880
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
    T[3]=sample_stage(3,TC[3]);
    vec4 t0=(T[0]*VC[0]);
    R[0]=t0;
    vec4 t1=(T[1]*R[0]);
    R[0]=t1;
    vec4 t2=(T[2]*R[0]);
    R[0]=t2;
    vec4 t3=(T[3]*R[0]);
    R[0]=t3;
}
void f5(){ // 61E8E8
    T[2]=sample_stage(2,TC[2]);
    T[3]=sample_stage(3,TC[3]);
    vec4 t0=(vec4(1.0)-((T[3]).wwww));
    R[1]=((t0)*4.0);
    vec4 t1=R[1];
    R[1]=((t1)*4.0);
    vec4 t2=(vec4(1.0)-((T[3]).zzzz));
    R[0].w=(t2).w;
    vec4 t3=((R[0]).wwww*vec4(0.0625,0.0625,0.0625,0.0625)+R[1]);
    R[1]=t3;
    vec4 t4=vec4(dot((R[1]).xyz,(vec4(1.0,0.0,0.0,0.0)).xyz));
    R[1]=t4;
    vec4 t5=T[2];
    vec4 t6=((R[1]).wwww*(VC[0]).wwww);
    R[0].xyz=(t5).xyz;
    R[0].w=(t6).w;
}
void f6(){ // 61E9C4
    
}
void f7(){ // 61E9E4
    
}
void f8(){ // 61E9EC
    T[0]=sample_stage(0,TC[0]);
}
void f9(){ // 61E9FC
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
}
void f10(){ // 61EA14
    T[0]=sample_stage(0,TC[0]);
    T[2]=sample_stage(2,TC[2]);
}
void f11(){ // 61EA2C
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
}
void f12(){ // 61EA4C
    T[3]=sample_stage(3,TC[3]);
}
void f13(){ // 61EA5C
    T[0]=sample_stage(0,TC[0]);
    T[3]=sample_stage(3,TC[3]);
}
void f14(){ // 61EA74
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[3]=sample_stage(3,TC[3]);
}
void f15(){ // 61EA94
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
    T[3]=sample_stage(3,TC[3]);
}
void f16(){ // 61EABC
    
}
void f17(){ // 61EAC4
    vec4 t0=(PC[6]+T[3]);
    R[1].xyz=(t0).xyz;
}
void f18(){ // 61EADC
    vec4 t0=VC[0];
    R[0].xyz=(t0).xyz;
}
void f19(){ // 61EAF0
    vec4 t0=(VC[1]*T[0]);
    R[1].xyz=(t0).xyz;
}
void f20(){ // 61EB08
    vec4 t0=(VC[1]*(T[0]).wwww);
    R[1].xyz=(t0).xyz;
}
void f21(){ // 61EB20
    vec4 t0=(T[0]*VC[0]);
    R[0].xyz=(t0).xyz;
}
void f22(){ // 61EB38
    vec4 t0=(T[0]*VC[0]);
    R[0].xyz=(t0).xyz;
}
void f23(){ // 61EB50
    vec4 t0=(T[0]*R[1]+VC[0]);
    R[0].xyz=(t0).xyz;
}
void f24(){ // 61EB6C
    vec4 t0=(T[0]*(T[0]).wwww);
    R[1].xyz=(t0).xyz;
    vec4 t1=(VC[0]*(vec4(1.0)-((T[1]).wwww))+R[1]);
    R[0].xyz=(t1).xyz;
}
void f25(){ // 61EB98
    vec4 t0=T[0];
    R[0].xyz=(t0).xyz;
}
void f26(){ // 61EBAC
    vec4 t0=(T[1]*VC[1]);
    R[1].xyz=(t0).xyz;
}
void f27(){ // 61EBC4
    vec4 t0=(T[1]*R[0]);
    R[0].xyz=(t0).xyz;
}
void f28(){ // 61EBDC
    vec4 t0=(T[1]*R[0]);
    R[0].xyz=(((t0)*2.0)).xyz;
}
void f29(){ // 61EBF4
    vec4 t0=(T[2]*R[0]);
    R[0].xyz=(t0).xyz;
}
void f30(){ // 61EC0C
    vec4 t0=(T[1]*R[1]+R[0]);
    R[0].xyz=(t0).xyz;
}
void f31(){ // 61EC28
    vec4 t0=(T[1]*(T[1]).wwww);
    R[1].xyz=(t0).xyz;
    vec4 t1=(R[0]*(vec4(1.0)-((T[1]).wwww))+R[1]);
    R[0].xyz=(t1).xyz;
}
void f32(){ // 61EC54
    vec4 t0=(T[1]+R[0]);
    R[0].xyz=(t0).xyz;
}
void f33(){ // 61EC6C
    vec4 t0=(R[0]*R[1]);
    R[0].xyz=(t0).xyz;
}
void f34(){ // 61EC84
    
}
void f35(){ // 61EC8C
    vec4 t0=(T[3]*PC[6]+R[0]);
    R[0].xyz=(t0).xyz;
}
void f36(){ // 61ECA8
    vec4 t0=((R[0]).wwww*T[1]+R[0]);
    R[0].xyz=(t0).xyz;
}
void f37(){ // 61ECC4
    vec4 t0=((R[0]).wwww*T[2]+R[0]);
    R[0].xyz=(t0).xyz;
}
void f38(){ // 61ECE0
    vec4 t0=((PC[6]).wwww+(T[3]).wwww);
    R[1].w=(t0).w;
}
void f39(){ // 61ECF8
    vec4 t0=((vec4(1.0)-((VC[1]).wwww))*(T[0]).wwww+(VC[1]).wwww);
    R[1].xyz=(t0).xyz;
}
void f40(){ // 61ED14
    vec4 t0=((vec4(1.0)-((VC[1]).wwww))*(T[1]).wwww+(VC[1]).wwww);
    R[1].xyz=(t0).xyz;
}
void f41(){ // 61ED30
    
}
void f42(){ // 61ED38
    vec4 t0=(VC[0]).wwww;
    R[0].w=(t0).w;
}
void f43(){ // 61ED4C
    vec4 t0=((T[0]).wwww*(VC[0]).wwww);
    R[0].w=(t0).w;
}
void f44(){ // 61ED64
    vec4 t0=((T[1]).wwww*(R[0]).wwww);
    R[0].w=(t0).w;
}
void f45(){ // 61ED7C
    vec4 t0=(T[1]).wwww;
    R[0].w=(t0).w;
}
void f46(){ // 61ED90
    vec4 t0=(T[2]).wwww;
    R[0].w=(t0).w;
}
void f47(){ // 61EDA4
    vec4 t0=((T[2]).wwww*(R[0]).wwww);
    R[0].w=(t0).w;
}
void f48(){ // 61EDBC
    
}
void f49(){ // 61EDC4
    vec4 t0=(R[0]+VC[1]);
    vec4 t1=(R[0]).wwww;
    R[0].xyz=(t0).xyz;
    R[0].w=(t1).w;
}
void f50(){ // 622348
    T[0]=sample_stage(0,TC[0]);
    vec4 t0=((T[0]).wwww*((T[0])*2.0-vec4(1.0)));
    R[1].xyz=(t0).xyz;
    vec4 t1=PC[0];
    R[0]=t1;
    vec4 t2=(R[1]-((R[0])*2.0-vec4(1.0)));
    R[1].xyz=(t2).xyz;
    vec4 t3=PC[1];
    R[0]=t3;
    vec4 t4=vec4(dot((R[1]).xyz,(((R[0])*2.0-vec4(1.0))).xyz));
    vec4 t5=((-((R[1]).zzzz))+(vec4(1.0,1.0,1.0,0.5)).wwww);
    R[1].xyz=(((t4)*2.0)).xyz;
    R[0].w=(t5).w;
    vec4 t6=mix(T[0],(vec4(0.0,0.0,0.0,0.0)).wwww,vec4(greaterThan((R[0]).wwww,vec4(0.5))));
    vec4 t7=mix((vec4(1.0,1.0,1.0,0.5)).wwww,vec4(0.0,0.0,0.0,0.0),vec4(greaterThan((R[0]).wwww,vec4(0.5))));
    R[0].xyz=(t6).xyz;
    R[0].w=(t7).w;
    vec4 t8=((T[0]).wwww-PC[2]);
    R[1].xyz=(clamp(((t8)*4.0),0.0,1.0)).xyz;
    vec4 t9=(R[0]-(vec4(1.0)-(R[1])));
    R[0].xyz=(t9).xyz;
}
void f51(){ // 622428
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
    T[3]=sample_stage(3,TC[3]);
    vec4 t0=(T[0]*vec4(0.25,0.25,0.25,0.25));
    R[0]=t0;
    vec4 t1=(T[1]*vec4(0.25,0.25,0.25,0.25)+R[0]);
    R[0]=t1;
    vec4 t2=(T[2]*vec4(0.25,0.25,0.25,0.25)+R[0]);
    R[0]=t2;
    vec4 t3=(T[3]*vec4(0.25,0.25,0.25,0.25)+R[0]);
    R[0]=t3;
}
void f52(){ // 6224B4
    T[0]=sample_stage(0,TC[0]);
    vec4 t0=T[0];
    R[0]=t0;
}
void f53(){ // 6224D0
    T[0]=sample_stage(0,TC[0]);
    vec4 t0=vec4(dot((T[0]).xyz,(vec4(0.29899999499320984,0.5870000123977661,0.11400000005960464,1.0)).xyz));
    R[0]=t0;
    vec4 t1=(R[0]*(T[0]).wwww);
    R[0].xyz=(t1).xyz;
    vec4 t2=(vec4(0.29899999499320984,0.5870000123977661,0.11400000005960464,1.0)).wwww;
    R[0].w=(t2).w;
}
void f54(){ // 623830
    T[0]=sample_stage(0,TC[0]);
    vec4 t0=(T[0]*VC[0]);
    R[0]=clamp(t0,0.0,1.0);
    vec4 t1=((vec4(1.0)-((R[0]).wwww))*(vec4(1.0)-((R[0]).wwww)));
    R[0].w=(clamp(t1,0.0,1.0)).w;
    vec4 t2=(vec4(1.0)-((R[0]).wwww));
    R[0].w=(t2).w;
    vec4 t3=(R[0]*(R[0]).wwww);
    R[0].xyz=(t3).xyz;
}
void f55(){ // 623BB0
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
    T[3]=sample_stage(3,TC[3]);
    vec4 t0=vec4(dot((((T[0])*2.0-vec4(1.0))).xyz,(((T[2])*2.0-vec4(1.0))).xyz));
    R[0].xyz=(clamp(t0,0.0,1.0)).xyz;
    vec4 t1=(R[0]*PC[0]+PC[1]);
    R[0].xyz=(t1).xyz;
    vec4 t2=(R[0]*T[1]);
    R[0].xyz=(t2).xyz;
    vec4 t3=vec4(dot((((T[0])*2.0-vec4(1.0))).xyz,(((T[3])*2.0-vec4(1.0))).xyz));
    R[1].xyz=(clamp(t3,0.0,1.0)).xyz;
    vec4 t4=(R[1]*R[1]);
    R[1].xyz=(t4).xyz;
    vec4 t5=(R[1]*R[1]);
    R[1].xyz=(t5).xyz;
    vec4 t6=(R[1]*R[1]);
    R[1].xyz=(t6).xyz;
    vec4 t7=(R[1]*PC[2]+R[0]);
    vec4 t8=(vec4(0.0,0.0,0.0,0.0)).wwww;
    R[0].xyz=(t7).xyz;
    R[0].w=(t8).w;
}
void f56(){ // 623C88
    T[0]=sample_stage(0,TC[0]);
    M3[1]=dot(TC[1].xyz,T[0].xyz);
    M3[2]=dot(TC[2].xyz,T[0].xyz);
    T[3]=sample_vspec(3,vec3(M3[1],M3[2],dot(TC[3].xyz,T[0].xyz)),vec3(TC[1].w,TC[2].w,TC[3].w));
    vec4 t0=(VC[0]*(vec4(1.0)-((T[3]).wwww)));
    R[1].xyz=(t0).xyz;
    vec4 t1=(T[3]*(T[3]).wwww+R[1]);
    vec4 t2=(VC[0]).wwww;
    R[0].xyz=(t1).xyz;
    R[0].w=(t2).w;
}
void f57(){ // 623CF0
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_bump(1,TC[1],T[0]);
    vec4 t0=(VC[0]*(vec4(1.0)-((T[1]).wwww)));
    R[1].xyz=(t0).xyz;
    vec4 t1=(T[1]*(T[1]).wwww+R[1]);
    vec4 t2=(VC[0]).wwww;
    R[0].xyz=(t1).xyz;
    R[0].w=(t2).w;
}
void f58(){ // 623D40
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_bump(2,TC[2],T[0]);
    vec4 t0=(VC[0]*T[1]);
    R[0].xyz=(t0).xyz;
    vec4 t1=(R[0]*(vec4(1.0)-((T[2]).wwww)));
    R[0].xyz=(t1).xyz;
    vec4 t2=(T[2]*(T[2]).wwww+R[0]);
    vec4 t3=(VC[0]).wwww;
    R[0].xyz=(t2).xyz;
    R[0].w=(t3).w;
}
void f59(){ // 623DA8
    T[0]=sample_stage(0,TC[0]);
    T[1]=sample_stage(1,TC[1]);
    T[2]=sample_stage(2,TC[2]);
    T[3]=sample_bump(3,TC[3],T[0]);
    vec4 t0=(VC[0]*T[1]);
    R[0].xyz=(t0).xyz;
    vec4 t1=(R[0]*T[2]);
    R[0].xyz=(t1).xyz;
    vec4 t2=(R[0]*(vec4(1.0)-((T[3]).wwww)));
    vec4 t3=((VC[0]).wwww*(T[1]).wwww);
    R[0].xyz=(t2).xyz;
    R[0].w=(t3).w;
    vec4 t4=(T[3]*(T[3]).wwww+R[0]);
    vec4 t5=((R[0]).wwww*(T[2]).wwww);
    R[0].xyz=(t4).xyz;
    R[0].w=(t5).w;
}
void run(int id){switch(id){
case 0:f0();break;
case 1:f1();break;
case 2:f2();break;
case 3:f3();break;
case 4:f4();break;
case 5:f5();break;
case 6:f6();break;
case 7:f7();break;
case 8:f8();break;
case 9:f9();break;
case 10:f10();break;
case 11:f11();break;
case 12:f12();break;
case 13:f13();break;
case 14:f14();break;
case 15:f15();break;
case 16:f16();break;
case 17:f17();break;
case 18:f18();break;
case 19:f19();break;
case 20:f20();break;
case 21:f21();break;
case 22:f22();break;
case 23:f23();break;
case 24:f24();break;
case 25:f25();break;
case 26:f26();break;
case 27:f27();break;
case 28:f28();break;
case 29:f29();break;
case 30:f30();break;
case 31:f31();break;
case 32:f32();break;
case 33:f33();break;
case 34:f34();break;
case 35:f35();break;
case 36:f36();break;
case 37:f37();break;
case 38:f38();break;
case 39:f39();break;
case 40:f40();break;
case 41:f41();break;
case 42:f42();break;
case 43:f43();break;
case 44:f44();break;
case 45:f45();break;
case 46:f46();break;
case 47:f47();break;
case 48:f48();break;
case 49:f49();break;
case 50:f50();break;
case 51:f51();break;
case 52:f52();break;
case 53:f53();break;
case 54:f54();break;
case 55:f55();break;
case 56:f56();break;
case 57:f57();break;
case 58:f58();break;
case 59:f59();break;
default:break;}}
void main(){
    R[0]=vec4(0.0);R[1]=vec4(0.0);for(int k=0;k<4;++k){T[k]=vec4(0.0);M3[k]=0.0;}TC[0]=in_t0;TC[1]=in_t1;TC[2]=in_t2;TC[3]=in_t3;
    VC[0]=in_d0;VC[1]=in_d1;
    // Unrolled with constant indices (dynamic indexing misbehaved on the
    // console GPU, 2026-09-30); a negative entry ends the list.
    if(program[0].x>=0)run(program[0].x);if(program[0].y>=0)run(program[0].y);if(program[0].z>=0)run(program[0].z);if(program[0].w>=0)run(program[0].w);if(program[1].x>=0)run(program[1].x);if(program[1].y>=0)run(program[1].y);if(program[1].z>=0)run(program[1].z);if(program[1].w>=0)run(program[1].w);if(program[2].x>=0)run(program[2].x);if(program[2].y>=0)run(program[2].y);if(program[2].z>=0)run(program[2].z);if(program[2].w>=0)run(program[2].w);if(program[3].x>=0)run(program[3].x);if(program[3].y>=0)run(program[3].y);if(program[3].z>=0)run(program[3].z);if(program[3].w>=0)run(program[3].w);
    vec4 c=R[0];
    // Fixed-function stages after the pixel shader: alpha test, fog.
    // Console diagnostic (alpha_test.w, Minus button): 2 = output alpha as grey, 3 = vertex diffuse alpha, 1 = no alpha test.
    if(alpha_test.w>=7.0){out_colour=vec4(in_d0.rgb,1.0);return;}
    if(alpha_test.w>=5.0){out_colour=vec4(1.0,0.0,0.0,1.0);return;}
    if(alpha_test.w==2.0){out_colour=vec4(vec3(clamp(c.a,0.0,1.0)),1.0);return;}
    if(alpha_test.w==3.0){out_colour=vec4(vec3(clamp(in_d0.a,0.0,1.0)),1.0);return;}
    if(alpha_test.x!=0.0&&alpha_test.w!=1.0){float a=floor(clamp(c.a,0.0,1.0)*255.0+0.5);float ref=alpha_test.y;int f=int(alpha_test.z);
        bool pass=f==8||(f==2&&a<ref)||(f==3&&a==ref)||(f==4&&a<=ref)||(f==5&&a>ref)||(f==6&&a!=ref)||(f==7&&a>=ref);
        if(!pass)discard;}
    if(fog_params.x!=0.0){float fz=gl_FragCoord.z;float fw=1.0/gl_FragCoord.w;float d=fog_params.w!=0.0?fw:fz;float f;
        int mode=int(fog_params.x);
        if(mode==3)f=(fog_colour.w-d)/max(fog_colour.w-fog_params.y,1e-20);
        else if(mode==1)f=exp(-fog_params.z*d);
        else if(mode==2)f=exp(-(fog_params.z*d)*(fog_params.z*d));
        else f=in_fog;
        f=clamp(f,0.0,1.0);c.rgb=mix(fog_colour.rgb,c.rgb,f);}
    out_colour=c;
}
