// Generated by tools/generate_pc_shaders.py from the hash-pinned EXE. Do not edit.
#version 460

layout(std140,binding=0) uniform PsConstants{vec4 PC[8];};
layout(std140,binding=1) uniform PsProgram{ivec4 program[4];ivec4 info;ivec4 stage_kind[2];vec4 bump[8];vec4 lum[2];};
layout(std140,binding=2) uniform PsFixed{vec4 fog_colour;vec4 fog_params;vec4 alpha_test;};
layout(location=0) in vec4 in_d0;
layout(location=1) in vec4 in_d1;
layout(location=2) in vec4 in_t0;
layout(location=3) in vec4 in_t1;
layout(location=4) in vec4 in_t2;
layout(location=5) in vec4 in_t3;
layout(location=6) in vec4 in_t4;
layout(location=7) in vec4 in_t5;
layout(location=8) in vec4 in_t6;
layout(location=9) in vec4 in_t7;
layout(location=10) in float in_fog;
layout(location=0) out vec4 out_colour;
layout(binding=0) uniform sampler2D tex2d0;
layout(binding=6) uniform samplerCube texcube0;
layout(binding=1) uniform sampler2D tex2d1;
layout(binding=7) uniform samplerCube texcube1;
layout(binding=2) uniform sampler2D tex2d2;
layout(binding=8) uniform samplerCube texcube2;
layout(binding=3) uniform sampler2D tex2d3;
layout(binding=9) uniform samplerCube texcube3;
layout(binding=4) uniform sampler2D tex2d4;
layout(binding=10) uniform samplerCube texcube4;
layout(binding=5) uniform sampler2D tex2d5;
layout(binding=11) uniform samplerCube texcube5;
vec4 R[6];vec4 T[6];vec4 VC[2];

vec4 d3d_rcp(float v){float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):1.0/v);return vec4(f);}
vec4 d3d_rsq(float v){v=abs(v);float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):inversesqrt(v));return vec4(f);}
vec4 d3d_lit(vec4 s){vec4 d=vec4(1.0,0.0,0.0,1.0);float p=clamp(s.w,-127.9961,127.9961);
    if(s.x>0.0){d.y=s.x;if(s.y>0.0)d.z=pow(s.y,p);}return d;}
vec4 d3d_dst(vec4 a,vec4 b){return vec4(1.0,a.y*b.y,a.z,b.w);}

vec4 sample_stage(int n,vec4 c){
    if(n==0)return stage_kind[0][0]==1?texture(texcube0,c.xyz):texture(tex2d0,c.xy);
    if(n==1)return stage_kind[0][1]==1?texture(texcube1,c.xyz):texture(tex2d1,c.xy);
    if(n==2)return stage_kind[0][2]==1?texture(texcube2,c.xyz):texture(tex2d2,c.xy);
    if(n==3)return stage_kind[0][3]==1?texture(texcube3,c.xyz):texture(tex2d3,c.xy);
    if(n==4)return stage_kind[1][0]==1?texture(texcube4,c.xyz):texture(tex2d4,c.xy);
    if(n==5)return stage_kind[1][1]==1?texture(texcube5,c.xyz):texture(tex2d5,c.xy);
    return vec4(0.0);}
void f0(){ // 61EDE8
    
}
void f1(){ // 61EDF0
    
}
void f2(){ // 61EDF8
    R[0]=sample_stage(0,T[0]);
}
void f3(){ // 61EE0C
    R[0]=sample_stage(0,T[0]);
    R[1]=sample_stage(1,T[1]);
}
void f4(){ // 61EE2C
    R[0]=sample_stage(0,T[0]);
    R[2]=sample_stage(2,T[2]);
}
void f5(){ // 61EE4C
    R[0]=sample_stage(0,T[0]);
    R[1]=sample_stage(1,T[1]);
    R[2]=sample_stage(2,T[2]);
}
void f6(){ // 61EE78
    R[3]=sample_stage(3,T[3]);
}
void f7(){ // 61EE8C
    R[0]=sample_stage(0,T[0]);
    R[3]=sample_stage(3,T[3]);
}
void f8(){ // 61EEAC
    R[0]=sample_stage(0,T[0]);
    R[1]=sample_stage(1,T[1]);
    R[3]=sample_stage(3,T[3]);
}
void f9(){ // 61EED8
    R[0]=sample_stage(0,T[0]);
    R[1]=sample_stage(1,T[1]);
    R[2]=sample_stage(2,T[2]);
    R[3]=sample_stage(3,T[3]);
}
void f10(){ // 61EF10
    
}
void f11(){ // 61EF18
    vec4 t0=(PC[6]+R[3]);
    R[5].xyz=(t0).xyz;
}
void f12(){ // 61EF30
    vec4 t0=VC[0];
    R[4].xyz=(t0).xyz;
}
void f13(){ // 61EF44
    vec4 t0=(VC[1]*R[0]);
    R[5].xyz=(t0).xyz;
}
void f14(){ // 61EF5C
    vec4 t0=(VC[1]*(R[0]).wwww);
    R[5].xyz=(t0).xyz;
}
void f15(){ // 61EF74
    vec4 t0=(R[0]*VC[0]);
    R[4].xyz=(t0).xyz;
}
void f16(){ // 61EF8C
    vec4 t0=(R[0]*VC[0]);
    R[4].xyz=(t0).xyz;
}
void f17(){ // 61EFA4
    vec4 t0=(R[0]*R[5]+VC[0]);
    R[4].xyz=(t0).xyz;
}
void f18(){ // 61EFC0
    vec4 t0=(R[0]*(R[0]).wwww);
    R[5].xyz=(t0).xyz;
    vec4 t1=(VC[0]*(vec4(1.0)-((R[0]).wwww))+R[5]);
    R[4].xyz=(t1).xyz;
}
void f19(){ // 61EFEC
    vec4 t0=R[0];
    R[4].xyz=(t0).xyz;
}
void f20(){ // 61F000
    vec4 t0=(R[1]*VC[1]);
    R[5].xyz=(t0).xyz;
}
void f21(){ // 61F018
    vec4 t0=(R[1]*R[4]);
    R[4].xyz=(t0).xyz;
}
void f22(){ // 61F030
    vec4 t0=(R[1]*R[4]);
    R[4].xyz=(((t0)*2.0)).xyz;
}
void f23(){ // 61F048
    vec4 t0=(R[2]*R[4]);
    R[4].xyz=(t0).xyz;
}
void f24(){ // 61F060
    vec4 t0=(R[1]*R[5]+R[4]);
    R[4].xyz=(t0).xyz;
}
void f25(){ // 61F07C
    vec4 t0=(R[1]*(R[1]).wwww);
    R[5].xyz=(t0).xyz;
    vec4 t1=(R[4]*(vec4(1.0)-((R[1]).wwww))+R[5]);
    R[4].xyz=(t1).xyz;
}
void f26(){ // 61F0A8
    vec4 t0=(R[1]+R[4]);
    R[4].xyz=(t0).xyz;
}
void f27(){ // 61F0C0
    vec4 t0=(R[4]*R[5]);
    R[4].xyz=(t0).xyz;
}
void f28(){ // 61F0D8
    
}
void f29(){ // 61F0E0
    vec4 t0=(R[3]*PC[6]+R[4]);
    R[4].xyz=(t0).xyz;
}
void f30(){ // 61F0FC
    vec4 t0=((R[4]).wwww*R[1]+R[4]);
    R[4].xyz=(t0).xyz;
}
void f31(){ // 61F118
    vec4 t0=((R[4]).wwww*R[2]+R[4]);
    R[4].xyz=(t0).xyz;
}
void f32(){ // 61F134
    vec4 t0=((PC[6]).wwww+(R[3]).wwww);
    R[5].w=(t0).w;
}
void f33(){ // 61F14C
    vec4 t0=((vec4(1.0)-((VC[1]).wwww))*(R[0]).wwww+(VC[1]).wwww);
    R[5].xyz=(t0).xyz;
}
void f34(){ // 61F168
    vec4 t0=((vec4(1.0)-((VC[1]).wwww))*(R[1]).wwww+(VC[1]).wwww);
    R[5].xyz=(t0).xyz;
}
void f35(){ // 61F184
    
}
void f36(){ // 61F18C
    vec4 t0=(VC[0]).wwww;
    R[4].w=(t0).w;
}
void f37(){ // 61F1A0
    vec4 t0=((R[0]).wwww*(VC[0]).wwww);
    R[4].w=(t0).w;
}
void f38(){ // 61F1B8
    vec4 t0=((R[1]).wwww*(R[4]).wwww);
    R[4].w=(t0).w;
}
void f39(){ // 61F1D0
    vec4 t0=(R[1]).wwww;
    R[4].w=(t0).w;
}
void f40(){ // 61F1E4
    vec4 t0=(R[2]).wwww;
    R[4].w=(t0).w;
}
void f41(){ // 61F1F8
    vec4 t0=((R[2]).wwww*(R[4]).wwww);
    R[4].w=(t0).w;
}
void f42(){ // 61F210
    
}
void f43(){ // 61F218
    vec4 t0=(R[4]+VC[1]);
    vec4 t1=(R[4]).wwww;
    R[0].xyz=(t0).xyz;
    R[0].w=(t1).w;
}
void run(int id){switch(id){
case 0:f0();break;
case 1:f1();break;
case 2:f2();break;
case 3:f3();break;
case 4:f4();break;
case 5:f5();break;
case 6:f6();break;
case 7:f7();break;
case 8:f8();break;
case 9:f9();break;
case 10:f10();break;
case 11:f11();break;
case 12:f12();break;
case 13:f13();break;
case 14:f14();break;
case 15:f15();break;
case 16:f16();break;
case 17:f17();break;
case 18:f18();break;
case 19:f19();break;
case 20:f20();break;
case 21:f21();break;
case 22:f22();break;
case 23:f23();break;
case 24:f24();break;
case 25:f25();break;
case 26:f26();break;
case 27:f27();break;
case 28:f28();break;
case 29:f29();break;
case 30:f30();break;
case 31:f31();break;
case 32:f32();break;
case 33:f33();break;
case 34:f34();break;
case 35:f35();break;
case 36:f36();break;
case 37:f37();break;
case 38:f38();break;
case 39:f39();break;
case 40:f40();break;
case 41:f41();break;
case 42:f42();break;
case 43:f43();break;
default:break;}}
void main(){
    for(int k=0;k<6;++k){R[k]=vec4(0.0);}T[0]=in_t0;T[1]=in_t1;T[2]=in_t2;T[3]=in_t3;T[4]=in_t4;T[5]=in_t5;
    VC[0]=in_d0;VC[1]=in_d1;
    // Unrolled with constant indices (dynamic indexing misbehaved on the
    // console GPU, 2026-09-30); a negative entry ends the list.
    if(program[0].x>=0)run(program[0].x);if(program[0].y>=0)run(program[0].y);if(program[0].z>=0)run(program[0].z);if(program[0].w>=0)run(program[0].w);if(program[1].x>=0)run(program[1].x);if(program[1].y>=0)run(program[1].y);if(program[1].z>=0)run(program[1].z);if(program[1].w>=0)run(program[1].w);if(program[2].x>=0)run(program[2].x);if(program[2].y>=0)run(program[2].y);if(program[2].z>=0)run(program[2].z);if(program[2].w>=0)run(program[2].w);if(program[3].x>=0)run(program[3].x);if(program[3].y>=0)run(program[3].y);if(program[3].z>=0)run(program[3].z);if(program[3].w>=0)run(program[3].w);
    vec4 c=R[0];
    // Fixed-function stages after the pixel shader: alpha test, fog.
    // Console diagnostic (alpha_test.w, Minus button): 2 = output alpha as grey, 3 = vertex diffuse alpha, 1 = no alpha test.
    if(alpha_test.w>=7.0){out_colour=vec4(in_d0.rgb,1.0);return;}
    if(alpha_test.w>=5.0){out_colour=vec4(1.0,0.0,0.0,1.0);return;}
    if(alpha_test.w==2.0){out_colour=vec4(vec3(clamp(c.a,0.0,1.0)),1.0);return;}
    if(alpha_test.w==3.0){out_colour=vec4(vec3(clamp(in_d0.a,0.0,1.0)),1.0);return;}
    if(alpha_test.x!=0.0&&alpha_test.w!=1.0){float a=floor(clamp(c.a,0.0,1.0)*255.0+0.5);float ref=alpha_test.y;int f=int(alpha_test.z);
        bool pass=f==8||(f==2&&a<ref)||(f==3&&a==ref)||(f==4&&a<=ref)||(f==5&&a>ref)||(f==6&&a!=ref)||(f==7&&a>=ref);
        if(!pass)discard;}
    if(fog_params.x!=0.0){float fz=gl_FragCoord.z;float fw=1.0/gl_FragCoord.w;float d=fog_params.w!=0.0?fw:fz;float f;
        int mode=int(fog_params.x);
        if(mode==3)f=(fog_colour.w-d)/max(fog_colour.w-fog_params.y,1e-20);
        else if(mode==1)f=exp(-fog_params.z*d);
        else if(mode==2)f=exp(-(fog_params.z*d)*(fog_params.z*d));
        else f=in_fog;
        f=clamp(f,0.0,1.0);c.rgb=mix(fog_colour.rgb,c.rgb,f);}
    out_colour=c;
}
