// Specialised from pc_vs_uber_vsh.glsl for blobs 5 36 6 10 17 35 26 (tools/generate_pc_spec_shaders.py). Do not edit.
// Generated by tools/generate_pc_shaders.py from the hash-pinned EXE. Do not edit.
#version 460

// The program words follow the constants in one uniform buffer (binding 0,
// 0x1100 bytes): read through a separate binding they reached the
// console GPU wrong (2026-09-30 diagnostic mode 7).
layout(std140,binding=0) uniform VsConstants{vec4 C[256];vec4 P[4];};
layout(std140,binding=2) uniform VsFix{vec4 clip_fix;};
layout(location=0) in vec4 in_v0;
layout(location=1) in vec4 in_v1;
layout(location=2) in vec4 in_v2;
layout(location=3) in vec4 in_v3;
layout(location=4) in vec4 in_v4;
layout(location=5) in vec4 in_v5;
layout(location=6) in vec4 in_v6;
layout(location=7) in vec4 in_v7;
layout(location=8) in vec4 in_v8;
layout(location=9) in vec4 in_v9;
layout(location=10) in vec4 in_v10;
layout(location=11) in vec4 in_v11;
layout(location=12) in vec4 in_v12;
layout(location=13) in vec4 in_v13;
layout(location=14) in vec4 in_v14;
layout(location=15) in vec4 in_v15;
layout(location=0) out vec4 out_d0;
layout(location=1) out vec4 out_d1;
layout(location=2) out vec4 out_t0;
layout(location=3) out vec4 out_t1;
layout(location=4) out vec4 out_t2;
layout(location=5) out vec4 out_t3;
layout(location=6) out vec4 out_t4;
layout(location=7) out vec4 out_t5;
layout(location=8) out vec4 out_t6;
layout(location=9) out vec4 out_t7;
layout(location=10) out float out_fog;
vec4 R[12];vec4 V[16];vec4 oPos;vec4 oFog;vec4 oPts;vec4 oD[2];vec4 oT[8];

vec4 d3d_rcp(float v){float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):1.0/v);return vec4(f);}
vec4 d3d_rsq(float v){v=abs(v);float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):inversesqrt(v));return vec4(f);}
vec4 d3d_lit(vec4 s){vec4 d=vec4(1.0,0.0,0.0,1.0);float p=clamp(s.w,-127.9961,127.9961);
    if(s.x>0.0){d.y=s.x;if(s.y>0.0)d.z=pow(s.y,p);}return d;}
vec4 d3d_dst(vec4 a,vec4 b){return vec4(1.0,a.y*b.y,a.z,b.w);}

void f5(){ // 61F7D4
    
}
void f6(){ // 61F800
    vec4 t0=(V[1]).xxxx;
    R[4].x=(t0).x;
    vec4 t1=((V[1]).xxxx+(V[1]).yyyy);
    R[0].x=(t1).x;
    vec4 t2=((C[0]).wwww+(-((R[0]).xxxx)));
    R[5].x=(t2).x;
    vec4 t3=vec4(dot(V[0],C[84]),dot(V[0],C[85]),dot(V[0],C[86]),dot(V[0],C[87]));
    R[1]=t3;
    vec4 t4=vec4(dot(V[0],C[88]),dot(V[0],C[89]),dot(V[0],C[90]),dot(V[0],C[91]));
    R[2]=t4;
    vec4 t5=((R[4]).xxxx*V[0]);
    R[0]=t5;
    vec4 t6=((V[1]).yyyy*R[1]+R[0]);
    R[0]=t6;
    vec4 t7=((R[5]).xxxx*R[2]+R[0]);
    R[11]=t7;
    vec4 t8=vec4(dot((V[3]).xyz,(C[84]).xyz),dot((V[3]).xyz,(C[85]).xyz),dot((V[3]).xyz,(C[86]).xyz),0.0);
    R[1].xyz=(t8).xyz;
    vec4 t9=vec4(dot((V[3]).xyz,(C[88]).xyz),dot((V[3]).xyz,(C[89]).xyz),dot((V[3]).xyz,(C[90]).xyz),0.0);
    R[2].xyz=(t9).xyz;
    vec4 t10=((R[4]).xxxx*V[3]);
    R[0]=t10;
    vec4 t11=((V[1]).yyyy*R[1]+R[0]);
    R[0]=t11;
    vec4 t12=((R[5]).xxxx*R[2]+R[0]);
    R[10]=t12;
    vec4 t13=vec4(dot(R[11],C[64]),dot(R[11],C[65]),dot(R[11],C[66]),dot(R[11],C[67]));
    oPos=t13;
}
void f10(){ // 61FA98
    vec4 t0=C[18];
    R[9]=t0;
    vec4 t1=C[19];
    R[8]=t1;
}
void f17(){ // 61FC88
    vec4 t0=(R[11]+(-(C[17])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t1).w;
    vec4 t2=(C[32]).wwww;
    R[5].w=(t2).w;
    vec4 t3=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t3).w;
    vec4 t4=(R[0]*(R[1]).wwww);
    R[2]=t4;
    vec4 t5=(R[2]+C[37]);
    R[0]=t5;
    vec4 t6=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t6).w;
    vec4 t7=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t7).w;
    vec4 t8=(R[0]*(R[1]).wwww);
    R[3]=t8;
    vec4 t9=vec4(dot((R[10]).xyz,(R[3]).xyz));
    R[5].y=(t9).y;
    vec4 t10=vec4(dot(((-(R[10]))).xyz,(C[37]).xyz));
    R[5].x=(t10).x;
    vec4 t11=max((R[5]).xxxx,C[0]);
    R[0]=t11;
    vec4 t12=((R[5]).xxxx*C[26]);
    R[1]=t12;
    vec4 t13=(R[1]+C[27]);
    R[1]=t13;
    vec4 t14=(R[1]*R[8]+C[20]);
    R[1]=t14;
    vec4 t15=(R[1]*C[16]);
    R[1]=t15;
    vec4 t16=(R[9]*C[21]);
    R[2]=t16;
    vec4 t17=(R[0]*R[2]+R[1]);
    oD[0]=t17;
    vec4 t18=d3d_lit(R[5]);
    R[0]=t18;
    vec4 t19=((R[0]).zzzz*C[32]);
    oD[1].xyz=(t19).xyz;
}
void f26(){ // 6210E8
    vec4 t0=R[9];
    oT[0]=t0;
}
void f35(){ // 62127C
    vec4 t0=V[7];
    R[9]=t0;
}
void f36(){ // 621290
    
}
void main(){
    for(int k=0;k<12;++k)R[k]=vec4(0.0);
    V[0]=in_v0;V[1]=in_v1;V[2]=in_v2;V[3]=in_v3;V[4]=in_v4;V[5]=in_v5;V[6]=in_v6;V[7]=in_v7;
    V[8]=in_v8;V[9]=in_v9;V[10]=in_v10;V[11]=in_v11;V[12]=in_v12;V[13]=in_v13;V[14]=in_v14;V[15]=in_v15;
    oPos=vec4(0.0);oFog=vec4(1.0);oPts=vec4(0.0);oD[0]=vec4(0.0);oD[1]=vec4(0.0);
    for(int k=0;k<8;++k)oT[k]=vec4(0.0);
    // Blob list as floats (P, after the constants), unrolled with constant
    // indices: integer words and dynamic indexing reached the console GPU
    // wrong (2026-09-30 diagnostic modes 7/8). -1 ends the list.
    f5();f36();f6();f10();f17();f35();f26();
    // D3D9 -> deko3d clip space. With the device's upper-left origin clip +y
    // is the top of the screen, as in D3D9 (hardware: the +y-up SUMO_FE and
    // glyph quads show upright), so y is not flipped. D3D9 pixel centres:
    // x + 1/w, y - 1/h (clip_fix.xy, times w), as Wine's position fixup.
    gl_Position=vec4(oPos.x+clip_fix.x*oPos.w,oPos.y-clip_fix.y*oPos.w,oPos.z,oPos.w);
    // Console diagnostic 6 (clip_fix.w): position = v0 * c64..c67 without the blob program.
    if(clip_fix.w==6.0)gl_Position=vec4(dot(in_v0,C[64]),dot(in_v0,C[65]),dot(in_v0,C[66]),dot(in_v0,C[67]));
    out_d0=clamp(oD[0],0.0,1.0);out_d1=clamp(oD[1],0.0,1.0);
    if(clip_fix.w==7.0){gl_Position=vec4(dot(in_v0,C[64]),dot(in_v0,C[65]),dot(in_v0,C[66]),dot(in_v0,C[67]));
        out_d0=vec4(P[0].x/80.0,P[0].y/80.0,P[0].z/80.0,1.0);}
    if(clip_fix.w==8.0){gl_Position=vec4(dot(in_v0,C[64]),dot(in_v0,C[65]),dot(in_v0,C[66]),dot(in_v0,C[67]));
        out_d0=vec4(clamp(oPos.w/200.0,0.0,1.0),clamp(abs(oPos.x/oPos.w),0.0,1.0),clamp(oPos.z/oPos.w,0.0,1.0),1.0);}
    out_t0=oT[0];out_t1=oT[1];out_t2=oT[2];out_t3=oT[3];out_t4=oT[4];out_t5=oT[5];out_t6=oT[6];out_t7=oT[7];
    out_fog=clamp(oFog.x,0.0,1.0);
}
