// Specialised from pc_ps14_uber_fsh.glsl for blobs 3 15 37 26 38 43 (tools/generate_pc_spec_shaders.py). Do not edit.
// Generated by tools/generate_pc_shaders.py from the hash-pinned EXE. Do not edit.
#version 460

layout(std140,binding=0) uniform PsConstants{vec4 PC[8];};
layout(std140,binding=1) uniform PsProgram{ivec4 program[4];ivec4 info;ivec4 stage_kind[2];vec4 bump[8];vec4 lum[2];};
layout(std140,binding=2) uniform PsFixed{vec4 fog_colour;vec4 fog_params;vec4 alpha_test;};
layout(location=0) in vec4 in_d0;
layout(location=1) in vec4 in_d1;
layout(location=2) in vec4 in_t0;
layout(location=3) in vec4 in_t1;
layout(location=4) in vec4 in_t2;
layout(location=5) in vec4 in_t3;
layout(location=6) in vec4 in_t4;
layout(location=7) in vec4 in_t5;
layout(location=8) in vec4 in_t6;
layout(location=9) in vec4 in_t7;
layout(location=10) in float in_fog;
layout(location=0) out vec4 out_colour;
layout(binding=0) uniform sampler2D tex2d0;
layout(binding=6) uniform samplerCube texcube0;
layout(binding=1) uniform sampler2D tex2d1;
layout(binding=7) uniform samplerCube texcube1;
layout(binding=2) uniform sampler2D tex2d2;
layout(binding=8) uniform samplerCube texcube2;
layout(binding=3) uniform sampler2D tex2d3;
layout(binding=9) uniform samplerCube texcube3;
layout(binding=4) uniform sampler2D tex2d4;
layout(binding=10) uniform samplerCube texcube4;
layout(binding=5) uniform sampler2D tex2d5;
layout(binding=11) uniform samplerCube texcube5;
vec4 R[6];vec4 T[6];vec4 VC[2];

vec4 d3d_rcp(float v){float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):1.0/v);return vec4(f);}
vec4 d3d_rsq(float v){v=abs(v);float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):inversesqrt(v));return vec4(f);}
vec4 d3d_lit(vec4 s){vec4 d=vec4(1.0,0.0,0.0,1.0);float p=clamp(s.w,-127.9961,127.9961);
    if(s.x>0.0){d.y=s.x;if(s.y>0.0)d.z=pow(s.y,p);}return d;}
vec4 d3d_dst(vec4 a,vec4 b){return vec4(1.0,a.y*b.y,a.z,b.w);}

vec4 sample_stage(int n,vec4 c){
    if(n==0)return stage_kind[0][0]==1?texture(texcube0,c.xyz):texture(tex2d0,c.xy);
    if(n==1)return stage_kind[0][1]==1?texture(texcube1,c.xyz):texture(tex2d1,c.xy);
    if(n==2)return stage_kind[0][2]==1?texture(texcube2,c.xyz):texture(tex2d2,c.xy);
    if(n==3)return stage_kind[0][3]==1?texture(texcube3,c.xyz):texture(tex2d3,c.xy);
    if(n==4)return stage_kind[1][0]==1?texture(texcube4,c.xyz):texture(tex2d4,c.xy);
    if(n==5)return stage_kind[1][1]==1?texture(texcube5,c.xyz):texture(tex2d5,c.xy);
    return vec4(0.0);}
void f3(){ // 61EE0C
    R[0]=sample_stage(0,T[0]);
    R[1]=sample_stage(1,T[1]);
}
void f15(){ // 61EF74
    vec4 t0=(R[0]*VC[0]);
    R[4].xyz=(t0).xyz;
}
void f26(){ // 61F0A8
    vec4 t0=(R[1]+R[4]);
    R[4].xyz=(t0).xyz;
}
void f37(){ // 61F1A0
    vec4 t0=((R[0]).wwww*(VC[0]).wwww);
    R[4].w=(t0).w;
}
void f38(){ // 61F1B8
    vec4 t0=((R[1]).wwww*(R[4]).wwww);
    R[4].w=(t0).w;
}
void f43(){ // 61F218
    vec4 t0=(R[4]+VC[1]);
    vec4 t1=(R[4]).wwww;
    R[0].xyz=(t0).xyz;
    R[0].w=(t1).w;
}
void main(){
    for(int k=0;k<6;++k){R[k]=vec4(0.0);}T[0]=in_t0;T[1]=in_t1;T[2]=in_t2;T[3]=in_t3;T[4]=in_t4;T[5]=in_t5;
    VC[0]=in_d0;VC[1]=in_d1;
    // Unrolled with constant indices (dynamic indexing misbehaved on the
    // console GPU, 2026-09-30); a negative entry ends the list.
    f3();f15();f37();f26();f38();f43();
    vec4 c=R[0];
    // Fixed-function stages after the pixel shader: alpha test, fog.
    // Console diagnostic (alpha_test.w, Minus button): 2 = output alpha as grey, 3 = vertex diffuse alpha, 1 = no alpha test.
    if(alpha_test.w>=7.0){out_colour=vec4(in_d0.rgb,1.0);return;}
    if(alpha_test.w>=5.0){out_colour=vec4(1.0,0.0,0.0,1.0);return;}
    if(alpha_test.w==2.0){out_colour=vec4(vec3(clamp(c.a,0.0,1.0)),1.0);return;}
    if(alpha_test.w==3.0){out_colour=vec4(vec3(clamp(in_d0.a,0.0,1.0)),1.0);return;}
    if(alpha_test.x!=0.0&&alpha_test.w!=1.0){float a=floor(clamp(c.a,0.0,1.0)*255.0+0.5);float ref=alpha_test.y;int f=int(alpha_test.z);
        bool pass=f==8||(f==2&&a<ref)||(f==3&&a==ref)||(f==4&&a<=ref)||(f==5&&a>ref)||(f==6&&a!=ref)||(f==7&&a>=ref);
        if(!pass)discard;}
    if(fog_params.x!=0.0){float fz=gl_FragCoord.z;float fw=1.0/gl_FragCoord.w;float d=fog_params.w!=0.0?fw:fz;float f;
        int mode=int(fog_params.x);
        if(mode==3)f=(fog_colour.w-d)/max(fog_colour.w-fog_params.y,1e-20);
        else if(mode==1)f=exp(-fog_params.z*d);
        else if(mode==2)f=exp(-(fog_params.z*d)*(fog_params.z*d));
        else f=in_fog;
        f=clamp(f,0.0,1.0);c.rgb=mix(fog_colour.rgb,c.rgb,f);}
    out_colour=c;
}
