// Generated by tools/generate_pc_shaders.py from the hash-pinned EXE. Do not edit.
#version 460

// The program words follow the constants in one uniform buffer (binding 0,
// 0x1100 bytes): read through a separate binding they reached the
// console GPU wrong (2026-09-30 diagnostic mode 7).
layout(std140,binding=0) uniform VsConstants{vec4 C[256];vec4 P[4];};
layout(std140,binding=2) uniform VsFix{vec4 clip_fix;};
layout(location=0) in vec4 in_v0;
layout(location=1) in vec4 in_v1;
layout(location=2) in vec4 in_v2;
layout(location=3) in vec4 in_v3;
layout(location=4) in vec4 in_v4;
layout(location=5) in vec4 in_v5;
layout(location=6) in vec4 in_v6;
layout(location=7) in vec4 in_v7;
layout(location=8) in vec4 in_v8;
layout(location=9) in vec4 in_v9;
layout(location=10) in vec4 in_v10;
layout(location=11) in vec4 in_v11;
layout(location=12) in vec4 in_v12;
layout(location=13) in vec4 in_v13;
layout(location=14) in vec4 in_v14;
layout(location=15) in vec4 in_v15;
layout(location=0) out vec4 out_d0;
layout(location=1) out vec4 out_d1;
layout(location=2) out vec4 out_t0;
layout(location=3) out vec4 out_t1;
layout(location=4) out vec4 out_t2;
layout(location=5) out vec4 out_t3;
layout(location=6) out vec4 out_t4;
layout(location=7) out vec4 out_t5;
layout(location=8) out vec4 out_t6;
layout(location=9) out vec4 out_t7;
layout(location=10) out float out_fog;
vec4 R[12];vec4 V[16];vec4 oPos;vec4 oFog;vec4 oPts;vec4 oD[2];vec4 oT[8];

vec4 d3d_rcp(float v){float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):1.0/v);return vec4(f);}
vec4 d3d_rsq(float v){v=abs(v);float f=v==1.0?1.0:(v==0.0?uintBitsToFloat(0x7f800000u):inversesqrt(v));return vec4(f);}
vec4 d3d_lit(vec4 s){vec4 d=vec4(1.0,0.0,0.0,1.0);float p=clamp(s.w,-127.9961,127.9961);
    if(s.x>0.0){d.y=s.x;if(s.y>0.0)d.z=pow(s.y,p);}return d;}
vec4 d3d_dst(vec4 a,vec4 b){return vec4(1.0,a.y*b.y,a.z,b.w);}

void f0(){ // 61F64C
    vec4 t0=V[0];
    R[11]=t0;
    vec4 t1=V[3];
    R[10]=t1;
    vec4 t2=vec4(dot(R[11],C[64]),dot(R[11],C[65]),dot(R[11],C[66]),dot(R[11],C[67]));
    oPos=t2;
}
void f1(){ // 61F67C
    
}
void f2(){ // 61F6A0
    vec4 t0=(V[0]*(C[7]).xxxx);
    R[0]=t0;
    vec4 t1=(V[13]*(C[7]).yyyy+R[0]);
    R[11]=t1;
    vec4 t2=(V[3]*(C[7]).xxxx);
    R[1]=t2;
    vec4 t3=(V[14]*(C[7]).yyyy+R[1]);
    R[10]=t3;
    vec4 t4=vec4(dot(R[11],C[64]),dot(R[11],C[65]),dot(R[11],C[66]),dot(R[11],C[67]));
    oPos=t4;
}
void f3(){ // 61F700
    
}
void f4(){ // 61F738
    vec4 t0=(V[1]).xxxx;
    R[4].x=(t0).x;
    vec4 t1=((C[0]).wwww+(-((V[1]).xxxx)));
    R[5].x=(t1).x;
    vec4 t2=vec4(dot(V[0],C[84]),dot(V[0],C[85]),dot(V[0],C[86]),dot(V[0],C[87]));
    R[1]=t2;
    vec4 t3=((R[4]).xxxx*V[0]);
    R[0]=t3;
    vec4 t4=((R[5]).xxxx*R[1]+R[0]);
    R[11]=t4;
    vec4 t5=vec4(dot((V[3]).xyz,(C[84]).xyz),dot((V[3]).xyz,(C[85]).xyz),dot((V[3]).xyz,(C[86]).xyz),0.0);
    R[1].xyz=(t5).xyz;
    vec4 t6=((R[4]).xxxx*V[3]);
    R[0]=t6;
    vec4 t7=((R[5]).xxxx*R[1]+R[0]);
    R[10]=t7;
    vec4 t8=vec4(dot(R[11],C[64]),dot(R[11],C[65]),dot(R[11],C[66]),dot(R[11],C[67]));
    oPos=t8;
}
void f5(){ // 61F7D4
    
}
void f6(){ // 61F800
    vec4 t0=(V[1]).xxxx;
    R[4].x=(t0).x;
    vec4 t1=((V[1]).xxxx+(V[1]).yyyy);
    R[0].x=(t1).x;
    vec4 t2=((C[0]).wwww+(-((R[0]).xxxx)));
    R[5].x=(t2).x;
    vec4 t3=vec4(dot(V[0],C[84]),dot(V[0],C[85]),dot(V[0],C[86]),dot(V[0],C[87]));
    R[1]=t3;
    vec4 t4=vec4(dot(V[0],C[88]),dot(V[0],C[89]),dot(V[0],C[90]),dot(V[0],C[91]));
    R[2]=t4;
    vec4 t5=((R[4]).xxxx*V[0]);
    R[0]=t5;
    vec4 t6=((V[1]).yyyy*R[1]+R[0]);
    R[0]=t6;
    vec4 t7=((R[5]).xxxx*R[2]+R[0]);
    R[11]=t7;
    vec4 t8=vec4(dot((V[3]).xyz,(C[84]).xyz),dot((V[3]).xyz,(C[85]).xyz),dot((V[3]).xyz,(C[86]).xyz),0.0);
    R[1].xyz=(t8).xyz;
    vec4 t9=vec4(dot((V[3]).xyz,(C[88]).xyz),dot((V[3]).xyz,(C[89]).xyz),dot((V[3]).xyz,(C[90]).xyz),0.0);
    R[2].xyz=(t9).xyz;
    vec4 t10=((R[4]).xxxx*V[3]);
    R[0]=t10;
    vec4 t11=((V[1]).yyyy*R[1]+R[0]);
    R[0]=t11;
    vec4 t12=((R[5]).xxxx*R[2]+R[0]);
    R[10]=t12;
    vec4 t13=vec4(dot(R[11],C[64]),dot(R[11],C[65]),dot(R[11],C[66]),dot(R[11],C[67]));
    oPos=t13;
}
void f7(){ // 61F8F4
    
}
void f8(){ // 61F920
    vec4 t0=(V[1]).xxxx;
    R[4].x=(t0).x;
    vec4 t1=((-((V[1]).xxxx))+(-((V[1]).yyyy)));
    R[0].x=(t1).x;
    vec4 t2=((-((V[1]).zzzz))+(C[0]).wwww);
    R[0].y=(t2).y;
    vec4 t3=((R[0]).xxxx+(R[0]).yyyy);
    R[5].x=(t3).x;
    vec4 t4=vec4(dot(V[0],C[84]),dot(V[0],C[85]),dot(V[0],C[86]),dot(V[0],C[87]));
    R[1]=t4;
    vec4 t5=vec4(dot(V[0],C[88]),dot(V[0],C[89]),dot(V[0],C[90]),dot(V[0],C[91]));
    R[2]=t5;
    vec4 t6=vec4(dot(V[0],C[92]),dot(V[0],C[93]),dot(V[0],C[94]),dot(V[0],C[95]));
    R[3]=t6;
    vec4 t7=((R[4]).xxxx*V[0]);
    R[0]=t7;
    vec4 t8=((V[1]).yyyy*R[1]+R[0]);
    R[0]=t8;
    vec4 t9=((V[1]).zzzz*R[2]+R[0]);
    R[0]=t9;
    vec4 t10=((R[5]).xxxx*R[3]+R[0]);
    R[11]=t10;
    vec4 t11=vec4(dot((V[3]).xyz,(C[84]).xyz),dot((V[3]).xyz,(C[85]).xyz),dot((V[3]).xyz,(C[86]).xyz),0.0);
    R[1].xyz=(t11).xyz;
    vec4 t12=vec4(dot((V[3]).xyz,(C[88]).xyz),dot((V[3]).xyz,(C[89]).xyz),dot((V[3]).xyz,(C[90]).xyz),0.0);
    R[2].xyz=(t12).xyz;
    vec4 t13=vec4(dot((V[3]).xyz,(C[92]).xyz),dot((V[3]).xyz,(C[93]).xyz),dot((V[3]).xyz,(C[94]).xyz),0.0);
    R[3].xyz=(t13).xyz;
    vec4 t14=((R[4]).xxxx*V[3]);
    R[0]=t14;
    vec4 t15=((V[1]).yyyy*R[1]+R[0]);
    R[0]=t15;
    vec4 t16=((V[1]).zzzz*R[2]+R[0]);
    R[0]=t16;
    vec4 t17=((R[5]).xxxx*R[3]+R[0]);
    R[10]=t17;
    vec4 t18=vec4(dot(R[11],C[64]),dot(R[11],C[65]),dot(R[11],C[66]),dot(R[11],C[67]));
    oPos=t18;
}
void f9(){ // 61FA6C
    
}
void f10(){ // 61FA98
    vec4 t0=C[18];
    R[9]=t0;
    vec4 t1=C[19];
    R[8]=t1;
}
void f11(){ // 61FAB8
    vec4 t0=V[5];
    R[9]=t0;
    vec4 t1=V[5];
    R[8]=t1;
}
void f12(){ // 61FAD8
    
}
void f13(){ // 61FAEC
    vec4 t0=(V[5]*(C[7]).xxxx);
    R[1]=t0;
    vec4 t1=(V[15]*(C[7]).yyyy+R[1]);
    R[9]=t1;
    vec4 t2=R[9];
    R[8]=t2;
}
void f14(){ // 61FB24
    
}
void f15(){ // 61FB48
    vec4 t0=vec4(dot(((-(R[10]))).xyz,(C[37]).xyz));
    R[5].x=(t0).x;
    vec4 t1=(R[9]*C[21]);
    R[2]=t1;
    vec4 t2=max((R[5]).xxxx,C[0]);
    R[0]=t2;
    vec4 t3=((R[5]).xxxx*C[26]);
    R[1]=t3;
    vec4 t4=(R[1]+C[27]);
    R[1]=t4;
    vec4 t5=(R[1]*R[8]+C[20]);
    R[1]=t5;
    vec4 t6=(R[1]*C[16]);
    R[1]=t6;
    vec4 t7=(R[0]*R[2]+R[1]);
    oD[0]=t7;
    vec4 t8=(C[0]).xxxx;
    oD[1]=t8;
}
void f16(){ // 61FBE8
    vec4 t0=vec4(dot((R[10]).xyz,(C[37]).xyz));
    R[5].x=(t0).x;
    vec4 t1=(R[9]*C[21]);
    R[2]=t1;
    vec4 t2=((R[5]).xxxx*C[26]);
    R[6]=t2;
    vec4 t3=(R[6]+C[27]);
    R[1]=t3;
    vec4 t4=max((R[5]).xxxx,C[0]);
    R[0]=t4;
    vec4 t5=(R[1]*R[8]+C[20]);
    R[1]=t5;
    vec4 t6=(R[1]*C[16]);
    R[1]=t6;
    vec4 t7=(R[0]*R[2]+R[1]);
    oD[0]=t7;
    vec4 t8=(C[0]).xxxx;
    oD[1]=t8;
}
void f17(){ // 61FC88
    vec4 t0=(R[11]+(-(C[17])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t1).w;
    vec4 t2=(C[32]).wwww;
    R[5].w=(t2).w;
    vec4 t3=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t3).w;
    vec4 t4=(R[0]*(R[1]).wwww);
    R[2]=t4;
    vec4 t5=(R[2]+C[37]);
    R[0]=t5;
    vec4 t6=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t6).w;
    vec4 t7=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t7).w;
    vec4 t8=(R[0]*(R[1]).wwww);
    R[3]=t8;
    vec4 t9=vec4(dot((R[10]).xyz,(R[3]).xyz));
    R[5].y=(t9).y;
    vec4 t10=vec4(dot(((-(R[10]))).xyz,(C[37]).xyz));
    R[5].x=(t10).x;
    vec4 t11=max((R[5]).xxxx,C[0]);
    R[0]=t11;
    vec4 t12=((R[5]).xxxx*C[26]);
    R[1]=t12;
    vec4 t13=(R[1]+C[27]);
    R[1]=t13;
    vec4 t14=(R[1]*R[8]+C[20]);
    R[1]=t14;
    vec4 t15=(R[1]*C[16]);
    R[1]=t15;
    vec4 t16=(R[9]*C[21]);
    R[2]=t16;
    vec4 t17=(R[0]*R[2]+R[1]);
    oD[0]=t17;
    vec4 t18=d3d_lit(R[5]);
    R[0]=t18;
    vec4 t19=((R[0]).zzzz*C[32]);
    oD[1].xyz=(t19).xyz;
}
void f18(){ // 61FDC8
    vec4 t0=(R[11]+(-(C[17])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t1).w;
    vec4 t2=(C[32]).wwww;
    R[5].w=(t2).w;
    vec4 t3=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t3).w;
    vec4 t4=(R[0]*(R[1]).wwww);
    R[2]=t4;
    vec4 t5=(R[2]+C[37]);
    R[0]=t5;
    vec4 t6=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t6).w;
    vec4 t7=(C[32]).wwww;
    R[4].w=(t7).w;
    vec4 t8=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t8).w;
    vec4 t9=(R[0]*(R[1]).wwww);
    R[3]=t9;
    vec4 t10=vec4(dot((R[10]).xyz,(R[3]).xyz));
    R[5].y=(t10).y;
    vec4 t11=vec4(dot((R[10]).xyz,(C[37]).xyz));
    R[5].x=(t11).x;
    vec4 t12=((R[5]).xxxx*C[26]);
    R[6]=t12;
    vec4 t13=(R[6]+C[27]);
    R[1]=t13;
    vec4 t14=max((R[5]).xxxx,C[0]);
    R[0]=t14;
    vec4 t15=(R[1]*R[8]+C[20]);
    R[1]=t15;
    vec4 t16=(-((R[5]).xxxx));
    R[4].x=(t16).x;
    vec4 t17=(R[1]*C[16]);
    R[1]=t17;
    vec4 t18=(R[9]*C[21]);
    R[2]=t18;
    vec4 t19=(R[0]*R[2]+R[1]);
    oD[0]=t19;
    vec4 t20=d3d_lit(R[5]);
    R[0]=t20;
    vec4 t21=((R[0]).zzzz*C[32]);
    oD[1].xyz=(t21).xyz;
}
void f19(){ // 61FF20
    vec4 t0=(R[11]+(-(C[40])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t1).x;
    vec4 t2=d3d_rsq(((R[1]).xxxx).w);
    R[2].x=(t2).x;
    vec4 t3=(R[0]*(R[2]).xxxx);
    R[3]=t3;
    vec4 t4=d3d_dst((R[1]).xxxx,(R[2]).xxxx);
    R[0]=t4;
    vec4 t5=vec4(dot((R[0]).xyz,(C[44]).xyz));
    R[2].x=(t5).x;
    vec4 t6=d3d_rcp(((R[2]).xxxx).w);
    R[2].x=(t6).x;
    vec4 t7=vec4(lessThan((R[0]).yyyy,(C[44]).wwww));
    R[1].x=(t7).x;
    vec4 t8=((R[2]).xxxx*(R[1]).xxxx);
    R[2].x=(t8).x;
    vec4 t9=vec4(dot((R[3]).xyz,(C[38]).xyz));
    R[1].x=(t9).x;
    vec4 t10=((R[1]).xxxx*(C[48]).xxxx+(C[48]).yyyy);
    R[0].x=(t10).x;
    vec4 t11=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t11).x;
    vec4 t12=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t12).x;
    vec4 t13=((R[2]).xxxx*(R[0]).xxxx);
    R[2].x=(t13).x;
    vec4 t14=vec4(dot(((-(R[10]))).xyz,(R[3]).xyz));
    R[4].x=(t14).x;
    vec4 t15=max((R[4]).xxxx,C[0]);
    R[0]=t15;
    vec4 t16=(R[0]*(R[2]).xxxx);
    R[0]=t16;
    vec4 t17=(R[0]*C[22]);
    R[5]=t17;
    vec4 t18=((R[2]).xxxx*C[28]);
    R[6]=t18;
    vec4 t19=(R[11]+(-(C[41])));
    R[0]=t19;
    vec4 t20=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t20).x;
    vec4 t21=d3d_rsq(((R[1]).xxxx).w);
    R[2].x=(t21).x;
    vec4 t22=(R[0]*(R[2]).xxxx);
    R[3]=t22;
    vec4 t23=d3d_dst((R[1]).xxxx,(R[2]).xxxx);
    R[0]=t23;
    vec4 t24=vec4(dot((R[0]).xyz,(C[45]).xyz));
    R[2].x=(t24).x;
    vec4 t25=d3d_rcp(((R[2]).xxxx).w);
    R[2].x=(t25).x;
    vec4 t26=vec4(lessThan((R[0]).yyyy,(C[45]).wwww));
    R[1].x=(t26).x;
    vec4 t27=((R[2]).xxxx*(R[1]).xxxx);
    R[2].x=(t27).x;
    vec4 t28=vec4(dot((R[3]).xyz,(C[39]).xyz));
    R[1].x=(t28).x;
    vec4 t29=((R[1]).xxxx*(C[49]).xxxx+(C[49]).yyyy);
    R[0].x=(t29).x;
    vec4 t30=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t30).x;
    vec4 t31=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t31).x;
    vec4 t32=((R[2]).xxxx*(R[0]).xxxx);
    R[2].x=(t32).x;
    vec4 t33=vec4(dot(((-(R[10]))).xyz,(R[3]).xyz));
    R[4].x=(t33).x;
    vec4 t34=max((R[4]).xxxx,C[0]);
    R[0]=t34;
    vec4 t35=(R[0]*(R[2]).xxxx);
    R[0]=t35;
    vec4 t36=(R[0]*C[23]+R[5]);
    R[5]=t36;
    vec4 t37=((R[2]).xxxx*C[29]+R[6]);
    R[6]=t37;
    vec4 t38=vec4(dot(((-(R[10]))).xyz,(C[37]).xyz));
    R[4].x=(t38).x;
    vec4 t39=max((R[4]).xxxx,C[0]);
    R[0]=t39;
    vec4 t40=(R[0]*C[21]+R[5]);
    R[5]=t40;
    vec4 t41=((R[4]).xxxx*C[26]);
    R[1]=t41;
    vec4 t42=(R[1]+C[27]);
    R[1]=t42;
    vec4 t43=(R[1]+R[6]);
    R[6]=t43;
    vec4 t44=(R[6]*R[8]+C[20]);
    R[6]=t44;
    vec4 t45=(R[6]*C[16]);
    R[6]=t45;
    vec4 t46=(R[5]*R[9]+R[6]);
    oD[0]=t46;
    vec4 t47=(C[0]).xxxx;
    oD[1]=t47;
}
void f20(){ // 620230
    vec4 t0=(C[32]).wwww;
    R[3].w=(t0).w;
    vec4 t1=(C[0]).wwww;
    R[6].w=(t1).w;
    vec4 t2=(R[11]+(-(C[17])));
    R[0]=t2;
    vec4 t3=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t3).w;
    vec4 t4=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t4).w;
    vec4 t5=(R[0]*(R[1]).wwww);
    R[4]=t5;
    vec4 t6=(R[11]+(-(C[40])));
    R[0]=t6;
    vec4 t7=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t7).x;
    vec4 t8=d3d_rsq(((R[1]).xxxx).w);
    R[1].y=(t8).y;
    vec4 t9=(R[0]*(R[1]).yyyy);
    R[2].xyz=(t9).xyz;
    vec4 t10=d3d_dst((R[1]).xxxx,(R[1]).yyyy);
    R[0]=t10;
    vec4 t11=vec4(dot((R[0]).xyz,(C[44]).xyz));
    R[2].w=(t11).w;
    vec4 t12=d3d_rcp(((R[2]).wwww).w);
    R[2].w=(t12).w;
    vec4 t13=vec4(lessThan((R[0]).yyyy,(C[44]).wwww));
    R[1].x=(t13).x;
    vec4 t14=((R[2]).wwww*(R[1]).xxxx);
    R[2].w=(t14).w;
    vec4 t15=vec4(dot(((R[2]).xyzz).xyz,(C[38]).xyz));
    R[0].x=(t15).x;
    vec4 t16=((R[0]).xxxx*(C[48]).xxxx+(C[48]).yyyy);
    R[0].x=(t16).x;
    vec4 t17=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t17).x;
    vec4 t18=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t18).x;
    vec4 t19=((R[2]).wwww*(R[0]).xxxx);
    R[2].w=(t19).w;
    vec4 t20=((R[2]).xyzz+R[4]);
    R[1]=t20;
    vec4 t21=vec4(dot((R[1]).xyz,(R[1]).xyz));
    R[0].w=(t21).w;
    vec4 t22=d3d_rsq(((R[0]).wwww).w);
    R[0].w=(t22).w;
    vec4 t23=(R[1]*(R[0]).wwww);
    R[1]=t23;
    vec4 t24=vec4(dot(((-(R[10]))).xyz,(R[1]).xyz));
    R[3].y=(t24).y;
    vec4 t25=vec4(dot(((-(R[10]))).xyz,((R[2]).xyzz).xyz));
    R[3].x=(t25).x;
    vec4 t26=d3d_lit(R[3]);
    R[0]=t26;
    vec4 t27=(R[0]*(R[2]).wwww);
    R[0]=t27;
    vec4 t28=((R[2]).wwww*C[28]);
    R[5]=t28;
    vec4 t29=((R[0]).yyyy*C[22]);
    R[6].xyz=(t29).xyz;
    vec4 t30=((R[0]).zzzz*C[33]);
    R[7]=t30;
    vec4 t31=(R[11]+(-(C[41])));
    R[0]=t31;
    vec4 t32=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t32).x;
    vec4 t33=d3d_rsq(((R[1]).xxxx).w);
    R[1].y=(t33).y;
    vec4 t34=(R[0]*(R[1]).yyyy);
    R[2].xyz=(t34).xyz;
    vec4 t35=d3d_dst((R[1]).xxxx,(R[1]).yyyy);
    R[0]=t35;
    vec4 t36=vec4(dot((R[0]).xyz,(C[45]).xyz));
    R[2].w=(t36).w;
    vec4 t37=d3d_rcp(((R[2]).wwww).w);
    R[2].w=(t37).w;
    vec4 t38=vec4(lessThan((R[0]).yyyy,(C[45]).wwww));
    R[1].x=(t38).x;
    vec4 t39=((R[2]).wwww*(R[1]).xxxx);
    R[2].w=(t39).w;
    vec4 t40=vec4(dot(((R[2]).xyzz).xyz,(C[39]).xyz));
    R[0].x=(t40).x;
    vec4 t41=((R[0]).xxxx*(C[49]).xxxx+(C[49]).yyyy);
    R[0].x=(t41).x;
    vec4 t42=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t42).x;
    vec4 t43=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t43).x;
    vec4 t44=((R[2]).wwww*(R[0]).xxxx);
    R[2].w=(t44).w;
    vec4 t45=vec4(dot((R[10]).xyz,((R[2]).xyzz).xyz));
    R[3].x=(t45).x;
    vec4 t46=max((R[3]).xxxx,C[0]);
    R[0].y=(t46).y;
    vec4 t47=(R[0]*(R[2]).wwww);
    R[0]=t47;
    vec4 t48=((R[2]).wwww*C[29]+R[5]);
    R[5]=t48;
    vec4 t49=((R[0]).yyyy*C[23]+R[6]);
    R[6].xyz=(t49).xyz;
    vec4 t50=vec4(dot((R[10]).xyz,(C[37]).xyz));
    R[3].x=(t50).x;
    vec4 t51=max((R[3]).xxxx,C[0]);
    R[0].y=(t51).y;
    vec4 t52=((R[0]).yyyy*C[21]+R[6]);
    R[6].xyz=(t52).xyz;
    vec4 t53=((R[3]).xxxx*C[26]);
    R[1]=t53;
    vec4 t54=(R[1]+C[27]);
    R[1]=t54;
    vec4 t55=(R[5]+R[1]);
    R[5]=t55;
    vec4 t56=(R[5]*R[8]+C[20]);
    R[5]=t56;
    vec4 t57=(R[5]*C[16]);
    R[5]=t57;
    vec4 t58=(R[6]*R[9]+R[5]);
    oD[0]=t58;
    vec4 t59=R[7];
    oD[1].xyz=(t59).xyz;
}
void f21(){ // 6205F0
    vec4 t0=(R[11]+(-(C[40])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t1).x;
    vec4 t2=d3d_rsq(((R[1]).xxxx).w);
    R[2].x=(t2).x;
    vec4 t3=(R[0]*(R[2]).xxxx);
    R[3]=t3;
    vec4 t4=d3d_dst((R[1]).xxxx,(R[2]).xxxx);
    R[0]=t4;
    vec4 t5=vec4(dot((R[0]).xyz,(C[44]).xyz));
    R[2].x=(t5).x;
    vec4 t6=d3d_rcp(((R[2]).xxxx).w);
    R[2].x=(t6).x;
    vec4 t7=vec4(lessThan((R[0]).yyyy,(C[44]).wwww));
    R[1].x=(t7).x;
    vec4 t8=((R[2]).xxxx*(R[1]).xxxx);
    R[2].x=(t8).x;
    vec4 t9=vec4(dot((R[3]).xyz,(C[38]).xyz));
    R[1].x=(t9).x;
    vec4 t10=((R[1]).xxxx*(C[48]).xxxx+(C[48]).yyyy);
    R[0].x=(t10).x;
    vec4 t11=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t11).x;
    vec4 t12=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t12).x;
    vec4 t13=((R[2]).xxxx*(R[0]).xxxx);
    R[2].x=(t13).x;
    vec4 t14=vec4(dot(((-(R[10]))).xyz,(R[3]).xyz));
    R[4].x=(t14).x;
    vec4 t15=max((R[4]).xxxx,C[0]);
    R[0]=t15;
    vec4 t16=(R[0]*(R[2]).xxxx);
    R[0]=t16;
    vec4 t17=(R[0]*C[22]);
    R[5]=t17;
    vec4 t18=((R[2]).xxxx*C[28]);
    R[6]=t18;
    vec4 t19=(R[11]+(-(C[41])));
    R[0]=t19;
    vec4 t20=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t20).x;
    vec4 t21=d3d_rsq(((R[1]).xxxx).w);
    R[2].x=(t21).x;
    vec4 t22=(R[0]*(R[2]).xxxx);
    R[3]=t22;
    vec4 t23=d3d_dst((R[1]).xxxx,(R[2]).xxxx);
    R[0]=t23;
    vec4 t24=vec4(dot((R[0]).xyz,(C[45]).xyz));
    R[2].x=(t24).x;
    vec4 t25=d3d_rcp(((R[2]).xxxx).w);
    R[2].x=(t25).x;
    vec4 t26=vec4(lessThan((R[0]).yyyy,(C[45]).wwww));
    R[1].x=(t26).x;
    vec4 t27=((R[2]).xxxx*(R[1]).xxxx);
    R[2].x=(t27).x;
    vec4 t28=vec4(dot((R[3]).xyz,(C[39]).xyz));
    R[1].x=(t28).x;
    vec4 t29=((R[1]).xxxx*(C[49]).xxxx+(C[49]).yyyy);
    R[0].x=(t29).x;
    vec4 t30=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t30).x;
    vec4 t31=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t31).x;
    vec4 t32=((R[2]).xxxx*(R[0]).xxxx);
    R[2].x=(t32).x;
    vec4 t33=vec4(dot(((-(R[10]))).xyz,(R[3]).xyz));
    R[4].x=(t33).x;
    vec4 t34=max((R[4]).xxxx,C[0]);
    R[0]=t34;
    vec4 t35=(R[0]*(R[2]).xxxx);
    R[0]=t35;
    vec4 t36=(R[0]*C[23]+R[5]);
    R[5]=t36;
    vec4 t37=((R[2]).xxxx*C[29]+R[6]);
    R[6]=t37;
    vec4 t38=(R[11]+(-(C[42])));
    R[0]=t38;
    vec4 t39=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t39).x;
    vec4 t40=d3d_rsq(((R[1]).xxxx).w);
    R[2].x=(t40).x;
    vec4 t41=(R[0]*(R[2]).xxxx);
    R[3]=t41;
    vec4 t42=d3d_dst((R[1]).xxxx,(R[2]).xxxx);
    R[0]=t42;
    vec4 t43=vec4(dot((R[0]).xyz,(C[46]).xyz));
    R[2].x=(t43).x;
    vec4 t44=d3d_rcp(((R[2]).xxxx).w);
    R[2].x=(t44).x;
    vec4 t45=vec4(lessThan((R[0]).yyyy,(C[46]).wwww));
    R[1].x=(t45).x;
    vec4 t46=((R[2]).xxxx*(R[1]).xxxx);
    R[2].x=(t46).x;
    vec4 t47=vec4(dot(((-(R[10]))).xyz,(R[3]).xyz));
    R[4].x=(t47).x;
    vec4 t48=max((R[4]).xxxx,C[0]);
    R[0]=t48;
    vec4 t49=(R[0]*(R[2]).xxxx);
    R[0]=t49;
    vec4 t50=(R[0]*C[24]+R[5]);
    R[5]=t50;
    vec4 t51=((R[2]).xxxx*C[30]+R[6]);
    R[6]=t51;
    vec4 t52=(R[11]+(-(C[43])));
    R[0]=t52;
    vec4 t53=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t53).x;
    vec4 t54=d3d_rsq(((R[1]).xxxx).w);
    R[2].x=(t54).x;
    vec4 t55=(R[0]*(R[2]).xxxx);
    R[3]=t55;
    vec4 t56=d3d_dst((R[1]).xxxx,(R[2]).xxxx);
    R[0]=t56;
    vec4 t57=vec4(dot((R[0]).xyz,(C[47]).xyz));
    R[2].x=(t57).x;
    vec4 t58=d3d_rcp(((R[2]).xxxx).w);
    R[2].x=(t58).x;
    vec4 t59=vec4(lessThan((R[0]).yyyy,(C[47]).wwww));
    R[1].x=(t59).x;
    vec4 t60=((R[2]).xxxx*(R[1]).xxxx);
    R[2].x=(t60).x;
    vec4 t61=vec4(dot(((-(R[10]))).xyz,(R[3]).xyz));
    R[4].x=(t61).x;
    vec4 t62=max((R[4]).xxxx,C[0]);
    R[0]=t62;
    vec4 t63=(R[0]*(R[2]).xxxx);
    R[0]=t63;
    vec4 t64=(R[0]*C[25]+R[5]);
    R[5]=t64;
    vec4 t65=((R[2]).xxxx*C[31]+R[6]);
    R[6]=t65;
    vec4 t66=vec4(dot(((-(R[10]))).xyz,(C[37]).xyz));
    R[4].x=(t66).x;
    vec4 t67=max((R[4]).xxxx,C[0]);
    R[0]=t67;
    vec4 t68=(R[0]*C[21]+R[5]);
    R[5]=t68;
    vec4 t69=((R[4]).xxxx*C[26]);
    R[1]=t69;
    vec4 t70=(R[1]+C[27]);
    R[1]=t70;
    vec4 t71=(R[1]+R[6]);
    R[6]=t71;
    vec4 t72=(R[6]*R[8]+C[20]);
    R[6]=t72;
    vec4 t73=(R[6]*C[16]);
    R[6]=t73;
    vec4 t74=(R[5]*R[9]+R[6]);
    oD[0]=t74;
    vec4 t75=(C[0]).xxxx;
    oD[1]=t75;
}
void f22(){ // 620AC0
    vec4 t0=(C[32]).wwww;
    R[3].w=(t0).w;
    vec4 t1=(C[0]).wwww;
    R[6].w=(t1).w;
    vec4 t2=(R[11]+(-(C[17])));
    R[0]=t2;
    vec4 t3=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t3).w;
    vec4 t4=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t4).w;
    vec4 t5=(R[0]*(R[1]).wwww);
    R[4]=t5;
    vec4 t6=(R[11]+(-(C[40])));
    R[0]=t6;
    vec4 t7=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t7).x;
    vec4 t8=d3d_rsq(((R[1]).xxxx).w);
    R[1].y=(t8).y;
    vec4 t9=(R[0]*(R[1]).yyyy);
    R[2].xyz=(t9).xyz;
    vec4 t10=d3d_dst((R[1]).xxxx,(R[1]).yyyy);
    R[0]=t10;
    vec4 t11=vec4(dot((R[0]).xyz,(C[44]).xyz));
    R[2].w=(t11).w;
    vec4 t12=d3d_rcp(((R[2]).wwww).w);
    R[2].w=(t12).w;
    vec4 t13=vec4(lessThan((R[0]).yyyy,(C[44]).wwww));
    R[1].x=(t13).x;
    vec4 t14=((R[2]).wwww*(R[1]).xxxx);
    R[2].w=(t14).w;
    vec4 t15=vec4(dot(((R[2]).xyzz).xyz,(C[38]).xyz));
    R[0].x=(t15).x;
    vec4 t16=((R[0]).xxxx*(C[48]).xxxx+(C[48]).yyyy);
    R[0].x=(t16).x;
    vec4 t17=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t17).x;
    vec4 t18=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t18).x;
    vec4 t19=((R[2]).wwww*(R[0]).xxxx);
    R[2].w=(t19).w;
    vec4 t20=((R[2]).xyzz+R[4]);
    R[1]=t20;
    vec4 t21=vec4(dot((R[1]).xyz,(R[1]).xyz));
    R[0].w=(t21).w;
    vec4 t22=d3d_rsq(((R[0]).wwww).w);
    R[0].w=(t22).w;
    vec4 t23=(R[1]*(R[0]).wwww);
    R[1]=t23;
    vec4 t24=vec4(dot(((-(R[10]))).xyz,(R[1]).xyz));
    R[3].y=(t24).y;
    vec4 t25=vec4(dot(((-(R[10]))).xyz,((R[2]).xyzz).xyz));
    R[3].x=(t25).x;
    vec4 t26=d3d_lit(R[3]);
    R[0]=t26;
    vec4 t27=(R[0]*(R[2]).wwww);
    R[0]=t27;
    vec4 t28=((R[2]).wwww*C[28]);
    R[5]=t28;
    vec4 t29=((R[0]).yyyy*C[22]);
    R[6].xyz=(t29).xyz;
    vec4 t30=((R[0]).zzzz*C[33]);
    R[7]=t30;
    vec4 t31=(R[11]+(-(C[41])));
    R[0]=t31;
    vec4 t32=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t32).x;
    vec4 t33=d3d_rsq(((R[1]).xxxx).w);
    R[1].y=(t33).y;
    vec4 t34=(R[0]*(R[1]).yyyy);
    R[2].xyz=(t34).xyz;
    vec4 t35=d3d_dst((R[1]).xxxx,(R[1]).yyyy);
    R[0]=t35;
    vec4 t36=vec4(dot((R[0]).xyz,(C[45]).xyz));
    R[2].w=(t36).w;
    vec4 t37=d3d_rcp(((R[2]).wwww).w);
    R[2].w=(t37).w;
    vec4 t38=vec4(lessThan((R[0]).yyyy,(C[45]).wwww));
    R[1].x=(t38).x;
    vec4 t39=((R[2]).wwww*(R[1]).xxxx);
    R[2].w=(t39).w;
    vec4 t40=vec4(dot(((R[2]).xyzz).xyz,(C[39]).xyz));
    R[0].x=(t40).x;
    vec4 t41=((R[0]).xxxx*(C[49]).xxxx+(C[49]).yyyy);
    R[0].x=(t41).x;
    vec4 t42=max((R[0]).xxxx,(C[0]).xxxx);
    R[0].x=(t42).x;
    vec4 t43=min((R[0]).xxxx,(C[0]).wwww);
    R[0].x=(t43).x;
    vec4 t44=((R[2]).wwww*(R[0]).xxxx);
    R[2].w=(t44).w;
    vec4 t45=vec4(dot(((-(R[10]))).xyz,((R[2]).xyzz).xyz));
    R[3].x=(t45).x;
    vec4 t46=max((R[3]).xxxx,C[0]);
    R[0].y=(t46).y;
    vec4 t47=(R[0]*(R[2]).wwww);
    R[0]=t47;
    vec4 t48=((R[2]).wwww*C[29]+R[5]);
    R[5]=t48;
    vec4 t49=((R[0]).yyyy*C[23]+R[6]);
    R[6].xyz=(t49).xyz;
    vec4 t50=(R[11]+(-(C[42])));
    R[0]=t50;
    vec4 t51=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t51).x;
    vec4 t52=d3d_rsq(((R[1]).xxxx).w);
    R[1].y=(t52).y;
    vec4 t53=(R[0]*(R[1]).yyyy);
    R[2].xyz=(t53).xyz;
    vec4 t54=d3d_dst((R[1]).xxxx,(R[1]).yyyy);
    R[0]=t54;
    vec4 t55=vec4(dot((R[0]).xyz,(C[46]).xyz));
    R[2].w=(t55).w;
    vec4 t56=d3d_rcp(((R[2]).wwww).w);
    R[2].w=(t56).w;
    vec4 t57=vec4(lessThan((R[0]).yyyy,(C[46]).wwww));
    R[1].x=(t57).x;
    vec4 t58=((R[2]).wwww*(R[1]).xxxx);
    R[2].w=(t58).w;
    vec4 t59=vec4(dot(((-(R[10]))).xyz,((R[2]).xyzz).xyz));
    R[3].x=(t59).x;
    vec4 t60=max((R[3]).xxxx,C[0]);
    R[0].y=(t60).y;
    vec4 t61=(R[0]*(R[2]).wwww);
    R[0]=t61;
    vec4 t62=((R[2]).wwww*C[30]+R[5]);
    R[5]=t62;
    vec4 t63=((R[0]).yyyy*C[24]+R[6]);
    R[6].xyz=(t63).xyz;
    vec4 t64=(R[11]+(-(C[43])));
    R[0]=t64;
    vec4 t65=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].x=(t65).x;
    vec4 t66=d3d_rsq(((R[1]).xxxx).w);
    R[1].y=(t66).y;
    vec4 t67=(R[0]*(R[1]).yyyy);
    R[2].xyz=(t67).xyz;
    vec4 t68=d3d_dst((R[1]).xxxx,(R[1]).yyyy);
    R[0]=t68;
    vec4 t69=vec4(dot((R[0]).xyz,(C[47]).xyz));
    R[2].w=(t69).w;
    vec4 t70=d3d_rcp(((R[2]).wwww).w);
    R[2].w=(t70).w;
    vec4 t71=vec4(lessThan((R[0]).yyyy,(C[47]).wwww));
    R[1].x=(t71).x;
    vec4 t72=((R[2]).wwww*(R[1]).xxxx);
    R[2].w=(t72).w;
    vec4 t73=vec4(dot(((-(R[10]))).xyz,((R[2]).xyzz).xyz));
    R[3].x=(t73).x;
    vec4 t74=max((R[3]).xxxx,C[0]);
    R[0].y=(t74).y;
    vec4 t75=(R[0]*(R[2]).wwww);
    R[0]=t75;
    vec4 t76=((R[2]).wwww*C[31]+R[5]);
    R[5]=t76;
    vec4 t77=((R[0]).yyyy*C[25]+R[6]);
    R[6].xyz=(t77).xyz;
    vec4 t78=vec4(dot(((-(R[10]))).xyz,(C[37]).xyz));
    R[3].x=(t78).x;
    vec4 t79=max((R[3]).xxxx,C[0]);
    R[0].y=(t79).y;
    vec4 t80=((R[0]).yyyy*C[21]+R[6]);
    R[6].xyz=(t80).xyz;
    vec4 t81=((R[3]).xxxx*C[26]);
    R[1]=t81;
    vec4 t82=(R[1]+C[27]);
    R[1]=t82;
    vec4 t83=(R[5]+R[1]);
    R[5]=t83;
    vec4 t84=(R[5]*R[8]+C[20]);
    R[5]=t84;
    vec4 t85=(R[5]*C[16]);
    R[5]=t85;
    vec4 t86=(R[6]*R[9]+R[5]);
    oD[0]=t86;
    vec4 t87=R[7];
    oD[1].xyz=(t87).xyz;
}
void f23(){ // 62103C
    vec4 t0=vec4(dot(R[9],C[68]));
    oT[0].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[69]));
    oT[0].y=(t1).y;
}
void f24(){ // 621064
    vec4 t0=vec4(dot(R[9],C[68]));
    oT[0].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[69]));
    oT[0].y=(t1).y;
    vec4 t2=vec4(dot(R[9],C[70]));
    oT[0].z=(t2).z;
}
void f25(){ // 6210A0
    vec4 t0=vec4(dot(R[9],C[68]));
    oT[0].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[69]));
    oT[0].y=(t1).y;
    vec4 t2=vec4(dot(R[9],C[70]));
    oT[0].z=(t2).z;
    vec4 t3=vec4(dot(R[9],C[71]));
    oT[0].w=(t3).w;
}
void f26(){ // 6210E8
    vec4 t0=R[9];
    oT[0]=t0;
}
void f27(){ // 6210FC
    vec4 t0=vec4(dot(R[9],C[72]));
    oT[1].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[73]));
    oT[1].y=(t1).y;
}
void f28(){ // 621124
    vec4 t0=vec4(dot(R[9],C[72]));
    oT[1].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[73]));
    oT[1].y=(t1).y;
    vec4 t2=vec4(dot(R[9],C[74]));
    oT[1].z=(t2).z;
}
void f29(){ // 621160
    vec4 t0=vec4(dot(R[9],C[72]));
    oT[1].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[73]));
    oT[1].y=(t1).y;
    vec4 t2=vec4(dot(R[9],C[74]));
    oT[1].z=(t2).z;
    vec4 t3=vec4(dot(R[9],C[75]));
    oT[1].w=(t3).w;
}
void f30(){ // 6211A8
    vec4 t0=R[9];
    oT[1]=t0;
}
void f31(){ // 6211BC
    vec4 t0=vec4(dot(R[9],C[76]));
    oT[2].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[77]));
    oT[2].y=(t1).y;
}
void f32(){ // 6211E4
    vec4 t0=vec4(dot(R[9],C[76]));
    oT[2].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[77]));
    oT[2].y=(t1).y;
    vec4 t2=vec4(dot(R[9],C[78]));
    oT[2].z=(t2).z;
}
void f33(){ // 621220
    vec4 t0=vec4(dot(R[9],C[76]));
    oT[2].x=(t0).x;
    vec4 t1=vec4(dot(R[9],C[77]));
    oT[2].y=(t1).y;
    vec4 t2=vec4(dot(R[9],C[78]));
    oT[2].z=(t2).z;
    vec4 t3=vec4(dot(R[9],C[79]));
    oT[2].w=(t3).w;
}
void f34(){ // 621268
    vec4 t0=R[9];
    oT[2]=t0;
}
void f35(){ // 62127C
    vec4 t0=V[7];
    R[9]=t0;
}
void f36(){ // 621290
    
}
void f37(){ // 6212A4
    vec4 t0=V[8];
    R[9]=t0;
}
void f38(){ // 6212B8
    
}
void f39(){ // 6212CC
    vec4 t0=V[9];
    R[9]=t0;
}
void f40(){ // 6212E0
    
}
void f41(){ // 6212F4
    vec4 t0=V[10];
    R[9]=t0;
}
void f42(){ // 621308
    
}
void f43(){ // 62131C
    vec4 t0=(V[7]*(C[7]).xxxx);
    R[0]=t0;
    vec4 t1=(V[11]*(C[7]).yyyy+R[0]);
    R[9]=t1;
}
void f44(){ // 621348
    
}
void f45(){ // 621368
    vec4 t0=(V[8]*(C[7]).xxxx);
    R[0]=t0;
    vec4 t1=(V[12]*(C[7]).yyyy+R[0]);
    R[9]=t1;
}
void f46(){ // 621394
    
}
void f47(){ // 6213B4
    vec4 t0=(V[9]*(C[7]).xxxx);
    R[0]=t0;
    vec4 t1=(V[15]*(C[7]).yyyy+R[0]);
    R[9]=t1;
}
void f48(){ // 6213E0
    
}
void f49(){ // 621400
    vec4 t0=(V[10]*(C[7]).xxxx);
    R[0]=t0;
    vec4 t1=(V[15]*(C[7]).yyyy+R[0]);
    R[9]=t1;
}
void f50(){ // 62142C
    
}
void f51(){ // 62144C
    vec4 t0=R[10];
    R[9]=t0;
}
void f52(){ // 621460
    vec4 t0=R[11];
    R[9]=t0;
}
void f53(){ // 621478
    vec4 t0=(R[11]+(-(C[17])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t1).w;
    vec4 t2=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t2).w;
    vec4 t3=(R[0]*(R[1]).wwww);
    R[3]=t3;
    vec4 t4=vec4(dot((R[10]).xyz,(R[3]).xyz));
    R[0].x=(t4).x;
    vec4 t5=((R[0]).xxxx+(R[0]).xxxx);
    R[0].y=(t5).y;
    vec4 t6=(R[10]*(-((R[0]).yyyy))+R[3]);
    R[9]=t6;
}
void f54(){ // 6214F0
    vec4 t0=(R[11]+(-(C[17])));
    R[0]=t0;
    vec4 t1=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t1).w;
    vec4 t2=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t2).w;
    vec4 t3=(R[0]*(R[1]).wwww);
    R[3]=t3;
    vec4 t4=vec4(dot((R[10]).xyz,(R[3]).xyz));
    R[0].x=(t4).x;
    vec4 t5=((R[0]).xxxx+(R[0]).xxxx);
    R[0].y=(t5).y;
    vec4 t6=(R[10]*(-((R[0]).yyyy))+R[3]);
    R[9]=t6;
    vec4 t7=C[9];
    R[1]=t7;
    vec4 t8=max((R[0]).xxxx,(-((R[0]).xxxx)));
    R[0].x=(t8).x;
    vec4 t9=((C[0]).wwww+(-((R[0]).xxxx)));
    R[1].y=(t9).y;
    vec4 t10=d3d_lit(R[1]);
    R[0]=t10;
    vec4 t11=((R[0]).zzzz*(C[9]).xxxx+(C[9]).zzzz);
    oD[1].w=(t11).w;
}
void f55(){ // 6215B8
    vec4 t0=vec4(dot(R[11],C[80]));
    oT[3].x=(t0).x;
    vec4 t1=vec4(dot(R[11],C[81]));
    oT[3].y=(t1).y;
    vec4 t2=vec4(dot(R[11],C[82]));
    oT[3].z=(t2).z;
    vec4 t3=vec4(dot(R[11],C[83]));
    oT[3].w=(t3).w;
}
void f56(){ // 621600
    vec4 t0=vec4(dot(R[11],C[80]));
    oT[3].x=(t0).x;
    vec4 t1=vec4(dot(R[11],C[81]));
    oT[3].y=(t1).y;
    vec4 t2=vec4(dot(R[11],C[82]));
    oT[3].z=(t2).z;
    vec4 t3=vec4(dot(R[11],C[83]));
    oT[3].w=(t3).w;
}
void f57(){ // 621648
    
}
void f58(){ // 621650
    
}
void f59(){ // 6216A0
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=V[7];
    oT[0]=t1;
    vec4 t2=V[8];
    oT[1]=t2;
    vec4 t3=V[3];
    R[2]=t3;
    vec4 t4=(-(V[9]));
    R[3]=t4;
    vec4 t5=((R[3]).zxyy*(R[2]).yzxx);
    R[0]=t5;
    vec4 t6=((R[3]).yzxx*(R[2]).zxyy+(-(R[0])));
    R[4]=t6;
    vec4 t7=((R[4]).zxyy*(R[3]).yzxx);
    R[0]=t7;
    vec4 t8=((R[4]).yzxx*(R[3]).zxyy+(-(R[0])));
    R[5]=t8;
    vec4 t9=vec4(dot((R[4]).xyz,((-(C[37]))).xyz));
    oT[2].x=(t9).x;
    vec4 t10=vec4(dot((R[5]).xyz,((-(C[37]))).xyz));
    oT[2].z=(t10).z;
    vec4 t11=vec4(dot((R[3]).xyz,((-(C[37]))).xyz));
    oT[2].y=(t11).y;
    vec4 t12=(V[0]+(-(C[17])));
    R[0]=t12;
    vec4 t13=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t13).w;
    vec4 t14=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t14).w;
    vec4 t15=(R[0]*(R[1]).wwww);
    R[7]=t15;
    vec4 t16=(R[7]+C[37]);
    R[0]=t16;
    vec4 t17=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t17).w;
    vec4 t18=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t18).w;
    vec4 t19=(R[0]*(R[1]).wwww);
    R[6]=t19;
    vec4 t20=vec4(dot((R[4]).xyz,((-(R[6]))).xyz));
    oT[3].x=(t20).x;
    vec4 t21=vec4(dot((R[5]).xyz,((-(R[6]))).xyz));
    oT[3].z=(t21).z;
    vec4 t22=vec4(dot((R[3]).xyz,((-(R[6]))).xyz));
    oT[3].y=(t22).y;
}
void f60(){ // 621848
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=(V[0]+(-(C[17])));
    R[7]=t1;
    vec4 t2=vec4(dot((R[7]).xyz,(R[7]).xyz));
    R[1].w=(t2).w;
    vec4 t3=(C[32]).wwww;
    R[9].w=(t3).w;
    vec4 t4=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t4).w;
    vec4 t5=(R[7]*(R[1]).wwww);
    R[0]=t5;
    vec4 t6=(R[0]+C[37]);
    R[0]=t6;
    vec4 t7=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t7).w;
    vec4 t8=(C[32]).wwww;
    R[8].w=(t8).w;
    vec4 t9=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t9).w;
    vec4 t10=(R[0]*(R[1]).wwww);
    R[6]=t10;
    vec4 t11=vec4(dot(((-(V[3]))).xyz,(R[6]).xyz));
    R[9].y=(t11).y;
    vec4 t12=vec4(dot((V[3]).xyz,(R[6]).xyz));
    R[8].y=(t12).y;
    vec4 t13=vec4(dot(((-(V[3]))).xyz,(C[37]).xyz));
    R[9].x=(t13).x;
    vec4 t14=max((R[9]).xxxx,C[0]);
    R[0]=t14;
    vec4 t15=((R[9]).xxxx*C[26]);
    R[1]=t15;
    vec4 t16=(R[1]+C[27]);
    R[1]=t16;
    vec4 t17=(R[1]*C[19]);
    R[1]=t17;
    vec4 t18=(R[1]+C[20]);
    R[1]=t18;
    vec4 t19=C[18];
    R[2]=t19;
    vec4 t20=(R[2]*C[21]);
    R[2]=t20;
    vec4 t21=(R[0]*R[2]+R[1]);
    oD[0]=t21;
    vec4 t22=vec4(dot((V[3]).xyz,(C[37]).xyz));
    R[8].x=(t22).x;
    vec4 t23=max((R[8]).xxxx,C[0]);
    R[0]=t23;
    vec4 t24=d3d_lit(R[9]);
    R[0]=t24;
    vec4 t25=d3d_lit(R[8]);
    R[1]=t25;
    vec4 t26=((R[0]).zzzz*(C[32]).xyzz);
    oD[1]=t26;
    vec4 t27=V[3];
    R[2]=t27;
    vec4 t28=V[9];
    R[3]=t28;
    vec4 t29=V[7];
    oT[0]=t29;
    vec4 t30=((R[3]).zxyy*(R[2]).yzxx);
    R[0]=t30;
    vec4 t31=((R[3]).yzxx*(R[2]).zxyy+(-(R[0])));
    R[4]=t31;
    vec4 t32=((R[4]).zxyy*(R[3]).yzxx);
    R[0]=t32;
    vec4 t33=((R[4]).yzxx*(R[3]).zxyy+(-(R[0])));
    R[5]=t33;
    vec4 t34=vec4(dot((R[4]).xyz,(C[72]).xyz));
    oT[1].x=(t34).x;
    vec4 t35=vec4(dot((R[3]).xyz,(C[72]).xyz));
    oT[1].y=(t35).y;
    vec4 t36=vec4(dot((R[5]).xyz,(C[72]).xyz));
    oT[1].z=(t36).z;
    vec4 t37=(-((R[7]).xxxx));
    oT[1].w=(t37).w;
    vec4 t38=vec4(dot((R[4]).xyz,(C[73]).xyz));
    oT[2].x=(t38).x;
    vec4 t39=vec4(dot((R[3]).xyz,(C[73]).xyz));
    oT[2].y=(t39).y;
    vec4 t40=vec4(dot((R[5]).xyz,(C[73]).xyz));
    oT[2].z=(t40).z;
    vec4 t41=(-((R[7]).yyyy));
    oT[2].w=(t41).w;
    vec4 t42=vec4(dot((R[4]).xyz,(C[74]).xyz));
    oT[3].x=(t42).x;
    vec4 t43=vec4(dot((R[3]).xyz,(C[74]).xyz));
    oT[3].y=(t43).y;
    vec4 t44=vec4(dot((R[5]).xyz,(C[74]).xyz));
    oT[3].z=(t44).z;
    vec4 t45=(-((R[7]).zzzz));
    oT[3].w=(t45).w;
}
void f61(){ // 621B38
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=(V[0]+(-(C[17])));
    R[7]=t1;
    vec4 t2=vec4(dot((R[7]).xyz,(R[7]).xyz));
    R[1].w=(t2).w;
    vec4 t3=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t3).w;
    vec4 t4=(C[32]).wwww;
    R[9].w=(t4).w;
    vec4 t5=(R[7]*(R[1]).wwww);
    R[7]=t5;
    vec4 t6=R[7];
    R[0]=t6;
    vec4 t7=(R[0]+C[37]);
    R[0]=t7;
    vec4 t8=vec4(dot((R[0]).xyz,(R[0]).xyz));
    R[1].w=(t8).w;
    vec4 t9=(C[32]).wwww;
    R[8].w=(t9).w;
    vec4 t10=d3d_rsq(((R[1]).wwww).w);
    R[1].w=(t10).w;
    vec4 t11=(R[0]*(R[1]).wwww);
    R[6]=t11;
    vec4 t12=vec4(dot(((-(V[3]))).xyz,(R[6]).xyz));
    R[9].y=(t12).y;
    vec4 t13=vec4(dot((V[3]).xyz,(R[6]).xyz));
    R[8].y=(t13).y;
    vec4 t14=vec4(dot(((-(V[3]))).xyz,(C[37]).xyz));
    R[9].x=(t14).x;
    vec4 t15=max((R[9]).xxxx,C[0]);
    R[0]=t15;
    vec4 t16=((R[9]).xxxx*C[26]);
    R[1]=t16;
    vec4 t17=(R[1]+C[27]);
    R[1]=t17;
    vec4 t18=(R[1]*C[19]);
    R[1]=t18;
    vec4 t19=(R[1]+C[20]);
    R[1]=t19;
    vec4 t20=C[18];
    R[2]=t20;
    vec4 t21=(R[2]*C[21]);
    R[2]=t21;
    vec4 t22=(R[0]*R[2]+R[1]);
    oD[0]=t22;
    vec4 t23=vec4(dot((V[3]).xyz,(C[37]).xyz));
    R[8].x=(t23).x;
    vec4 t24=max((R[8]).xxxx,C[0]);
    R[0]=t24;
    vec4 t25=d3d_lit(R[9]);
    R[0]=t25;
    vec4 t26=((R[0]).zzzz*(C[32]).xyzz);
    oD[1]=t26;
    vec4 t27=V[3];
    R[2]=t27;
    vec4 t28=V[9];
    R[3]=t28;
    vec4 t29=V[7];
    oT[0]=t29;
    vec4 t30=((R[3]).zxyy*(R[2]).yzxx);
    R[0]=t30;
    vec4 t31=((R[3]).yzxx*(R[2]).zxyy+(-(R[0])));
    R[4]=t31;
    vec4 t32=((R[4]).zxyy*(R[3]).yzxx);
    R[0]=t32;
    vec4 t33=((R[4]).yzxx*(R[3]).zxyy+(-(R[0])));
    R[5]=t33;
    vec4 t34=vec4(dot((R[4]).xyz,(C[72]).xyz));
    oT[1].x=(t34).x;
    vec4 t35=vec4(dot((R[3]).xyz,(C[72]).xyz));
    oT[1].y=(t35).y;
    vec4 t36=vec4(dot((R[5]).xyz,(C[72]).xyz));
    oT[1].z=(t36).z;
    vec4 t37=vec4(dot((R[4]).xyz,(C[73]).xyz));
    oT[2].x=(t37).x;
    vec4 t38=vec4(dot((R[3]).xyz,(C[73]).xyz));
    oT[2].y=(t38).y;
    vec4 t39=vec4(dot((R[5]).xyz,(C[73]).xyz));
    oT[2].z=(t39).z;
    vec4 t40=vec4(dot((R[4]).xyz,(C[74]).xyz));
    oT[3].x=(t40).x;
    vec4 t41=vec4(dot((R[3]).xyz,(C[74]).xyz));
    oT[3].y=(t41).y;
    vec4 t42=vec4(dot((R[5]).xyz,(C[74]).xyz));
    oT[3].z=(t42).z;
    vec4 t43=R[7];
    oT[4]=t43;
}
void f62(){ // 621E10
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=V[5];
    R[0]=t1;
    vec4 t2=vec4(greaterThanEqual(R[0],R[0]));
    R[1]=t2;
    vec4 t3=(R[1]+(-(R[0])));
    R[2]=t3;
    vec4 t4=(R[0]*C[8]);
    R[3]=t4;
    vec4 t5=(R[2]*C[7]+R[3]);
    oD[0]=t5;
}
void f63(){ // 621E90
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=C[18];
    oD[0]=t1;
    vec4 t2=(C[0]).xxxx;
    oD[1]=t2;
    vec4 t3=V[7];
    oT[0]=t3;
    vec4 t4=V[8];
    oT[1]=t4;
}
void f64(){ // 621F00
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=(V[5]*C[18]);
    oD[0]=t1;
    vec4 t2=(C[0]).xxxx;
    oD[1]=t2;
    vec4 t3=V[7];
    oT[0]=t3;
    vec4 t4=V[8];
    oT[1]=t4;
}
void f65(){ // 621F80
    vec4 t0=(V[0]*(C[7]).xxxx);
    R[0]=t0;
    vec4 t1=(V[13]*(C[7]).yyyy+R[0]);
    R[1]=t1;
    vec4 t2=vec4(dot(R[1],C[64]),dot(R[1],C[65]),dot(R[1],C[66]),dot(R[1],C[67]));
    oPos=t2;
    vec4 t3=(V[5]*(C[7]).xxxx);
    R[1]=t3;
    vec4 t4=(V[15]*(C[7]).yyyy+R[1]);
    oD[0]=t4;
    vec4 t5=(C[0]).xxxx;
    oD[1]=t5;
    vec4 t6=(V[7]*(C[7]).xxxx);
    R[0]=t6;
    vec4 t7=(V[11]*(C[7]).yyyy+R[0]);
    oT[0].xy=(t7).xy;
}
void f66(){ // 622058
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=C[18];
    oD[0]=t1;
    vec4 t2=vec4(dot(V[0],C[76]));
    oT[2].x=(t2).x;
    vec4 t3=vec4(dot(V[0],C[77]));
    oT[2].y=(t3).y;
    vec4 t4=vec4(dot(V[0],C[78]));
    oT[2].z=(t4).z;
}
void f67(){ // 6220B8
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=V[5];
    oD[0]=t1;
    vec4 t2=vec4(dot(V[0],C[76]));
    oT[2].x=(t2).x;
    vec4 t3=vec4(dot(V[0],C[77]));
    oT[2].y=(t3).y;
    vec4 t4=vec4(dot(V[0],C[78]));
    oT[2].z=(t4).z;
    vec4 t5=vec4(dot(V[0],C[80]));
    oT[3].x=(t5).x;
    vec4 t6=vec4(dot(V[0],C[81]));
    oT[3].y=(t6).y;
    vec4 t7=vec4(dot(V[0],C[82]));
    oT[3].z=(t7).z;
}
void f68(){ // 622158
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=C[18];
    R[0]=t1;
    vec4 t2=(R[0]*C[10]);
    oD[0]=t2;
    vec4 t3=(C[0]).xxxx;
    oD[1]=t3;
    vec4 t4=V[7];
    oT[0]=t4;
}
void f69(){ // 6221C0
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=C[18];
    R[0]=t1;
    vec4 t2=(R[0]*C[10]);
    oD[0]=t2;
    vec4 t3=(C[0]).xxxx;
    oD[1]=t3;
}
void f70(){ // 622210
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=C[18];
    oD[0]=t1;
    vec4 t2=(C[0]).xxxx;
    oD[1]=t2;
    vec4 t3=V[7];
    oT[0]=t3;
}
void f71(){ // 622268
    vec4 t0=vec4(dot(V[0],C[64]),dot(V[0],C[65]),dot(V[0],C[66]),dot(V[0],C[67]));
    oPos=t0;
    vec4 t1=(V[5]*C[18]);
    oD[0]=t1;
    vec4 t2=(C[0]).xxxx;
    oD[1]=t2;
    vec4 t3=V[7];
    oT[0]=t3;
}
void f72(){ // 623E38
    vec4 t0=vec4(dot(V[0],C[64]));
    oPos.x=(t0).x;
    vec4 t1=vec4(dot(V[0],C[65]));
    oPos.y=(t1).y;
    vec4 t2=vec4(dot(V[0],C[66]));
    oPos.z=(t2).z;
    vec4 t3=vec4(dot(V[0],C[67]));
    oPos.w=(t3).w;
}
void run(int id){switch(id){
case 0:f0();break;
case 1:f1();break;
case 2:f2();break;
case 3:f3();break;
case 4:f4();break;
case 5:f5();break;
case 6:f6();break;
case 7:f7();break;
case 8:f8();break;
case 9:f9();break;
case 10:f10();break;
case 11:f11();break;
case 12:f12();break;
case 13:f13();break;
case 14:f14();break;
case 15:f15();break;
case 16:f16();break;
case 17:f17();break;
case 18:f18();break;
case 19:f19();break;
case 20:f20();break;
case 21:f21();break;
case 22:f22();break;
case 23:f23();break;
case 24:f24();break;
case 25:f25();break;
case 26:f26();break;
case 27:f27();break;
case 28:f28();break;
case 29:f29();break;
case 30:f30();break;
case 31:f31();break;
case 32:f32();break;
case 33:f33();break;
case 34:f34();break;
case 35:f35();break;
case 36:f36();break;
case 37:f37();break;
case 38:f38();break;
case 39:f39();break;
case 40:f40();break;
case 41:f41();break;
case 42:f42();break;
case 43:f43();break;
case 44:f44();break;
case 45:f45();break;
case 46:f46();break;
case 47:f47();break;
case 48:f48();break;
case 49:f49();break;
case 50:f50();break;
case 51:f51();break;
case 52:f52();break;
case 53:f53();break;
case 54:f54();break;
case 55:f55();break;
case 56:f56();break;
case 57:f57();break;
case 58:f58();break;
case 59:f59();break;
case 60:f60();break;
case 61:f61();break;
case 62:f62();break;
case 63:f63();break;
case 64:f64();break;
case 65:f65();break;
case 66:f66();break;
case 67:f67();break;
case 68:f68();break;
case 69:f69();break;
case 70:f70();break;
case 71:f71();break;
case 72:f72();break;
default:break;}}
void main(){
    for(int k=0;k<12;++k)R[k]=vec4(0.0);
    V[0]=in_v0;V[1]=in_v1;V[2]=in_v2;V[3]=in_v3;V[4]=in_v4;V[5]=in_v5;V[6]=in_v6;V[7]=in_v7;
    V[8]=in_v8;V[9]=in_v9;V[10]=in_v10;V[11]=in_v11;V[12]=in_v12;V[13]=in_v13;V[14]=in_v14;V[15]=in_v15;
    oPos=vec4(0.0);oFog=vec4(1.0);oPts=vec4(0.0);oD[0]=vec4(0.0);oD[1]=vec4(0.0);
    for(int k=0;k<8;++k)oT[k]=vec4(0.0);
    // Blob list as floats (P, after the constants), unrolled with constant
    // indices: integer words and dynamic indexing reached the console GPU
    // wrong (2026-09-30 diagnostic modes 7/8). -1 ends the list.
    if(P[0].x>=0.0)run(int(P[0].x));if(P[0].y>=0.0)run(int(P[0].y));if(P[0].z>=0.0)run(int(P[0].z));if(P[0].w>=0.0)run(int(P[0].w));if(P[1].x>=0.0)run(int(P[1].x));if(P[1].y>=0.0)run(int(P[1].y));if(P[1].z>=0.0)run(int(P[1].z));if(P[1].w>=0.0)run(int(P[1].w));if(P[2].x>=0.0)run(int(P[2].x));if(P[2].y>=0.0)run(int(P[2].y));if(P[2].z>=0.0)run(int(P[2].z));if(P[2].w>=0.0)run(int(P[2].w));if(P[3].x>=0.0)run(int(P[3].x));if(P[3].y>=0.0)run(int(P[3].y));if(P[3].z>=0.0)run(int(P[3].z));if(P[3].w>=0.0)run(int(P[3].w));
    // D3D9 -> deko3d clip space. With the device's upper-left origin clip +y
    // is the top of the screen, as in D3D9 (hardware: the +y-up SUMO_FE and
    // glyph quads show upright), so y is not flipped. D3D9 pixel centres:
    // x + 1/w, y - 1/h (clip_fix.xy, times w), as Wine's position fixup.
    gl_Position=vec4(oPos.x+clip_fix.x*oPos.w,oPos.y-clip_fix.y*oPos.w,oPos.z,oPos.w);
    // Console diagnostic 6 (clip_fix.w): position = v0 * c64..c67 without the blob program.
    if(clip_fix.w==6.0)gl_Position=vec4(dot(in_v0,C[64]),dot(in_v0,C[65]),dot(in_v0,C[66]),dot(in_v0,C[67]));
    out_d0=clamp(oD[0],0.0,1.0);out_d1=clamp(oD[1],0.0,1.0);
    if(clip_fix.w==7.0){gl_Position=vec4(dot(in_v0,C[64]),dot(in_v0,C[65]),dot(in_v0,C[66]),dot(in_v0,C[67]));
        out_d0=vec4(P[0].x/80.0,P[0].y/80.0,P[0].z/80.0,1.0);}
    if(clip_fix.w==8.0){gl_Position=vec4(dot(in_v0,C[64]),dot(in_v0,C[65]),dot(in_v0,C[66]),dot(in_v0,C[67]));
        out_d0=vec4(clamp(oPos.w/200.0,0.0,1.0),clamp(abs(oPos.x/oPos.w),0.0,1.0),clamp(oPos.z/oPos.w,0.0,1.0),1.0);}
    out_t0=oT[0];out_t1=oT[1];out_t2=oT[2];out_t3=oT[3];out_t4=oT[4];out_t5=oT[5];out_t6=oT[6];out_t7=oT[7];
    out_fog=clamp(oFog.x,0.0,1.0);
}
