#include "platform/world_source_pack.hpp"
#include "platform/course_asset_pack.hpp"
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <cstdio>
#include <zlib.h>
using namespace outrun::platform; namespace fs=std::filesystem;
namespace { unsigned checks{};void req(bool x,const char*m){++checks;if(!x)throw std::runtime_error(m);} void put(const fs::path&p,const std::vector<std::uint8_t>&b){fs::create_directories(p.parent_path());std::ofstream f(p,std::ios::binary);f.write((const char*)b.data(),b.size());}
std::vector<std::uint8_t> zip(const std::uint8_t*p,std::size_t n){uLongf cap=compressBound(n);std::vector<std::uint8_t>b(cap);if(compress2(b.data(),&cap,p,n,Z_BEST_SPEED)!=Z_OK)throw std::runtime_error("zlib");b.resize(cap);return b;}}
int main(int argc,char**argv){try{req(argc==3,"WORLD COURSE");WorldSourcePack old,now;CourseAssetPack course;std::string e;req(load_world_source_pack_file(argv[1],old,&e)&&load_course_asset_pack_file(argv[2],course,&e),"fixtures");auto root=fs::temp_directory_path()/"outrun-r151-retail-world";fs::remove_all(root);const char*paths[7]={"Stage/BEAC/coli_CS_BEAC_bin.sz","Stage/BEAC/cs_CS_BEAC_bin.sz","Stage/BEAC/scn_env_fog_BEAC_bin.sz","Stage/BEAC/scn_env_sun_BEAC_bin.sz","Stage/BEAC/maya_spl_BEAC_bin.sz","Stage/BEAC/oso_cs_beac.sz","Stage/BEAC/cs_ENV_BEAC_bin.sz"};for(int i=0;i<7;i++){auto*p=world_source_bytes(old,old.entries[i]);req(p!=nullptr,"old bytes");put(root/paths[i],zip(p,old.entries[i].size));}put(root/"Scripts/bin/Races.bin",{1});put(root/"Scripts/bin/csc_data_cvt.bin",{1});put(root/"CARS/obj_plcar_250gto_pmt.sz",{1});put(root/"Sprite/spr_SPRANI_SUMO_FE_CVT_Exst.sz",{1});RetailAssetStore store{};req(retail_asset_store_open(store,root.string(),&e),"root");req(build_beac_world_source_from_retail(store,course,now,&e),"direct world");req(now.descriptor_index==15u&&now.entries.size()==old.entries.size(),"identity");for(std::size_t i=0;i<7;i++){req(now.entries[i].descriptor_field==old.entries[i].descriptor_field,"field");req(now.entries[i].guest_path_token==old.entries[i].guest_path_token,"token");req(now.entries[i].size==old.entries[i].size,"size");auto*a=world_source_bytes(now,now.entries[i]);auto*b=world_source_bytes(old,old.entries[i]);req(a&&b&&std::equal(a,a+now.entries[i].size,b),"payload");}fs::remove_all(root);std::printf("retail_world_r151: %u checks passed; seven BEAC files match r150 world bytes\n",checks);return 0;}catch(const std::exception&e){std::fprintf(stderr,"FAILED: %s\n",e.what());return 1;}}
