#!/usr/bin/env python3
"""Translate the retained pixel shaders (switch/shaders GLSL) to HLSL 5.0.

Only the already generated expressions are rewritten, as for the Metal
build (mac/tools/generate_metal_shaders.py). Unknown layout or constructs
fail the build instead of inventing a translation. No retail EXE is needed.

Usage: generate_hlsl_shaders.py <out.hpp>      header for the D3D11 device
       generate_hlsl_shaders.py --dump <dir>   one .hlsl file per program
"""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]

PRELUDE = r'''// Generated by xbox/tools/generate_hlsl_shaders.py. Do not edit.
float4 mk4(float a){return float4(a,a,a,a);}
float4 mk4(bool4 a){return (float4)a;}
float4 mk4(float a,float b,float c,float d){return float4(a,b,c,d);}
float4 mk4(float3 a,float b){return float4(a,b);}
float4 mk4(float2 a,float b,float c){return float4(a,b,c);}
float4 mk4(float2 a,float2 b){return float4(a,b);}
float3 mk3(float a){return float3(a,a,a);}
float3 mk3(float a,float b,float c){return float3(a,b,c);}
float2 mk2(float a){return float2(a,a);}
float2 mk2(float a,float b){return float2(a,b);}
int4 imk4(int a){return int4(a,a,a,a);}
int4 imk4(int a,int b,int c,int d){return int4(a,b,c,d);}
bool4 greaterThan(float4 a,float4 b){return a>b;}
'''

# The vertex stage only forwards the vertices the CPU already transformed
# (PcSoftD3D9Device), like the PS5 GL device.
VERTEX = r'''struct VsIn{float4 p:POSITION;float4 d0:COLOR0;float4 d1:COLOR1;
 float4 t0:TEXCOORD0;float4 t1:TEXCOORD1;float4 t2:TEXCOORD2;float4 t3:TEXCOORD3;
 float4 t4:TEXCOORD4;float4 t5:TEXCOORD5;float4 t6:TEXCOORD6;float4 t7:TEXCOORD7;float fog:TEXCOORD8;};
struct Varying{float4 p:SV_Position;float4 d0:COLOR0;float4 d1:COLOR1;
 float4 t0:TEXCOORD0;float4 t1:TEXCOORD1;float4 t2:TEXCOORD2;float4 t3:TEXCOORD3;
 float4 t4:TEXCOORD4;float4 t5:TEXCOORD5;float4 t6:TEXCOORD6;float4 t7:TEXCOORD7;float fog:TEXCOORD8;};
'''
VERTEX_MAIN = r'''Varying vs_main(VsIn v){Varying o;o.p=v.p;o.d0=v.d0;o.d1=v.d1;o.t0=v.t0;o.t1=v.t1;o.t2=v.t2;o.t3=v.t3;
 o.t4=v.t4;o.t5=v.t5;o.t6=v.t6;o.t7=v.t7;o.fog=v.fog;return o;}
'''

INPUTS = ['d0', 'd1'] + [f't{k}' for k in range(8)] + ['fog']


def translate(name, source):
    source = re.sub(r'^#version[^\n]*\n', '', source, flags=re.M)
    samplers = {}

    def block(m):
        return f'cbuffer {m[2]} : register(b{m[1]}) {{{m[3]}}};'
    source = re.sub(r'layout\(std140,binding=(\d+)\) uniform (\w+)\{([^}]*)\};', block, source)

    def sampler(m):
        binding, kind, ident = int(m[1]), m[2], m[3]
        samplers[ident] = binding % 6
        tex = 'TextureCube' if kind == 'samplerCube' else 'Texture2D'
        return f'{tex} {ident} : register(t{binding});'
    source = re.sub(r'^layout\(binding=(\d+)\) uniform (sampler2D|samplerCube) (\w+);', sampler, source, flags=re.M)
    source = re.sub(r'^layout\(location=\d+\) in (vec4|float) in_(\w+);\n', '', source, flags=re.M)
    source = re.sub(r'^layout\(location=0\) out vec4 out_colour;\n', '', source, flags=re.M)
    # Global working registers are per-invocation statics in HLSL.
    source = re.sub(r'^((?:vec4|float) \w+(?:\[\d+\])?(?:[;,]\w+(?:\[\d+\])?)*;(?:(?:vec4|float) \w+(?:\[\d+\])?;)*)$',
                    lambda m: re.sub(r'(^|;)((?:vec4|float) )', r'\1static \2', m[1]), source, flags=re.M)
    source = re.sub(r'texture\((\w+),', lambda m: f'{m[1]}.Sample(smp{samplers[m[1]]},', source)
    source = re.sub(r'\bivec4\(', 'imk4(', source)
    source = re.sub(r'\bvec([234])\(', r'mk\1(', source)
    for glsl, hlsl in [('ivec4', 'int4'), ('vec4', 'float4'), ('vec3', 'float3'), ('vec2', 'float2')]:
        source = re.sub(r'\b' + glsl + r'\b', hlsl, source)
    source = re.sub(r'\bmix\(', 'lerp(', source)
    source = source.replace('inversesqrt(', 'rsqrt(').replace('uintBitsToFloat(', 'asfloat(')
    source = source.replace('1.0/gl_FragCoord.w', 'g_frag.w').replace('gl_FragCoord', 'g_frag')
    source = re.sub(r'\bfor\(', '[unroll] for(', source)
    source = re.sub(r'\bpass\b', 'passed', source)   # reserved word in HLSL
    source = source.replace('void main()', 'void evaluate()')
    if re.search(r'layout\(|\btexture\(|\bgl_|\bsampler2D\b|\bsamplerCube\b', source):
        raise ValueError(f'untranslated shader construct in {name}')
    inputs = ''.join(f'static float4 in_{k};' if k != 'fog' else 'static float in_fog;' for k in INPUTS)
    statics = f'static float4 g_frag;static float4 out_colour;{inputs}\n'
    smp = ''.join(f'SamplerState smp{k} : register(s{k});' for k in range(6)) + '\n'
    copy = ''.join(f'in_{k}=v.{k};' for k in INPUTS)
    entry = f'float4 ps_main(Varying v):SV_Target{{g_frag=v.p;g_frag.w=v.p.w;{copy}evaluate();return out_colour;}}\n'
    return PRELUDE + VERTEX + smp + statics + source + '\n' + entry


def programs():
    for name, file in [('ffp', 'pc_ffp_fsh.glsl'), ('ps11', 'pc_ps11_uber_fsh.glsl'), ('ps14', 'pc_ps14_uber_fsh.glsl')]:
        yield name, translate(name, (root / 'switch/shaders' / file).read_text())


def main():
    if len(sys.argv) == 3 and sys.argv[1] == '--dump':
        out = Path(sys.argv[2]); out.mkdir(parents=True, exist_ok=True)
        for name, text in programs():
            (out / f'pc_{name}.hlsl').write_text(text + VERTEX_MAIN)
        return
    parts = ['#pragma once\nnamespace outrun::xbox_runtime::hlsl {\n']
    for name, text in programs():
        parts.append(f'inline constexpr const char* {name}=R"OR2HLSL({text}{VERTEX_MAIN})OR2HLSL";\n')
    parts.append('}\n')
    out = Path(sys.argv[1]); out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(''.join(parts))


if __name__ == '__main__':
    main()
