#!/usr/bin/env python3
"""Recover the immutable 4A5830 model data from the owned, pinned PC binary."""
import argparse
import struct
from pathlib import Path
from analyse_exe import PE32
from run_pc_oracle import verify_input


def build(exe):
    digest = verify_input(exe)
    pe = PE32(exe.read_bytes())
    metadata = struct.unpack('<I', pe.va_bytes(0x1039e40, 4))[0]
    rows = []
    collision_rows = []
    for model in range(30):
        definition = struct.unpack('<I', pe.va_bytes(0x5b2f68 + model * 4, 4))[0]
        words = []
        for wheel in range(4):
            words.extend(struct.unpack('<3I', pe.va_bytes(definition + 0x98 + wheel * 0x20, 12)))
        words.extend(struct.unpack('<3I', pe.va_bytes(metadata + model * 0x44 + 0x0c, 12)))
        words.append(struct.unpack('<I', pe.va_bytes(metadata + model * 0x44 + 0x1c, 4))[0])
        words.extend(struct.unpack('<4I', pe.va_bytes(metadata + model * 0x44 + 0x20, 16)))
        rows.append('    {{' + ','.join(f'0x{x:08x}u' for x in words) + '}}')
        collision_rows.append('    {{' + ','.join(f'0x{x:02x}' for x in pe.va_bytes(0x5e8a88 + model * 0x3c, 0x3c)) + '}}')
    return ('#pragma once\n#include <array>\n#include <cstdint>\n'
            '// Generated by tools/build_vehicle_constructor_tables.py.\n'
            f'// Source SHA256: {digest}\n'
            '// 46BBF0: four xyz wheel positions; 4866C0: words +C/+10/+14/+1C/+20/+24/+28/+2C.\n'
            '// Model-ID order, NOT menu order. Float fields retain exact source bits.\n'
            'namespace outrun::platform {\n'
            'inline constexpr std::array<std::array<std::uint32_t,20>,30> VehicleConstructorData{{\n'
            + ',\n'.join(rows) + '\n}};\n'
            '// 520950 collision descriptors, including unused source bytes.\n'
            'inline constexpr std::array<std::array<std::uint8_t,60>,30> VehicleCollisionData{{\n'
            + ',\n'.join(collision_rows) + '\n}};\n}\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('exe', type=Path)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    args.out.write_text(build(args.exe), encoding='utf-8')
