#!/usr/bin/env python3
"""Audit 1 (call-graph completeness): for every function the port implements
or handles, each direct callee in the original must be implemented, handled,
refused on purpose, or at least named (inlined code cites the address).
Callees the port never mentions are listed as gaps, with their callers.

usage: decomp_callgaps.py [--listing steam.asm] [--out-dir work/decomp]
"""
import argparse, bisect, collections, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import decomp_status as ds

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--listing', default=os.path.join(ds.ROOT, 'work', 'decomp', 'steam_text.asm'))
    ap.add_argument('--out-dir', default=os.path.join(ds.ROOT, 'work', 'decomp'))
    a = ap.parse_args()
    ins = ds.listing(a.listing)
    starts = ds.function_starts(ins, open(ds.EXE, 'rb').read())
    size = ds.sizes(starts, ins)
    named, handled, constant, refused, mentioned, tested = ds.scan_port()
    platform = ds.import_callers(starts, ins)
    status = {s: ds.classify(s, named, handled, constant, refused, mentioned, platform) for s in starts}
    calls = collections.defaultdict(set)
    for addr, t in ins:
        m = re.match(r'(?:call|jmp)\s+0x([0-9a-f]+)$', t)
        if not m: continue
        v = int(m.group(1), 16)
        if v not in status: continue
        k = bisect.bisect_right(starts, addr) - 1
        if k < 0: continue
        f = starts[k]
        if f != v and addr < f + size[f]: calls[f].add(v)
    ported = [s for s in starts if status[s] in ('implemented', 'handled', 'constant') and ds.region(s) == 'game']
    gaps = collections.defaultdict(set)
    for f in ported:
        for v in calls[f]:
            if status[v] == 'absent': gaps[v].add(f)
    rows = sorted(gaps.items(), key=lambda kv: (-len(kv[1]), kv[0]))
    os.makedirs(a.out_dir, exist_ok=True)
    out = ['# Call audit: functions called by ported code but never named in the port\n',
           'Generated by `tools/decomp_callgaps.py`. One line = a function of the original called (call or direct jump) '
           'by at least one ported function, whose address appears nowhere in the port. '
           'Either the port replaced it without saying so, or the call is missing.\n',
           'Total: %d functions, %d bytes.\n' % (len(rows), sum(size[v] for v, _ in rows)),
           '| Function | Bytes | Region | Called by (ported) |', '|---|---|---|---|']
    for v, fs in rows:
        out.append('| %06x | %d | %s | %s |' % (v, size[v], ds.region(v), ' '.join('%06x' % f for f in sorted(fs)[:8]) + (' …' if len(fs) > 8 else '')))
    with open(os.path.join(a.out_dir, 'call-audit.md'), 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(out) + '\n')
    print('\n'.join(out[:3]))
    print('\n'.join(out[3:60]))

if __name__ == '__main__':
    main()
