#!/usr/bin/env python3
"""Static audit of the native service dispatchers: every PC address a native
module calls through its service (call(...0xADDR...), p.call(0xADDR...),
svc(0xADDR...), leaf(0xADDR...)) that the module's runtime service never
answers (no `case 0xADDR` in the dispatcher files). Such a call aborts the
module at run time (or falls back to the bulk translation where the runtime
has that fallback).

usage: decomp_service_gaps.py [--out work/decomp/service-gaps.md]
"""
import argparse, collections, csv, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = 'src/platform/'
MGR = P + 'race_manager_runtime.cpp'   # native_race_manager_call: the dispatchers' common fallback
# Not race area (it delegates only its 8 race-manager words).
# module sources -> the dispatcher files that answer their service calls
MODULES = {
    'race area': ([P + 'race_area.cpp'], [P + 'race_area_runtime.cpp']),
    'race end': ([P + 'race_end_modes.cpp', P + 'race_ending.cpp', P + 'race_goal_camera.cpp', P + 'race_name_entry.cpp',
                  P + 'arcade_attract.cpp', P + 'race_ending_services.cpp'], [P + 'race_end_runtime.cpp', P + 'arcade_services.inc', MGR, P + 'race_player_car.cpp']),
    'race traffic': ([P + 'race_traffic.cpp'], [P + 'race_traffic_runtime.cpp', MGR]),
    'race robots': ([P + 'race_robots.cpp', P + 'race_autoscene.cpp', P + 'rob_disp.cpp', P + 'rob_osage.cpp'],
                    [P + 'race_robots_runtime.cpp', MGR]),
    'race ghosts': ([P + 'race_ghost_car.cpp', P + 'race_records.cpp'], [P + 'race_ghosts_runtime.cpp', MGR, P + 'race_area_runtime.cpp', P + 'pc_vehicle_display.cpp']),
    'race hud': ([P + 'race_hud_navi.cpp', P + 'race_hud.cpp'], [P + 'race_hud_runtime.cpp']),
    'particles': ([P + 'race_particles.cpp', P + 'race_particles_init.cpp', P + 'race_particles_effects.cpp',
                   P + 'race_particles_draw.cpp'], [P + 'native_race_effects.cpp', P + 'race_particles.cpp']),
}
BULK_FALLBACK = {'race end', 'race traffic', 'race ghosts', 'race area', 'race robots'}
r_call = re.compile(r'\b(?:call|p\.call|svc|leaf|d\.leaf|byte_call|p\.byte_call|callf|q)\s*\(\s*(?:c\s*,\s*|ctx\s*,\s*)?0x0*([0-9a-fA-F]{6})u?\b')
r_case = re.compile(r'case\s+0x0*([0-9a-fA-F]{6})u?\b|(?:pc|k\.pc|target)\s*==\s*0x0*([0-9a-fA-F]{6})u?\b')

def read(p):
    p = os.path.join(ROOT, p)
    return open(p, encoding='utf-8', errors='replace').read() if os.path.exists(p) else ''

def main():
    a = argparse.ArgumentParser(); a.add_argument('--out', default=os.path.join(ROOT, 'work', 'decomp', 'service-gaps.md'))
    o = a.parse_args()
    info = {}
    fc = os.path.join(ROOT, 'work', 'decomp', 'functions.csv')
    if os.path.exists(fc):
        for r in csv.DictReader(open(fc)): info[int(r['address'], 16)] = r
    lines = ['# Service gaps of the native dispatchers', '',
             'Generated by `tools/decomp_service_gaps.py`. One line = a PC address a native module calls through its',
             'service that the module\'s dispatcher never answers by a `case`. Static: the call may sit on a path that',
             'never runs offline (network, guards); check each one.', '']
    total = 0
    for name, (srcs, disp) in MODULES.items():
        calls = collections.defaultdict(set)
        for s in srcs:
            for i, l in enumerate(read(s).splitlines(), 1):
                code = l.split('//')[0]
                for m in r_call.finditer(code):
                    calls[int(m.group(1), 16)].add('%s:%d' % (os.path.basename(s), i))
        handled = set()
        for d in disp:
            for m in r_case.finditer(read(d)):
                handled.add(int(m.group(1) or m.group(2), 16))
        gaps = sorted(a for a in calls if a not in handled)
        total += len(gaps)
        lines += ['## %s (%d gaps%s)' % (name, len(gaps), ', bulk fallback' if name in BULK_FALLBACK else ''), '',
                  '| Function | Bytes | Tracker | Called from |', '|---|---|---|---|']
        for g in gaps:
            r = info.get(g, {})
            lines.append('| %06x | %s | %s %s | %s |' % (g, r.get('bytes', '?'), r.get('status', '?'),
                         os.path.basename(r.get('file', '')), ' '.join(sorted(calls[g])[:4])))
        lines.append('')
    os.makedirs(os.path.dirname(o.out), exist_ok=True)
    open(o.out, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
    print('%d gaps -> %s' % (total, o.out))

if __name__ == '__main__':
    main()
