#!/usr/bin/env python3
"""Protection gate sites of the FXT EXE against the Steam build (the base).

For every game function whose bytes differ between the two EXEs, list each
differing span with the FXT instruction there (a jump into the protection)
and the Steam instruction(s) it replaced (the plain code). The verified
functions (tests cite them) come first: their FXT-measured checks stopped at
these gates, so the Steam instruction is what the port must reproduce there.

usage: decomp_gates.py [--steam-listing d/steam.asm] [--fxt-listing d/text.asm]
Output: work/decomp/gates.md"""
import argparse, bisect, csv, os, re, struct, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import decomp_status as ds

def listing(path):
    rx = re.compile(r'\s+([0-9a-f]+):\t(.*)$'); out = {}
    for l in open(path, encoding='utf-8', errors='replace'):
        m = rx.match(l.rstrip('\n'))
        if m: out[int(m.group(1), 16)] = m.group(2).strip()
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--steam-listing', required=True)
    ap.add_argument('--fxt-listing', required=True)
    ap.add_argument('--out', default=os.path.join(ds.ROOT, 'work', 'decomp', 'gates.md'))
    a = ap.parse_args()
    st = open(ds.STEAM, 'rb').read(); fx = open(ds.FXT, 'rb').read()
    def reader(d):
        secs = ds.pe_sections(d)
        def rd(addr, n):
            for name, va, vs, ro, rs in secs:
                if va <= addr < va + rs: return d[ro + addr - va:ro + min(addr - va + n, rs)]
            return b''
        return rd
    rs, rf = reader(st), reader(fx)
    ls, lf = listing(a.steam_listing), listing(a.fxt_listing)
    sk, fk = sorted(ls), sorted(lf)
    rows = list(csv.DictReader(open(os.path.join(ds.ROOT, 'work', 'decomp', 'functions.csv'), encoding='utf-8')))
    funcs = []
    for r in rows:
        if not r.get('base', '').startswith('steam!=fxt') or r.get('region') != 'game': continue
        f, n = int(r['address'], 16), int(r['bytes'])
        p, q = rs(f, n), rf(f, n)
        spans = []; i = 0
        while i < min(len(p), len(q)):
            if p[i] != q[i]:
                j = i
                while j < len(p) and p[j] != q[j]: j += 1
                spans.append((f + i, f + j)); i = j
            else: i += 1
        funcs.append((r['verified'] == '1', r['status'], f, n, r['file'], spans))
    funcs.sort(key=lambda t: (not t[0], t[2]))
    def ins_at(L, keys, lo, hi):
        k = bisect.bisect_right(keys, lo) - 1
        out = []
        while 0 <= k < len(keys) and keys[k] < hi:
            out.append('%x %s' % (keys[k], L[keys[k]])); k += 1
        return out
    o = ['# Protection gates: FXT against Steam\n',
         'Generated by `tools/decomp_gates.py`. For each game function whose bytes differ between the FXT EXE '
         '(protected) and the Steam EXE (the base), every differing span with the FXT instruction (a jump into the protection) '
         'and the plain Steam instruction it replaces. Verified functions come first: their measurements '
         'on the FXT stopped at these gates, so the Steam instruction is what the port must reproduce.\n',
         '%d functions, %d of them verified.\n' % (len(funcs), sum(1 for t in funcs if t[0]))]
    for ver, stt, f, n, fl, spans in funcs:
        o.append('\n## %06x (%d bytes, %s%s) %s\n' % (f, n, stt, ', verified' if ver else '', fl))
        for lo, hi in spans:
            o.append('- %x..%x: FXT `%s` -> Steam `%s`' % (lo, hi, '; '.join(ins_at(lf, fk, lo, hi)), '; '.join(ins_at(ls, sk, lo, hi))))
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    open(a.out, 'w', encoding='utf-8').write('\n'.join(o) + '\n')
    print('\n'.join(o[:3]))

if __name__ == '__main__':
    main()
