#!/usr/bin/env python3
"""Emit src/platform/race_area_data.cpp: the initial .data images of the race
AREA (635F2C..636BC4) and SKY (638664..638674) modules of the pinned
OR2006C2C.EXE. Usage:
    python3 tools/extract_race_area_data.py ../OR2006C2C.EXE src/platform/race_area_data.cpp
"""
import hashlib, struct, sys

# The base is the unpacked Steam build (7c4e8ec6...); the protected OR2006C2C.EXE
# (bdafa88a...) is the same build with the same data and is still accepted.
STEAM_SHA256 = '7c4e8ec6fcc54e04bfd82e6165e789dfe462e898dcde6f1107d7cc72799fa93d'
EXE_SHA256 = 'bdafa88a5abdd2a9743f6bdcc5e2189288c0203790412fce10b9bb649933482f'
ACCEPTED_SHA256 = (STEAM_SHA256, EXE_SHA256)
RANGES = [
    ('RaceAreaDataImage', 0x635F2C, 0x636BC4, 'area module .data 635F2C..636BC4'),
    ('RaceSkyDataImage', 0x638664, 0x638674, 'sky module .data 638664..638674'),
]

def main():
    exe, out = sys.argv[1], sys.argv[2]
    data = open(exe, 'rb').read()
    if hashlib.sha256(data).hexdigest() not in ACCEPTED_SHA256:
        raise SystemExit('unexpected EXE')
    pe = struct.unpack_from('<I', data, 0x3c)[0]
    count = struct.unpack_from('<H', data, pe + 6)[0]
    opt = struct.unpack_from('<H', data, pe + 20)[0]
    image = struct.unpack_from('<I', data, pe + 24 + 28)[0]
    secs = []
    for i in range(count):
        o = pe + 24 + opt + 40 * i
        vs, va, rs, ro = struct.unpack_from('<IIII', data, o + 8)
        secs.append((image + va, vs, rs, ro))
    def read(a, n):
        for va, vs, rs, ro in secs:
            if va <= a and a + n <= va + max(vs, rs):
                off = a - va
                raw = data[ro + off:ro + min(off + n, rs)] if off < rs else b''
                return raw + b'\0' * (n - len(raw))
        raise SystemExit('address outside sections: %x' % a)
    lines = ['// Generated by tools/extract_race_area_data.py from the unpacked Steam build of OR2006C2C (same data as the pinned OR2006C2C.EXE).',
             '#include <cstddef>', '#include <cstdint>', 'namespace outrun::platform {']
    for name, a, b, what in RANGES:
        d = read(a, b - a)
        lines.append('// %s' % what)
        lines.append('extern const std::uint8_t %s[0x%x];' % (name, b - a))
        lines.append('const std::uint8_t %s[0x%x]={' % (name, b - a))
        for i in range(0, len(d), 32):
            lines.append('    ' + ','.join('0x%02x' % x for x in d[i:i + 32]) + ',')
        lines.append('};')
    lines.append('}')
    open(out, 'w', newline='\n').write('\n'.join(lines) + '\n')

if __name__ == '__main__':
    main()
