#!/usr/bin/env python3
"""Emit src/platform/pc_sound_tables.inc: the static tables of the PC sound
driver (42F0D0 / 427700 / 42EFF0 / 42F330) from the unpacked Steam build of OR2006C2C (same data as the pinned OR2006C2C.EXE).
Usage:
    python3 tools/extract_sound_tables.py ../OR2006C2C.EXE src/platform/pc_sound_tables.inc
"""
import hashlib, struct, sys

# The base is the unpacked Steam build (7c4e8ec6...); the protected OR2006C2C.EXE
# (bdafa88a...) is the same build with the same data and is still accepted.
STEAM_SHA256 = '7c4e8ec6fcc54e04bfd82e6165e789dfe462e898dcde6f1107d7cc72799fa93d'
EXE_SHA256 = 'bdafa88a5abdd2a9743f6bdcc5e2189288c0203790412fce10b9bb649933482f'
ACCEPTED_SHA256 = (STEAM_SHA256, EXE_SHA256)
SOUND_IDS = 0x241          # 7763E0 .. 779104, 20 bytes per id
BANKS = 0xa9               # 6242E8, 12 bytes per bank {name, id list, flag}
ICS_DEFS_COUNT = 0x74d2ec  # count of the 74D2F0 definitions (20 bytes each)


def main():
    exe, out = sys.argv[1], sys.argv[2]
    d = open(exe, 'rb').read()
    if hashlib.sha256(d).hexdigest() not in ACCEPTED_SHA256:
        sys.exit('not the pinned OR2006C2C.EXE')
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    n = struct.unpack_from('<H', d, pe + 6)[0]
    o = pe + 24 + struct.unpack_from('<H', d, pe + 20)[0]
    secs = []
    for i in range(n):
        _, vs, va, rs, ra = struct.unpack_from('<8sIIII', d, o + 40 * i)
        secs.append((va + 0x400000, vs, rs, ra))

    def off(a):
        for v, vs, rs, ra in secs:
            if v <= a < v + rs:
                return ra + a - v
        return None

    def u32(a):
        p = off(a)
        return struct.unpack_from('<I', d, p)[0] if p is not None else 0

    def u16(a):
        p = off(a)
        return struct.unpack_from('<H', d, p)[0] if p is not None else 0

    def cstr(a):
        p = off(a)
        return d[p:d.index(b'\0', p)].decode('ascii')

    L = ['// Generated by tools/extract_sound_tables.py from the unpacked Steam build of OR2006C2C (same data as the pinned OR2006C2C.EXE).',
         '// Sound ids (7763E0 + id*20): rate word +8, volume category word +C;',
         '// voices 773868 / 774170 (ICS buffers) [0 = 1]; ICS base rate word 7790FE + id*8.']
    L.append('constexpr PcSoundIdInfo kSoundIds[%d]={' % SOUND_IDS)
    for i in range(SOUND_IDS):
        L.append('    {%du,%du,%du,%du,%du},' % (u16(0x7763e8 + i * 20), u16(0x7763ec + i * 20),
                                               u32(0x773868 + i * 4), u32(0x774170 + i * 4), u16(0x7790fe + i * 8)))
    L.append('};')
    L.append('// Banks 6242E8 + bank*12: file name and the ids 427700 maps to the slot ({count, ids...}).')
    lists = []
    L.append('constexpr PcSoundBankInfo kSoundBanks[%d]={' % BANKS)
    for b in range(BANKS):
        name = cstr(u32(0x6242e8 + b * 12))
        lst = u32(0x6242e8 + b * 12 + 4)
        ids = []
        if off(lst) is not None and lst < 0x8a0000:
            cnt = struct.unpack('<h', struct.pack('<H', u16(lst)))[0]
            ids = [u16(lst + 2 + 2 * k) for k in range(max(cnt, 0))]
        L.append('    {"%s",%d,%d},' % (name, sum(len(x) for x in lists), len(ids)))
        lists.append(ids)
    L.append('};')
    flat = [x for ids in lists for x in ids]
    L.append('constexpr std::uint16_t kSoundBankIds[%d]={' % max(len(flat), 1))
    for k in range(0, len(flat), 16):
        L.append('    ' + ','.join('0x%x' % x for x in flat[k:k + 16]) + ',')
    L.append('};')
    count = u32(ICS_DEFS_COUNT)
    L.append('// ICS definitions 74D2F0 (%d x {id, ?, layer count, ?, layers}) and their 0xCC-byte layers.' % count)
    layers = []
    L.append('constexpr PcIcsDefinition kIcsDefinitions[%d]={' % count)
    for k in range(count):
        a = 0x74d2f0 + k * 20
        did, nl, lp = u32(a), u32(a + 8), u32(a + 16)
        L.append('    {0x%xu,%du,%du},' % (did, len(layers), nl))
        for j in range(nl):
            p = off(lp + j * 0xcc)
            layers.append(d[p:p + 0xcc])
    L.append('};')
    L.append('constexpr std::uint8_t kIcsLayers[%d][0xcc]={' % len(layers))
    for raw in layers:
        L.append('    {' + ','.join('%d' % b for b in raw) + '},')
    L.append('};')
    open(out, 'w', newline='\n').write('\n'.join(L) + '\n')


if __name__ == '__main__':
    main()
