#!/usr/bin/env python3
"""Emit src/platform/race_robots_data.cpp: the EXE bytes the race robot
module (Lindbergh RobDriver/RobFlagMan, PC 487810..4897EB) reads from the
pinned OR2006C2C.EXE: its .data image 654568..6549C8 (mutable: 6546C0 is
sorted in place by 4884D0) and the read-only .rdata tables/constants.
Usage:
    python3 tools/extract_race_robots_data.py ../OR2006C2C.EXE src/platform/race_robots_data.cpp
"""
import hashlib, struct, sys

# The base is the unpacked Steam build (7c4e8ec6...); the protected OR2006C2C.EXE
# (bdafa88a...) is the same build with the same data and is still accepted.
STEAM_SHA256 = '7c4e8ec6fcc54e04bfd82e6165e789dfe462e898dcde6f1107d7cc72799fa93d'
EXE_SHA256 = 'bdafa88a5abdd2a9743f6bdcc5e2189288c0203790412fce10b9bb649933482f'
ACCEPTED_SHA256 = (STEAM_SHA256, EXE_SHA256)
DATA = ('RaceRobotsDataImage', 0x654568, 0x6549C8, 'robot module .data 654568..6549C8 (driver records, tables, 6546C0 hand-motion list)')
TABLES = [
    (0x5A91BC, 0x5A91C0, '488AF0 network offset scale'),
    (0x5B0CB8, 0x5B2FE0, '46BC10 per-model character position tables (5B2F68 pointer list)'),
    (0x5B4320, 0x5B4324, '488DD0 steering frame scale'),
    (0x5C0B80, 0x5C1630, 'robot motion tables 5C0B80..5C162C'),
    (0x619A34, 0x619A38, 'zero constant'),
    (0x6280C4, 0x6282A8, '487A30/488DD0 float constants 6280C4, 628254, 6282A4'),
]

def main():
    exe, out = sys.argv[1], sys.argv[2]
    data = open(exe, 'rb').read()
    if hashlib.sha256(data).hexdigest() not in ACCEPTED_SHA256:
        raise SystemExit('unexpected EXE')
    pe = struct.unpack_from('<I', data, 0x3c)[0]
    count = struct.unpack_from('<H', data, pe + 6)[0]
    opt = struct.unpack_from('<H', data, pe + 20)[0]
    image = struct.unpack_from('<I', data, pe + 24 + 28)[0]
    secs = []
    for i in range(count):
        o = pe + 24 + opt + 40 * i
        vs, va, rs, ro = struct.unpack_from('<IIII', data, o + 8)
        secs.append((image + va, vs, rs, ro))
    def read(a, n):
        for va, vs, rs, ro in secs:
            if va <= a and a + n <= va + max(vs, rs):
                off = a - va
                raw = data[ro + off:ro + min(off + n, rs)] if off < rs else b''
                return raw + b'\0' * (n - len(raw))
        raise SystemExit('address outside sections: %x' % a)
    def emit(lines, name, d):
        lines.append('const std::uint8_t %s[0x%x]={' % (name, len(d)))
        for i in range(0, len(d), 32):
            lines.append('    ' + ','.join('0x%02x' % x for x in d[i:i + 32]) + ',')
        lines.append('};')
    lines = ['// Generated by tools/extract_race_robots_data.py from the unpacked Steam build of OR2006C2C (same data as the pinned OR2006C2C.EXE).',
             '#include "platform/race_robots.hpp"', 'namespace outrun::platform {']
    name, a, b, what = DATA
    lines.append('// %s' % what)
    emit(lines, name, read(a, b - a))
    lines.append('namespace {')
    for i, (a, b, what) in enumerate(TABLES):
        lines.append('// %08X..%08X %s' % (a, b, what))
        emit(lines, 'Table%d' % i, read(a, b - a))
    lines.append('}')
    lines.append('const PcRaceRobotTable RaceRobotTables[%d]={' % len(TABLES))
    for i, (a, b, what) in enumerate(TABLES):
        lines.append('    {0x%xu,Table%d,sizeof Table%d},' % (a, i, i))
    lines.append('};')
    lines.append('}')
    open(out, 'w', newline='\n').write('\n'.join(lines) + '\n')

if __name__ == '__main__':
    main()
