#!/usr/bin/env python3
"""Specialised PC shaders for the Switch backend.

The uber shaders (switch/shaders/pc_{vs,ps11,ps14}_uber_*.glsl, from
tools/generate_pc_shaders.py) run any created D3D9 shader: its blob list is
read from a uniform and dispatched through a switch over every EXE blob, up to
16 times per vertex/pixel. On the console GPU that costs ~57 ms per race frame
(measured 2026-10-01: 13 fps, fence wait 57 ms). For every program listed in
tools/pc_spec_programs.txt this script writes a shader that calls the blob
functions of that program directly (same function bodies, same epilogue), and
switch/source/pc_spec_shaders.inc, the table SwitchD3D9Device uses to pick
it; programs not listed keep the uber shader.

    python3 tools/generate_pc_spec_shaders.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'switch', 'shaders')
INC = os.path.join(ROOT, 'switch', 'source')
KINDS = {'vs': ('pc_vs_uber_vsh.glsl', 'vsh', 0), 'ps11': ('pc_ps11_uber_fsh.glsl', 'fsh', 1),
         'ps14': ('pc_ps14_uber_fsh.glsl', 'fsh', 2)}


def specialise(text, blobs, kind):
    head, sep, rest = text.partition('void run(int id){switch(id){')
    if not sep:
        raise SystemExit('uber shader without run()')
    funcs = {}
    for m in re.finditer(r'^void f(\d+)\(\)\{.*?^\}\n', head, re.S | re.M):
        funcs[int(m.group(1))] = (m.start(), m.end())
    if not funcs:
        raise SystemExit('uber shader without blob functions')
    first = min(s for s, _ in funcs.values())
    last = max(e for _, e in funcs.values())
    kept = ''.join(head[funcs[b][0]:funcs[b][1]] for b in sorted(set(blobs)))
    main = rest[rest.index('void main(){'):]
    calls = ''.join('f%d();' % b for b in blobs)
    if kind == 'vs':
        main, n = re.subn(r'    if\(P\[0\]\.x>=0\.0\)run\(.*\n', '    ' + calls + '\n', main)
    else:
        main, n = re.subn(r'    if\(program\[0\]\.x>=0\)run\(.*\n', '    ' + calls + '\n', main)
    if n != 1:
        raise SystemExit('dispatch line not found')
    banner = '// Specialised from %s for blobs %s (tools/generate_pc_spec_shaders.py). Do not edit.\n' % (
        KINDS[kind][0], ' '.join(map(str, blobs)))
    return banner + head[:first] + kept + head[last:] + main


def main():
    programs = []
    with open(os.path.join(ROOT, 'tools', 'pc_spec_programs.txt')) as f:
        for line in f:
            line = line.split('#')[0].split()
            if not line:
                continue
            kind, blobs = line[0], [int(x) for x in line[1:]]
            if kind not in KINDS or not 1 <= len(blobs) <= 16:
                raise SystemExit('bad program line: %r' % line)
            if (kind, blobs) not in programs:
                programs.append((kind, blobs))
    for name in os.listdir(SRC):
        if name.startswith('pc_spec_') and name.endswith('.glsl'):
            os.remove(os.path.join(SRC, name))
    uber = {k: open(os.path.join(SRC, v[0])).read() for k, v in KINDS.items()}
    table = ['// Generated by tools/generate_pc_spec_shaders.py from tools/pc_spec_programs.txt. Do not edit.',
             '// {kind (0 vs, 1 ps11, 2 ps14), blob count, blobs, romfs path}']
    for i, (kind, blobs) in enumerate(programs):
        name = 'pc_spec_%s_%d_%s' % (kind, i, KINDS[kind][1])
        with open(os.path.join(SRC, name + '.glsl'), 'w', newline='\n') as f:
            f.write(specialise(uber[kind], blobs, kind))
        table.append('{%d,%d,{%s},"romfs:/shaders/%s.dksh"},' % (
            KINDS[kind][2], len(blobs), ','.join(map(str, blobs)), name))
    with open(os.path.join(INC, 'pc_spec_shaders.inc'), 'w', newline='\n') as f:
        f.write('\n'.join(table) + '\n')
    print('specialised programs: %d' % len(programs))


if __name__ == '__main__':
    main()
