#!/usr/bin/env python3
"""Emit src/platform/embedded_camera_data.cpp for the three camera parameter
tables copied by PC 0x484EE0.

The camera init copies 5B4A30 (0x64C bytes), 5BA4E0 (0x438) and 5B5080 (0x5460)
into its writable globals 818FE8/818BB0/813750. These are EXE-owned data: the
generated file holds their addresses only and points them into the player's
EXE image (system/exe_image) once it is loaded.

Usage: generate_camera_tables.py src/platform/embedded_camera_data.cpp
"""
import hashlib
import struct
import sys

EXPECTED_SHA256 = 'bdafa88a5abdd2a9743f6bdcc5e2189288c0203790412fce10b9bb649933482f'
TABLES = (('EmbeddedCameraTable5b4a30', 0x5B4A30, 0x64C),
          ('EmbeddedCameraTable5ba4e0', 0x5BA4E0, 0x438),
          ('EmbeddedCameraTable5b5080', 0x5B5080, 0x5460))


def read_va(image: bytes, va: int, size: int) -> bytes:
    pe = struct.unpack_from('<I', image, 0x3C)[0]
    count = struct.unpack_from('<H', image, pe + 6)[0]
    optional = struct.unpack_from('<H', image, pe + 20)[0]
    base = struct.unpack_from('<I', image, pe + 24 + 28)[0]
    for i in range(count):
        o = pe + 24 + optional + i * 40
        vsize, rva, rsize, raw = struct.unpack_from('<IIII', image, o + 8)
        if base + rva <= va and va + size <= base + rva + rsize:
            start = raw + va - base - rva
            return image[start:start + size]
    raise SystemExit(f'0x{va:X}+0x{size:X} is not backed by file data')


def main() -> None:
    out = ['// Generated by tools/generate_camera_tables.py: addresses only, data from the player\'s EXE.',
           '#include "platform/embedded_camera_data.hpp"',
           '#include "system/exe_image.hpp"',
           'namespace outrun::platform {']
    for name, va, size in TABLES:
        out.append(f'const std::uint8_t* {name}=nullptr;')
    out.append('void bind_embedded_camera_tables(){')
    for name, va, size in TABLES:
        out.append(f'    {name}=exe_image_bytes(0x{va:X}u,0x{size:X}u);')
    out.append('}')
    out.append('OR2_EXE_BIND(bind_embedded_camera_tables);')
    out.append('} // namespace outrun::platform')
    with open(sys.argv[-1], 'w', newline='\n') as f:
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
