#!/usr/bin/env python3
"""Emit src/platform/embedded_vehicle_draw_data.cpp for the per-model draw
layout records used by PC 0x46AE70.

0x5B2F68[model+variant] points at thirty consecutive 0x128-byte layout records
(object IDs, part positions and angles) starting at 0x5B0CB8. 0x64D120[model]
holds thirty colour-list IDs (guest addresses kept as opaque IDs). Both are
EXE-owned data: the generated file binds them to the player's EXE image
(system/exe_image) and checks the pointer table there.

Usage: generate_vehicle_draw_tables.py src/platform/embedded_vehicle_draw_data.cpp
"""
import hashlib
import struct
import sys

EXPECTED_SHA256 = 'bdafa88a5abdd2a9743f6bdcc5e2189288c0203790412fce10b9bb649933482f'
MODELS = 30
RECORD = 0x128


def reader(image: bytes):
    pe = struct.unpack_from('<I', image, 0x3C)[0]
    count = struct.unpack_from('<H', image, pe + 6)[0]
    optional = struct.unpack_from('<H', image, pe + 20)[0]
    base = struct.unpack_from('<I', image, pe + 24 + 28)[0]
    sections = []
    for i in range(count):
        o = pe + 24 + optional + i * 40
        sections.append(struct.unpack_from('<IIII', image, o + 8))

    def read(va: int, size: int) -> bytes:
        for vsize, rva, rsize, raw in sections:
            if base + rva <= va and va + size <= base + rva + rsize:
                start = raw + va - base - rva
                return image[start:start + size]
        raise SystemExit(f'0x{va:X}+0x{size:X} is not backed by file data')
    return read


def main() -> None:
    out = ['// Generated by tools/generate_vehicle_draw_tables.py: addresses only, data from the player\'s EXE.',
           '#include "platform/embedded_vehicle_draw_data.hpp"',
           '#include "system/exe_image.hpp"',
           '#include <stdexcept>',
           'namespace outrun::platform {',
           'const std::uint8_t* EmbeddedVehicleLayouts=nullptr;',
           f'std::uint32_t EmbeddedVehicleColourIds[{MODELS}]={{}};',
           'void bind_embedded_vehicle_draw_tables(){',
           f'    for(std::uint32_t k=0;k<{MODELS}u;++k)',
           f'        if(exe_image_u32(0x5B2F68u+k*4u)!=0x5B0CB8u+k*0x{RECORD:X}u)throw std::runtime_error("vehicle layout table is not consecutive");',
           f'    EmbeddedVehicleLayouts=exe_image_bytes(0x5B0CB8u,0x{MODELS * RECORD:X}u);',
           f'    for(std::uint32_t k=0;k<{MODELS}u;++k)EmbeddedVehicleColourIds[k]=exe_image_u32(0x64D120u+k*4u);',
           '}',
           'OR2_EXE_BIND(bind_embedded_vehicle_draw_tables);',
           '} // namespace outrun::platform']
    with open(sys.argv[-1], 'w', newline='\n') as f:
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
