#!/usr/bin/env python3
"""Emit src/platform/embedded_shader_data.cpp: the EXE-owned renderer data
(shader fragments, state tables, constants) by PC address.

PC 40E140 links vertex shaders from bytecode fragments selected through the
pointer table at .data 73F000; 40FD70 uses two fixed shaders (pointers at
7420A4/7420A8) with the declarations 625C10/625BE0, and 40F6B0 uploads the
constants 625658/625668/6222CC. All of this lives in the ranges listed here,
together with the renderer state tables and float constants of the flush
(405890 tree: 408C80/409430/40B200/411060 ...). The pointer values are kept as
PC virtual addresses and resolved against these ranges, so the native linker
reads exactly the words the PC reads. The generated file holds addresses only;
the bytes come from the player's EXE image (system/exe_image).

Usage: generate_shader_tables.py src/platform/embedded_shader_data.cpp
"""
import hashlib
import struct
import sys

EXPECTED_SHA256 = 'bdafa88a5abdd2a9743f6bdcc5e2189288c0203790412fce10b9bb649933482f'
RANGES = (('EmbeddedRenderRdata61e700', 0x61E700, 0x625C40 - 0x61E700),
          ('EmbeddedRenderRdata628000', 0x628000, 0x200),
          ('EmbeddedRenderRdata5a91b0', 0x5A91B0, 0x10),
          ('EmbeddedRenderRdata619a30', 0x619A30, 0x10),
          ('EmbeddedRenderData73f000', 0x73F000, 0x110),
          ('EmbeddedRenderData740c98', 0x740C98, 0x8),
          # 74209C: shader token pointers by key (40FE90 / 4105FA: kinds 0..15; 0 and 1 are null).
          ('EmbeddedRenderData74209c', 0x74209C, 0x40),
          ('EmbeddedRenderData64cfa0', 0x64CFA0, 0x1F8),
          ('EmbeddedRenderRdata5b30d0', 0x5B30D0, 0x930),
          # 40AF40: pointers of the six fixed pixel shaders (tokens in 61E700..).
          ('EmbeddedRenderData73dbe4', 0x73DBE4, 0x18),
          # 683980 other-car colour lists (4AD470 colour argument) and their
          # material id records 5C4050..5C45F8 (the 64CFA0 / 5B30D0 layout).
          ('EmbeddedRenderData6837c0', 0x6837C0, 0x1C0),
          ('EmbeddedRenderRdata5c4050', 0x5C4050, 0x5A8),
          # 683A30: the lamp colour list of the traffic / racer cars (4AD7B0 / 4AD880 colour
          # argument) and its five material id records 5C4684..5C4737.
          ('EmbeddedRenderData683a30', 0x683A30, 0x18),
          ('EmbeddedRenderRdata5c4684', 0x5C4684, 0xB4))


def read_va(image: bytes, va: int, size: int) -> bytes:
    pe = struct.unpack_from('<I', image, 0x3C)[0]
    count = struct.unpack_from('<H', image, pe + 6)[0]
    optional = struct.unpack_from('<H', image, pe + 20)[0]
    base = struct.unpack_from('<I', image, pe + 24 + 28)[0]
    for i in range(count):
        o = pe + 24 + optional + i * 40
        vsize, rva, rsize, raw = struct.unpack_from('<IIII', image, o + 8)
        if base + rva <= va and va + size <= base + rva + rsize:
            start = raw + va - base - rva
            return image[start:start + size]
    raise SystemExit(f'0x{va:X}+0x{size:X} is not backed by file data')


def main() -> None:
    out = ['// Generated by tools/generate_shader_tables.py: addresses only, data from the player\'s EXE.',
           '#include "platform/embedded_shader_data.hpp"',
           '#include "system/exe_image.hpp"',
           'namespace outrun::platform {',
           'EmbeddedRenderRange EmbeddedRenderRanges[]={']
    for name, va, size in RANGES:
        out.append(f'    {{0x{va:X}u,0x{size:X}u,nullptr}}, // {name}')
    out.append('};')
    out.append(f'const std::size_t EmbeddedRenderRangeCount={len(RANGES)};')
    out.append('void bind_embedded_render_ranges(){')
    out.append('    for(auto& r:EmbeddedRenderRanges)r.bytes=exe_image_bytes(r.va,r.size);')
    out.append('}')
    out.append('OR2_EXE_BIND(bind_embedded_render_ranges);')
    out.append('} // namespace outrun::platform')
    with open(sys.argv[-1], 'w', newline='\n') as f:
        f.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
