// Generated by tools/generate_vehicle_draw_tables.py: addresses only, data from the player's EXE.
#include "platform/embedded_vehicle_draw_data.hpp"
#include "system/exe_image.hpp"
#include <stdexcept>
namespace outrun::platform {
const std::uint8_t* EmbeddedVehicleLayouts=nullptr;
std::uint32_t EmbeddedVehicleColourIds[30]={};
void bind_embedded_vehicle_draw_tables(){
    for(std::uint32_t k=0;k<30u;++k)
        if(exe_image_u32(0x5B2F68u+k*4u)!=0x5B0CB8u+k*0x128u)throw std::runtime_error("vehicle layout table is not consecutive");
    EmbeddedVehicleLayouts=exe_image_bytes(0x5B0CB8u,0x22B0u);
    for(std::uint32_t k=0;k<30u;++k)EmbeddedVehicleColourIds[k]=exe_image_u32(0x64D120u+k*4u);
}
OR2_EXE_BIND(bind_embedded_vehicle_draw_tables);
} // namespace outrun::platform
