// Generated by tools/generate_shader_tables.py: addresses only, data from the player's EXE.
#include "platform/embedded_shader_data.hpp"
#include "system/exe_image.hpp"
namespace outrun::platform {
EmbeddedRenderRange EmbeddedRenderRanges[]={
    {0x61E700u,0x7540u,nullptr}, // EmbeddedRenderRdata61e700
    {0x628000u,0x200u,nullptr}, // EmbeddedRenderRdata628000
    {0x5A91B0u,0x10u,nullptr}, // EmbeddedRenderRdata5a91b0
    {0x619A30u,0x10u,nullptr}, // EmbeddedRenderRdata619a30
    {0x73F000u,0x110u,nullptr}, // EmbeddedRenderData73f000
    {0x740C98u,0x8u,nullptr}, // EmbeddedRenderData740c98
    {0x74209Cu,0x40u,nullptr}, // EmbeddedRenderData74209c
    {0x64CFA0u,0x1F8u,nullptr}, // EmbeddedRenderData64cfa0
    {0x5B30D0u,0x930u,nullptr}, // EmbeddedRenderRdata5b30d0
    {0x73DBE4u,0x18u,nullptr}, // EmbeddedRenderData73dbe4
    {0x6837C0u,0x1C0u,nullptr}, // EmbeddedRenderData6837c0
    {0x5C4050u,0x5A8u,nullptr}, // EmbeddedRenderRdata5c4050
    {0x683A30u,0x18u,nullptr}, // EmbeddedRenderData683a30
    {0x5C4684u,0xB4u,nullptr}, // EmbeddedRenderRdata5c4684
};
const std::size_t EmbeddedRenderRangeCount=14;
void bind_embedded_render_ranges(){
    for(auto& r:EmbeddedRenderRanges)r.bytes=exe_image_bytes(r.va,r.size);
}
OR2_EXE_BIND(bind_embedded_render_ranges);
} // namespace outrun::platform
