// Generated by tools/extract_exe_ranges.py: PC ranges of OR2006C2C.EXE mapped by the ported code.
// No data of the original: each range points into the player's EXE image once it is loaded.
#include "platform/pc_address_view.hpp"
#include "system/exe_image.hpp"
namespace outrun::platform {
PcExeRange EmbeddedExeRanges[]={
    {0x005c5200u,nullptr,0x1200u}, // name entry 4B2370..4B4F20 tables: row positions 5C5210, tokens 5C5458 / 5C5548 / 5C5C20 / 5C5C98 / 5C5D18 / 5C6284 / 5C62AC, layouts 5C5EF8 / 5C6028, charset 5C62E0, digits 5C6344, strings 5C633C..5C63B0, 5C6374
    {0x005a4600u,nullptr,0x2b00u}, // arcade ending tables: 5A4618 motion sets, 5A4624 / 5A464C / 5A4674 ending ids, 5A46A0, 5A4740 background rows, 5A4824 + id * 0x4C rows (5A4830 scene, 5A4838 resources, 5A4874 4F2020, 5A4878 car), light blocks 5A5378.. and their list 5A6AB8
    {0x00638df0u,nullptr,0x180u}, // arcade ending .data: 638DF0 sound ids per ending, 638E98 ending id, 638E9C column, 638EA0 handle (writable copy in PcRaceEndState)
    {0x005a7780u,nullptr,0xb0u}, // arcade ending stage model names (452340: 5A46A4 rows -> END_*_STAGE / END_5x_S...)
    {0x005c1b70u,nullptr,0x80u}, // name entry bad-word strings (68694C list, stored +1 per character)
    {0x0068694cu,nullptr,0x30u}, // name entry bad-word list 68694C (.data pointers, 0-terminated)
    {0x005c6900u,nullptr,0x190u}, // name entry rank digit offset 5C6900 / 5C6904; AUTOSCENE HAKO_HUTA 5C6908, _USA 5C6914, car part / eye / KEM names 5C691C..5C6A8C
    {0x00717d68u,nullptr,0x2e8u}, // AUTOSCENE script rows 717D68 + scene * 12 (scenes 0..0x3D)
    {0x005e6b00u,nullptr,0x450u}, // 5E6B60 ("adding player %s to start packet", 516xxx), AUTOSCENE script paths (AS folder as_*_bin.sz)
    {0x005c09c0u,nullptr,0x4u}, // AUTOSCENE fov factor 5C09C0
    {0x00687000u,nullptr,0xd0u}, // AUTOSCENE sound ids 687030 (scene events 2 / 4) and motion car letters 6870CC
    {0x00626460u,nullptr,0x10u}, // name entry "%s" 626468 and " " 62646C
    {0x005b3a30u,nullptr,0x290u}, // 47CF40 rival name/param tables, class byte lists 5B3B70, 5B3C34/5B3C74 pairs
    {0x005b4460u,nullptr,0x20u}, // 47CF40 "%s %d" and float constants
    {0x005e57d8u,nullptr,0x58u}, // rival names (505390 memcpy of 32 bytes)
    {0x00624c40u,nullptr,0x20u}, // rival name (505390 memcpy of 32 bytes)
    {0x0064de00u,nullptr,0x400u}, // rival configs 64DFF0/64E040, 64DEFC, 64DF68/64DF94/64DFA0, class table 64E090
    {0x006af250u,nullptr,0xb0u}, // 505390 name pointers, 505340 table 6AF268
    {0x005c21e0u,nullptr,0x70u}, // Heart Attack result sheet request result tokens 5C21E8
    {0x005c68e0u,nullptr,0x20u}, // 4F2DF0 drift score factor 5C68E0
    {0x005c2250u,nullptr,0x130u}, // 49B870 model family 5C2350 and resource table 5C2258
    {0x005cee80u,nullptr,0xb1c0u}, // ORC78TBL primary (6A54E0) and secondary (6A55E8) course descriptors, 44DBB0 table 5D4FD8, descriptor file paths
    {0x00654500u,nullptr,0x700u}, // robots .data: 488090 records 654868, 487EE0 table 6549B0; the passenger (489A90): 45BF30 motion triples 6545C8 / 654628, bone values 654754 / 654758, 487F50 charas 6549C8, voice records 6549E0 / 654A30 / 654B10
    {0x00633558u,nullptr,0x890u}, // 448AD0 model resource path table (0x223 entries, ends at the 633DE4 cursor)
    {0x0059dd00u,nullptr,0x4b00u}, // model resource path strings
    {0x005da040u,nullptr,0x9000u}, // crash poses/keys, crash tables 5E08E8/5E0988, wall material/crush/friction tables 5E0DE0..5E3030
    {0x005e3040u,nullptr,0x1fc0u}, // vehicle display records (car +2B4 -> 5E3170..) read by PART_EFC 41BC60 (41F5F0 backfire: record +1644)
    {0x006ab600u,nullptr,0xe00u}, // crash poses 16..19 and their keys
    {0x005c2570u,nullptr,0xa10u}, // crash reroute ranges 5C2570 (stage*64)
    {0x005a42f4u,nullptr,0x1cu}, // 44CF00 stage-8 branch collision path immediate LRBK_PALM (course-prog)
    {0x005a4310u,nullptr,0x258u}, // course object animation paths BK/ANIMS/oso_dyn_bo_*_bin.sz named by the 636xxx object kind records
    {0x005e61a0u,nullptr,0x150u}, // camera motion table 5E61D0 (513730/513740: record, duration) and its one-key channels 5E61A0/5E61B0
    {0x006bb3c8u,nullptr,0x573c0u}, // camera motions of 5E61D0 (20 channels {count, keys} per scene) and their keys (486EF0)
    {0x00599400u,nullptr,0x100u}, // traffic .rdata constants (599428/599438/59943C FLT_MAX)
    {0x005a2900u,nullptr,0x100u}, // traffic .rdata constants (5A29DC/5A29E4/5A29EC)
    {0x005a4600u,nullptr,0x100u}, // traffic .rdata constants (5A4608/5A460C)
    {0x005b0000u,nullptr,0x400u}, // traffic .rdata constants (5B005C/5B0068, 5B018C Heart Attack distance class, 5B0158.. request score tables)
    {0x0063ee68u,nullptr,0xef98u}, // Heart Attack car tables 63EE68 / 644C28 (45D710), 64A9E8 / 64AA00 sign tokens, 64AAA8 crate pieces, 64AAD8 escorts (.data, no writer)
    {0x0064e200u,nullptr,0x2300u}, // Heart Attack car table 644C28 continued (.data, no writer)
    {0x006510f8u,nullptr,0x330u}, // Heart Attack car table 644C28 end (.data, no writer)
    {0x005b0cb8u,nullptr,0x2328u}, // car model layouts 5B0CB8 (0x128 bytes each: shadow / part model ids) and their table 5B2F68[model] (46A560 car-select draw)
    {0x005b2fe0u,nullptr,0xa20u}, // colour list entries {key, alternative bank ids} reached through car / object colour lists (race_colour_alt; 5B3118 in Heart Attack)
    {0x005b3a00u,nullptr,0x30u}, // traffic .rdata constants before the rival tables
    {0x005b3cc0u,nullptr,0x7a0u}, // traffic .rdata tables and constants (5B3DE4 class lengths, 5B3DF0, 5B3E08 speed records, 5B436C..5B445C)
    {0x005b4480u,nullptr,0x180u}, // traffic .rdata constants after 5B4480
    {0x005c4000u,nullptr,0x100u}, // traffic .rdata table 5C4000
    {0x005c6fc0u,nullptr,0x20u}, // 4F02D0 view bound 5C6FC8
    {0x005da2c0u,nullptr,0x20u}, // 4F02D0 view bound 5DA2D4
    {0x007162c0u,nullptr,0x10u}, // 504E70 frame time 7162C4 (.data, no writer)
    {0x006ac880u,nullptr,0x140u}, // 4F9450 collision tables 6AC898..6AC9B4 (.data, no writer)
    {0x005e0980u,nullptr,0x300u}, // 4F9450 class bytes 5E0990, SE table 5E0A78, 5E0AB8/5E0AC0, 45FB80 heart anchors 5E0AC8, 45D470 models 5E0C34 / 5E0C50
    {0x005a9000u,nullptr,0x6e00u}, // 5A9094 (network host session table), 4F6FE0 constant 5A923C, 45FB80 5A91B8, Heart Attack HUD token tables 5A93F0 / 5A9468 / 5A9484 / 5A94D0, quest request tables 5A94D8 / 5AC818, 5AFB58 cones, 5AFC4C..5AFD38, 5AFD2C
    {0x00650cf8u,nullptr,0x400u}, // traffic model records 30..44 of 650500 (4866C0), after the 30 player models
    {0x00596400u,nullptr,0x400u}, // DirectInput data: c_dfDIJoystick 59650C, c_dfDIKeyboard 596714, GUID_SysKeyboard 59672C, IID_IDirectInput8A 5967CC
    {0x0061e600u,nullptr,0x100u}, // keyboard input device: name 61E678, default key map 61E6B8
    {0x00624ac0u,nullptr,0x130u}, // input device vtables 624AD8 (base) / 624B30 (joystick 402640) / 624B88 (keyboard 403660)
    {0x00738b40u,nullptr,0x50u}, // joystick default button map 738B48 (.data, copied by 402640)
    {0x005cc000u,nullptr,0xc00u}, // controls configuration (4D7E00..4D7FB0, 4D6A60): key name table 5CC200..5CC8C4, slider table id 5CC048, constants 5CCBD8..5CCBF8, title owner vtable 5CCBB4
    {0x005ccc00u,nullptr,0x2280u}, // frontend screen vtables 5CCC00.. (network screens 5CD834 key 14, 5CD84C key 15, 5CDA88 key 22...) and their constants
    {0x005c9600u,nullptr,0x2a00u}, // frontend screen vtables 5C9600.. (network screens 5C97FC key 11, 5C9920 key 12, 5C9A28 key 13...)
    {0x0059da00u,nullptr,0x100u}, // frontend screen vtables 59DABC (key 17) / 59DAD4 (key 19)
    {0x005c1b00u,nullptr,0x200u}, // network screen vtables 5C1C2C (key 46) / 5C1C48 (key 26) and the session state vtables 5C1BE8 / 5C1C18
    {0x00692b00u,nullptr,0x1c0u}, // title options layout .data 692B28..692CA0 (rows 692C50, count 692C94, timer 692C98: writable copy in the input device layer)
    {0x006255d0u,nullptr,0x10u}, // empty string 6255D5 (4D7E00 window title)
    {0x005c1700u,nullptr,0x200u}, // 5C17E4 (network notice screen 15), title window vtables 5C1838 / 5C1888 / 5C18A0 / 5C18C8 and the 48CAE0 constant 5C1858
    {0x00596000u,nullptr,0x94000u}, // whole .rdata 596000..629FFF for the network module (its screens and widgets read constants, strings and vtables everywhere)
    {0x0059db00u,nullptr,0x1a0u}, // 445DA0 UTF-16 character tables 59DB08 / 59DC08
    {0x005e9520u,nullptr,0x16ae0u}, // network module .rdata: Demonware vtables, constants and strings (5E9520..5FFFFF)
    {0x00600000u,nullptr,0x2a000u}, // network module .rdata: Demonware / LAN constants, vtables and strings (600000..629FFF)
    {0x0062a000u,nullptr,0x156100u}, // initialized .data image 62A000..7800FF: the network module starts from a private copy of the whole data region (its screens, sessions and widgets)
    {0x00659900u,nullptr,0x200u}, // network module .data 659900..659AFF
    {0x0065b500u,nullptr,0x40u}, // LAN sockets 65B51C / 65B520 / 65B524 (.data -1)
    {0x0065d000u,nullptr,0x10u}, // network .data 65D008
    {0x0065e000u,nullptr,0x10u}, // network .data 65E00C
    {0x006aa330u,nullptr,0x10u}, // network .data 6AA334
    {0x00724600u,nullptr,0x400u}, // network .data 7246A4..724934
    {0x00733f00u,nullptr,0x1900u}, // network / CRT .data 733F40..735760
    {0x007f1930u,nullptr,0x10u}, // network .data 7F1938
    {0x00830b00u,nullptr,0x300u}, // network .data 830BEC..830D48
    {0x00836000u,nullptr,0x300u}, // network service object 83612C and 8360D4..
    {0x00850b00u,nullptr,0x40u}, // network .data 850B04..850B34
    {0x0085af00u,nullptr,0x500u}, // LAN interface table 85AFB8 and 85B2B0
    {0x0085de00u,nullptr,0x200u}, // network .data 85DE90..85DF54
    {0x0085eb00u,nullptr,0x100u}, // network .data 85EB78..85EBE4
    {0x0085f000u,nullptr,0x100u}, // network .data 85F0D0..85F0FC
    {0x0085fa40u,nullptr,0x20u}, // network .data 85FA50
    {0x00988d00u,nullptr,0x1f00u}, // network lobby 988F40, 98A628..98A6FC, 98AB04..98AB1C
    {0x00751b00u,nullptr,0x100u}, // course shadow pass .data: 422820 light records 751B2C / 751B58 (copied, 751B94 / 751B98 written in the writable copy of race_course_passes)
    {0x005ba918u,nullptr,0xe8u}, // camera .rdata after the 5BA4E0 table: presets 5BA918 / 5BA930, constants 5BA950..5BA96C, mode 10 eye 5BA980 / angles 5BA970 / fov 5BA97C
    {0x005baa00u,nullptr,0x1f10u}, // traffic model chains / model data of models 30..43 (before 5BC910)
    {0x005e8a88u,nullptr,0xa98u}, // 520950 collision descriptors 5E8A88 + model*0x3C (models 0..44)
    {0x006839f8u,nullptr,0x38u}, // 683980 colour list pointers of the traffic models 30..43 (.data, read only)
    {0x005da300u,nullptr,0x60u}, // 4F3EA0 default ranking records: 5DA318 leads, 5DA328/2C/30 names, 5DA334 nibbles
    {0x00619a00u,nullptr,0x100u}, // .rdata constants (619A34 = 0.0)
    {0x00628000u,nullptr,0x400u}, // .rdata float constants 628000..6283FF
    {0x005c1c60u,nullptr,0xf0u}, // course object .rdata constants 5C1C68 / 5C1D40
    {0x005c3700u,nullptr,0x900u}, // course object shapes 5C37B8 / 5C3A30 / 5C3CA8, body tables 5C3F1C..5C3F94, constants 5C3FB0..5C3FF0
    {0x00681200u,nullptr,0xc00u}, // course object .data: ball shapes 6812D0 / 681548 (4A8EA0 rewrites 681548), kind table 6817C0, spark tables 681CAC / 681CE8, 681D24
    {0x006a54e0u,nullptr,0x220u}, // course descriptor pointer tables 6A54E0 (primary) / 6A55E8 (secondary) (44C990: [6A54E0+i*4]+7E)
    {0x006a5df8u,nullptr,0xff0u}, // course appear source tables (4EF890 copies to 84BD00) and stage pointers 6A6CE0
    {0x0059dae0u,nullptr,0x40u}, // arcade .rdata string 59DAEC (sel_dl_edit0.tgt)
    {0x0059dc80u,nullptr,0x40u}, // 446510 slot caption positions 59DC84 / 59DC88 / 59DCA4
    {0x005c2120u,nullptr,0xc0u}, // arcade .rdata constants 5C2134 / 5C2138
    {0x005c6f00u,nullptr,0xc0u}, // arcade constants 5C6FB8 / 5C6FBC (player marks)
    {0x005c6fe0u,nullptr,0x2620u}, // arcade sprite table 5C7170 {token, first, last}, sequences 5C8BE0.., tables 5C91DC.., constants 5C9404..
    {0x00625630u,nullptr,0x10u}, // arcade .rdata constant 62563C
    {0x0065a7a0u,nullptr,0x20u}, // arcade settings 65A7A4..65A7B3 (.data initial values; written copies live in PcRaceEndState)
    {0x006898c0u,nullptr,0x740u}, // arcade .data tables 6898C9..689FC8 (initial values; written copies live in PcRaceEndState)
    {0x00687e20u,nullptr,0x38u}, // 4B88D0 / 4B8C00 player lamp x by player count 687E24 (.data, no writer)
};
const std::size_t EmbeddedExeRangeCount=109;
void bind_embedded_exe_ranges(){
    for(auto& r:EmbeddedExeRanges)r.data=exe_image_bytes(r.base,static_cast<std::uint32_t>(r.size));
}
OR2_EXE_BIND(bind_embedded_exe_ranges);
}
