// Generated by tools/generate_camera_tables.py: addresses only, data from the player's EXE.
#include "platform/embedded_camera_data.hpp"
#include "system/exe_image.hpp"
namespace outrun::platform {
const std::uint8_t* EmbeddedCameraTable5b4a30=nullptr;
const std::uint8_t* EmbeddedCameraTable5ba4e0=nullptr;
const std::uint8_t* EmbeddedCameraTable5b5080=nullptr;
void bind_embedded_camera_tables(){
    EmbeddedCameraTable5b4a30=exe_image_bytes(0x5B4A30u,0x64Cu);
    EmbeddedCameraTable5ba4e0=exe_image_bytes(0x5BA4E0u,0x438u);
    EmbeddedCameraTable5b5080=exe_image_bytes(0x5B5080u,0x5460u);
}
OR2_EXE_BIND(bind_embedded_camera_tables);
} // namespace outrun::platform
