// Generated by tools/generate_pc_shaders.py from the hash-pinned EXE. Do not edit.
#include "system/exe_image.hpp"
#include <cstring>
#include "platform/pc_shader_programs.hpp"
namespace outrun::platform {
namespace {
using namespace pc_shader;
void vs_0(VsState& s){ // 61F64C
    V4 t0=s.V[0];
    wmask(s.R[11],t0,15);
    V4 t1=s.V[3];
    wmask(s.R[10],t1,15);
    V4 t2=v4(dp4(s.R[11],s.C[64]).x,dp4(s.R[11],s.C[65]).x,dp4(s.R[11],s.C[66]).x,dp4(s.R[11],s.C[67]).x);
    wmask(s.oPos,t2,15);
}
void vs_1(VsState& s){ // 61F67C
    (void)s;
}
void vs_2(VsState& s){ // 61F6A0
    V4 t0=mul(s.V[0],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.V[13],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.R[11],t1,15);
    V4 t2=mul(s.V[3],swz(s.C[7],0,0,0,0));
    wmask(s.R[1],t2,15);
    V4 t3=mad(s.V[14],swz(s.C[7],1,1,1,1),s.R[1]);
    wmask(s.R[10],t3,15);
    V4 t4=v4(dp4(s.R[11],s.C[64]).x,dp4(s.R[11],s.C[65]).x,dp4(s.R[11],s.C[66]).x,dp4(s.R[11],s.C[67]).x);
    wmask(s.oPos,t4,15);
}
void vs_3(VsState& s){ // 61F700
    (void)s;
}
void vs_4(VsState& s){ // 61F738
    V4 t0=swz(s.V[1],0,0,0,0);
    wmask(s.R[4],t0,1);
    V4 t1=add(swz(s.C[0],3,3,3,3),neg(swz(s.V[1],0,0,0,0)));
    wmask(s.R[5],t1,1);
    V4 t2=v4(dp4(s.V[0],s.C[84]).x,dp4(s.V[0],s.C[85]).x,dp4(s.V[0],s.C[86]).x,dp4(s.V[0],s.C[87]).x);
    wmask(s.R[1],t2,15);
    V4 t3=mul(swz(s.R[4],0,0,0,0),s.V[0]);
    wmask(s.R[0],t3,15);
    V4 t4=mad(swz(s.R[5],0,0,0,0),s.R[1],s.R[0]);
    wmask(s.R[11],t4,15);
    V4 t5=v4(dp3(s.V[3],s.C[84]).x,dp3(s.V[3],s.C[85]).x,dp3(s.V[3],s.C[86]).x,0.f);
    wmask(s.R[1],t5,7);
    V4 t6=mul(swz(s.R[4],0,0,0,0),s.V[3]);
    wmask(s.R[0],t6,15);
    V4 t7=mad(swz(s.R[5],0,0,0,0),s.R[1],s.R[0]);
    wmask(s.R[10],t7,15);
    V4 t8=v4(dp4(s.R[11],s.C[64]).x,dp4(s.R[11],s.C[65]).x,dp4(s.R[11],s.C[66]).x,dp4(s.R[11],s.C[67]).x);
    wmask(s.oPos,t8,15);
}
void vs_5(VsState& s){ // 61F7D4
    (void)s;
}
void vs_6(VsState& s){ // 61F800
    V4 t0=swz(s.V[1],0,0,0,0);
    wmask(s.R[4],t0,1);
    V4 t1=add(swz(s.V[1],0,0,0,0),swz(s.V[1],1,1,1,1));
    wmask(s.R[0],t1,1);
    V4 t2=add(swz(s.C[0],3,3,3,3),neg(swz(s.R[0],0,0,0,0)));
    wmask(s.R[5],t2,1);
    V4 t3=v4(dp4(s.V[0],s.C[84]).x,dp4(s.V[0],s.C[85]).x,dp4(s.V[0],s.C[86]).x,dp4(s.V[0],s.C[87]).x);
    wmask(s.R[1],t3,15);
    V4 t4=v4(dp4(s.V[0],s.C[88]).x,dp4(s.V[0],s.C[89]).x,dp4(s.V[0],s.C[90]).x,dp4(s.V[0],s.C[91]).x);
    wmask(s.R[2],t4,15);
    V4 t5=mul(swz(s.R[4],0,0,0,0),s.V[0]);
    wmask(s.R[0],t5,15);
    V4 t6=mad(swz(s.V[1],1,1,1,1),s.R[1],s.R[0]);
    wmask(s.R[0],t6,15);
    V4 t7=mad(swz(s.R[5],0,0,0,0),s.R[2],s.R[0]);
    wmask(s.R[11],t7,15);
    V4 t8=v4(dp3(s.V[3],s.C[84]).x,dp3(s.V[3],s.C[85]).x,dp3(s.V[3],s.C[86]).x,0.f);
    wmask(s.R[1],t8,7);
    V4 t9=v4(dp3(s.V[3],s.C[88]).x,dp3(s.V[3],s.C[89]).x,dp3(s.V[3],s.C[90]).x,0.f);
    wmask(s.R[2],t9,7);
    V4 t10=mul(swz(s.R[4],0,0,0,0),s.V[3]);
    wmask(s.R[0],t10,15);
    V4 t11=mad(swz(s.V[1],1,1,1,1),s.R[1],s.R[0]);
    wmask(s.R[0],t11,15);
    V4 t12=mad(swz(s.R[5],0,0,0,0),s.R[2],s.R[0]);
    wmask(s.R[10],t12,15);
    V4 t13=v4(dp4(s.R[11],s.C[64]).x,dp4(s.R[11],s.C[65]).x,dp4(s.R[11],s.C[66]).x,dp4(s.R[11],s.C[67]).x);
    wmask(s.oPos,t13,15);
}
void vs_7(VsState& s){ // 61F8F4
    (void)s;
}
void vs_8(VsState& s){ // 61F920
    V4 t0=swz(s.V[1],0,0,0,0);
    wmask(s.R[4],t0,1);
    V4 t1=add(neg(swz(s.V[1],0,0,0,0)),neg(swz(s.V[1],1,1,1,1)));
    wmask(s.R[0],t1,1);
    V4 t2=add(neg(swz(s.V[1],2,2,2,2)),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t2,2);
    V4 t3=add(swz(s.R[0],0,0,0,0),swz(s.R[0],1,1,1,1));
    wmask(s.R[5],t3,1);
    V4 t4=v4(dp4(s.V[0],s.C[84]).x,dp4(s.V[0],s.C[85]).x,dp4(s.V[0],s.C[86]).x,dp4(s.V[0],s.C[87]).x);
    wmask(s.R[1],t4,15);
    V4 t5=v4(dp4(s.V[0],s.C[88]).x,dp4(s.V[0],s.C[89]).x,dp4(s.V[0],s.C[90]).x,dp4(s.V[0],s.C[91]).x);
    wmask(s.R[2],t5,15);
    V4 t6=v4(dp4(s.V[0],s.C[92]).x,dp4(s.V[0],s.C[93]).x,dp4(s.V[0],s.C[94]).x,dp4(s.V[0],s.C[95]).x);
    wmask(s.R[3],t6,15);
    V4 t7=mul(swz(s.R[4],0,0,0,0),s.V[0]);
    wmask(s.R[0],t7,15);
    V4 t8=mad(swz(s.V[1],1,1,1,1),s.R[1],s.R[0]);
    wmask(s.R[0],t8,15);
    V4 t9=mad(swz(s.V[1],2,2,2,2),s.R[2],s.R[0]);
    wmask(s.R[0],t9,15);
    V4 t10=mad(swz(s.R[5],0,0,0,0),s.R[3],s.R[0]);
    wmask(s.R[11],t10,15);
    V4 t11=v4(dp3(s.V[3],s.C[84]).x,dp3(s.V[3],s.C[85]).x,dp3(s.V[3],s.C[86]).x,0.f);
    wmask(s.R[1],t11,7);
    V4 t12=v4(dp3(s.V[3],s.C[88]).x,dp3(s.V[3],s.C[89]).x,dp3(s.V[3],s.C[90]).x,0.f);
    wmask(s.R[2],t12,7);
    V4 t13=v4(dp3(s.V[3],s.C[92]).x,dp3(s.V[3],s.C[93]).x,dp3(s.V[3],s.C[94]).x,0.f);
    wmask(s.R[3],t13,7);
    V4 t14=mul(swz(s.R[4],0,0,0,0),s.V[3]);
    wmask(s.R[0],t14,15);
    V4 t15=mad(swz(s.V[1],1,1,1,1),s.R[1],s.R[0]);
    wmask(s.R[0],t15,15);
    V4 t16=mad(swz(s.V[1],2,2,2,2),s.R[2],s.R[0]);
    wmask(s.R[0],t16,15);
    V4 t17=mad(swz(s.R[5],0,0,0,0),s.R[3],s.R[0]);
    wmask(s.R[10],t17,15);
    V4 t18=v4(dp4(s.R[11],s.C[64]).x,dp4(s.R[11],s.C[65]).x,dp4(s.R[11],s.C[66]).x,dp4(s.R[11],s.C[67]).x);
    wmask(s.oPos,t18,15);
}
void vs_9(VsState& s){ // 61FA6C
    (void)s;
}
void vs_10(VsState& s){ // 61FA98
    V4 t0=s.C[18];
    wmask(s.R[9],t0,15);
    V4 t1=s.C[19];
    wmask(s.R[8],t1,15);
}
void vs_11(VsState& s){ // 61FAB8
    V4 t0=s.V[5];
    wmask(s.R[9],t0,15);
    V4 t1=s.V[5];
    wmask(s.R[8],t1,15);
}
void vs_12(VsState& s){ // 61FAD8
    (void)s;
}
void vs_13(VsState& s){ // 61FAEC
    V4 t0=mul(s.V[5],swz(s.C[7],0,0,0,0));
    wmask(s.R[1],t0,15);
    V4 t1=mad(s.V[15],swz(s.C[7],1,1,1,1),s.R[1]);
    wmask(s.R[9],t1,15);
    V4 t2=s.R[9];
    wmask(s.R[8],t2,15);
}
void vs_14(VsState& s){ // 61FB24
    (void)s;
}
void vs_15(VsState& s){ // 61FB48
    V4 t0=dp3(neg(s.R[10]),s.C[37]);
    wmask(s.R[5],t0,1);
    V4 t1=mul(s.R[9],s.C[21]);
    wmask(s.R[2],t1,15);
    V4 t2=max(swz(s.R[5],0,0,0,0),s.C[0]);
    wmask(s.R[0],t2,15);
    V4 t3=mul(swz(s.R[5],0,0,0,0),s.C[26]);
    wmask(s.R[1],t3,15);
    V4 t4=add(s.R[1],s.C[27]);
    wmask(s.R[1],t4,15);
    V4 t5=mad(s.R[1],s.R[8],s.C[20]);
    wmask(s.R[1],t5,15);
    V4 t6=mul(s.R[1],s.C[16]);
    wmask(s.R[1],t6,15);
    V4 t7=mad(s.R[0],s.R[2],s.R[1]);
    wmask(s.oD[0],t7,15);
    V4 t8=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t8,15);
}
void vs_16(VsState& s){ // 61FBE8
    V4 t0=dp3(s.R[10],s.C[37]);
    wmask(s.R[5],t0,1);
    V4 t1=mul(s.R[9],s.C[21]);
    wmask(s.R[2],t1,15);
    V4 t2=mul(swz(s.R[5],0,0,0,0),s.C[26]);
    wmask(s.R[6],t2,15);
    V4 t3=add(s.R[6],s.C[27]);
    wmask(s.R[1],t3,15);
    V4 t4=max(swz(s.R[5],0,0,0,0),s.C[0]);
    wmask(s.R[0],t4,15);
    V4 t5=mad(s.R[1],s.R[8],s.C[20]);
    wmask(s.R[1],t5,15);
    V4 t6=mul(s.R[1],s.C[16]);
    wmask(s.R[1],t6,15);
    V4 t7=mad(s.R[0],s.R[2],s.R[1]);
    wmask(s.oD[0],t7,15);
    V4 t8=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t8,15);
}
void vs_17(VsState& s){ // 61FC88
    V4 t0=add(s.R[11],neg(s.C[17]));
    wmask(s.R[0],t0,15);
    V4 t1=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t1,8);
    V4 t2=swz(s.C[32],3,3,3,3);
    wmask(s.R[5],t2,8);
    V4 t3=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t3,8);
    V4 t4=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[2],t4,15);
    V4 t5=add(s.R[2],s.C[37]);
    wmask(s.R[0],t5,15);
    V4 t6=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t6,8);
    V4 t7=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t7,8);
    V4 t8=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[3],t8,15);
    V4 t9=dp3(s.R[10],s.R[3]);
    wmask(s.R[5],t9,2);
    V4 t10=dp3(neg(s.R[10]),s.C[37]);
    wmask(s.R[5],t10,1);
    V4 t11=max(swz(s.R[5],0,0,0,0),s.C[0]);
    wmask(s.R[0],t11,15);
    V4 t12=mul(swz(s.R[5],0,0,0,0),s.C[26]);
    wmask(s.R[1],t12,15);
    V4 t13=add(s.R[1],s.C[27]);
    wmask(s.R[1],t13,15);
    V4 t14=mad(s.R[1],s.R[8],s.C[20]);
    wmask(s.R[1],t14,15);
    V4 t15=mul(s.R[1],s.C[16]);
    wmask(s.R[1],t15,15);
    V4 t16=mul(s.R[9],s.C[21]);
    wmask(s.R[2],t16,15);
    V4 t17=mad(s.R[0],s.R[2],s.R[1]);
    wmask(s.oD[0],t17,15);
    V4 t18=d3d_lit(s.R[5]);
    wmask(s.R[0],t18,15);
    V4 t19=mul(swz(s.R[0],2,2,2,2),s.C[32]);
    wmask(s.oD[1],t19,7);
}
void vs_18(VsState& s){ // 61FDC8
    V4 t0=add(s.R[11],neg(s.C[17]));
    wmask(s.R[0],t0,15);
    V4 t1=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t1,8);
    V4 t2=swz(s.C[32],3,3,3,3);
    wmask(s.R[5],t2,8);
    V4 t3=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t3,8);
    V4 t4=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[2],t4,15);
    V4 t5=add(s.R[2],s.C[37]);
    wmask(s.R[0],t5,15);
    V4 t6=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t6,8);
    V4 t7=swz(s.C[32],3,3,3,3);
    wmask(s.R[4],t7,8);
    V4 t8=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t8,8);
    V4 t9=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[3],t9,15);
    V4 t10=dp3(s.R[10],s.R[3]);
    wmask(s.R[5],t10,2);
    V4 t11=dp3(s.R[10],s.C[37]);
    wmask(s.R[5],t11,1);
    V4 t12=mul(swz(s.R[5],0,0,0,0),s.C[26]);
    wmask(s.R[6],t12,15);
    V4 t13=add(s.R[6],s.C[27]);
    wmask(s.R[1],t13,15);
    V4 t14=max(swz(s.R[5],0,0,0,0),s.C[0]);
    wmask(s.R[0],t14,15);
    V4 t15=mad(s.R[1],s.R[8],s.C[20]);
    wmask(s.R[1],t15,15);
    V4 t16=neg(swz(s.R[5],0,0,0,0));
    wmask(s.R[4],t16,1);
    V4 t17=mul(s.R[1],s.C[16]);
    wmask(s.R[1],t17,15);
    V4 t18=mul(s.R[9],s.C[21]);
    wmask(s.R[2],t18,15);
    V4 t19=mad(s.R[0],s.R[2],s.R[1]);
    wmask(s.oD[0],t19,15);
    V4 t20=d3d_lit(s.R[5]);
    wmask(s.R[0],t20,15);
    V4 t21=mul(swz(s.R[0],2,2,2,2),s.C[32]);
    wmask(s.oD[1],t21,7);
}
void vs_19(VsState& s){ // 61FF20
    V4 t0=add(s.R[11],neg(s.C[40]));
    wmask(s.R[0],t0,15);
    V4 t1=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t1,1);
    V4 t2=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[2],t2,1);
    V4 t3=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[3],t3,15);
    V4 t4=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t4,15);
    V4 t5=dp3(s.R[0],s.C[44]);
    wmask(s.R[2],t5,1);
    V4 t6=d3d_rcp(swz(s.R[2],0,0,0,0).w);
    wmask(s.R[2],t6,1);
    V4 t7=slt(swz(s.R[0],1,1,1,1),swz(s.C[44],3,3,3,3));
    wmask(s.R[1],t7,1);
    V4 t8=mul(swz(s.R[2],0,0,0,0),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t8,1);
    V4 t9=dp3(s.R[3],s.C[38]);
    wmask(s.R[1],t9,1);
    V4 t10=mad(swz(s.R[1],0,0,0,0),swz(s.C[48],0,0,0,0),swz(s.C[48],1,1,1,1));
    wmask(s.R[0],t10,1);
    V4 t11=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t11,1);
    V4 t12=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t12,1);
    V4 t13=mul(swz(s.R[2],0,0,0,0),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t13,1);
    V4 t14=dp3(neg(s.R[10]),s.R[3]);
    wmask(s.R[4],t14,1);
    V4 t15=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t15,15);
    V4 t16=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t16,15);
    V4 t17=mul(s.R[0],s.C[22]);
    wmask(s.R[5],t17,15);
    V4 t18=mul(swz(s.R[2],0,0,0,0),s.C[28]);
    wmask(s.R[6],t18,15);
    V4 t19=add(s.R[11],neg(s.C[41]));
    wmask(s.R[0],t19,15);
    V4 t20=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t20,1);
    V4 t21=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[2],t21,1);
    V4 t22=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[3],t22,15);
    V4 t23=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t23,15);
    V4 t24=dp3(s.R[0],s.C[45]);
    wmask(s.R[2],t24,1);
    V4 t25=d3d_rcp(swz(s.R[2],0,0,0,0).w);
    wmask(s.R[2],t25,1);
    V4 t26=slt(swz(s.R[0],1,1,1,1),swz(s.C[45],3,3,3,3));
    wmask(s.R[1],t26,1);
    V4 t27=mul(swz(s.R[2],0,0,0,0),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t27,1);
    V4 t28=dp3(s.R[3],s.C[39]);
    wmask(s.R[1],t28,1);
    V4 t29=mad(swz(s.R[1],0,0,0,0),swz(s.C[49],0,0,0,0),swz(s.C[49],1,1,1,1));
    wmask(s.R[0],t29,1);
    V4 t30=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t30,1);
    V4 t31=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t31,1);
    V4 t32=mul(swz(s.R[2],0,0,0,0),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t32,1);
    V4 t33=dp3(neg(s.R[10]),s.R[3]);
    wmask(s.R[4],t33,1);
    V4 t34=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t34,15);
    V4 t35=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t35,15);
    V4 t36=mad(s.R[0],s.C[23],s.R[5]);
    wmask(s.R[5],t36,15);
    V4 t37=mad(swz(s.R[2],0,0,0,0),s.C[29],s.R[6]);
    wmask(s.R[6],t37,15);
    V4 t38=dp3(neg(s.R[10]),s.C[37]);
    wmask(s.R[4],t38,1);
    V4 t39=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t39,15);
    V4 t40=mad(s.R[0],s.C[21],s.R[5]);
    wmask(s.R[5],t40,15);
    V4 t41=mul(swz(s.R[4],0,0,0,0),s.C[26]);
    wmask(s.R[1],t41,15);
    V4 t42=add(s.R[1],s.C[27]);
    wmask(s.R[1],t42,15);
    V4 t43=add(s.R[1],s.R[6]);
    wmask(s.R[6],t43,15);
    V4 t44=mad(s.R[6],s.R[8],s.C[20]);
    wmask(s.R[6],t44,15);
    V4 t45=mul(s.R[6],s.C[16]);
    wmask(s.R[6],t45,15);
    V4 t46=mad(s.R[5],s.R[9],s.R[6]);
    wmask(s.oD[0],t46,15);
    V4 t47=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t47,15);
}
void vs_20(VsState& s){ // 620230
    V4 t0=swz(s.C[32],3,3,3,3);
    wmask(s.R[3],t0,8);
    V4 t1=swz(s.C[0],3,3,3,3);
    wmask(s.R[6],t1,8);
    V4 t2=add(s.R[11],neg(s.C[17]));
    wmask(s.R[0],t2,15);
    V4 t3=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t3,8);
    V4 t4=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t4,8);
    V4 t5=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[4],t5,15);
    V4 t6=add(s.R[11],neg(s.C[40]));
    wmask(s.R[0],t6,15);
    V4 t7=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t7,1);
    V4 t8=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[1],t8,2);
    V4 t9=mul(s.R[0],swz(s.R[1],1,1,1,1));
    wmask(s.R[2],t9,7);
    V4 t10=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[1],1,1,1,1));
    wmask(s.R[0],t10,15);
    V4 t11=dp3(s.R[0],s.C[44]);
    wmask(s.R[2],t11,8);
    V4 t12=d3d_rcp(swz(s.R[2],3,3,3,3).w);
    wmask(s.R[2],t12,8);
    V4 t13=slt(swz(s.R[0],1,1,1,1),swz(s.C[44],3,3,3,3));
    wmask(s.R[1],t13,1);
    V4 t14=mul(swz(s.R[2],3,3,3,3),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t14,8);
    V4 t15=dp3(swz(s.R[2],0,1,2,2),s.C[38]);
    wmask(s.R[0],t15,1);
    V4 t16=mad(swz(s.R[0],0,0,0,0),swz(s.C[48],0,0,0,0),swz(s.C[48],1,1,1,1));
    wmask(s.R[0],t16,1);
    V4 t17=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t17,1);
    V4 t18=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t18,1);
    V4 t19=mul(swz(s.R[2],3,3,3,3),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t19,8);
    V4 t20=add(swz(s.R[2],0,1,2,2),s.R[4]);
    wmask(s.R[1],t20,15);
    V4 t21=dp3(s.R[1],s.R[1]);
    wmask(s.R[0],t21,8);
    V4 t22=d3d_rsq(swz(s.R[0],3,3,3,3).w);
    wmask(s.R[0],t22,8);
    V4 t23=mul(s.R[1],swz(s.R[0],3,3,3,3));
    wmask(s.R[1],t23,15);
    V4 t24=dp3(neg(s.R[10]),s.R[1]);
    wmask(s.R[3],t24,2);
    V4 t25=dp3(neg(s.R[10]),swz(s.R[2],0,1,2,2));
    wmask(s.R[3],t25,1);
    V4 t26=d3d_lit(s.R[3]);
    wmask(s.R[0],t26,15);
    V4 t27=mul(s.R[0],swz(s.R[2],3,3,3,3));
    wmask(s.R[0],t27,15);
    V4 t28=mul(swz(s.R[2],3,3,3,3),s.C[28]);
    wmask(s.R[5],t28,15);
    V4 t29=mul(swz(s.R[0],1,1,1,1),s.C[22]);
    wmask(s.R[6],t29,7);
    V4 t30=mul(swz(s.R[0],2,2,2,2),s.C[33]);
    wmask(s.R[7],t30,15);
    V4 t31=add(s.R[11],neg(s.C[41]));
    wmask(s.R[0],t31,15);
    V4 t32=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t32,1);
    V4 t33=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[1],t33,2);
    V4 t34=mul(s.R[0],swz(s.R[1],1,1,1,1));
    wmask(s.R[2],t34,7);
    V4 t35=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[1],1,1,1,1));
    wmask(s.R[0],t35,15);
    V4 t36=dp3(s.R[0],s.C[45]);
    wmask(s.R[2],t36,8);
    V4 t37=d3d_rcp(swz(s.R[2],3,3,3,3).w);
    wmask(s.R[2],t37,8);
    V4 t38=slt(swz(s.R[0],1,1,1,1),swz(s.C[45],3,3,3,3));
    wmask(s.R[1],t38,1);
    V4 t39=mul(swz(s.R[2],3,3,3,3),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t39,8);
    V4 t40=dp3(swz(s.R[2],0,1,2,2),s.C[39]);
    wmask(s.R[0],t40,1);
    V4 t41=mad(swz(s.R[0],0,0,0,0),swz(s.C[49],0,0,0,0),swz(s.C[49],1,1,1,1));
    wmask(s.R[0],t41,1);
    V4 t42=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t42,1);
    V4 t43=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t43,1);
    V4 t44=mul(swz(s.R[2],3,3,3,3),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t44,8);
    V4 t45=dp3(s.R[10],swz(s.R[2],0,1,2,2));
    wmask(s.R[3],t45,1);
    V4 t46=max(swz(s.R[3],0,0,0,0),s.C[0]);
    wmask(s.R[0],t46,2);
    V4 t47=mul(s.R[0],swz(s.R[2],3,3,3,3));
    wmask(s.R[0],t47,15);
    V4 t48=mad(swz(s.R[2],3,3,3,3),s.C[29],s.R[5]);
    wmask(s.R[5],t48,15);
    V4 t49=mad(swz(s.R[0],1,1,1,1),s.C[23],s.R[6]);
    wmask(s.R[6],t49,7);
    V4 t50=dp3(s.R[10],s.C[37]);
    wmask(s.R[3],t50,1);
    V4 t51=max(swz(s.R[3],0,0,0,0),s.C[0]);
    wmask(s.R[0],t51,2);
    V4 t52=mad(swz(s.R[0],1,1,1,1),s.C[21],s.R[6]);
    wmask(s.R[6],t52,7);
    V4 t53=mul(swz(s.R[3],0,0,0,0),s.C[26]);
    wmask(s.R[1],t53,15);
    V4 t54=add(s.R[1],s.C[27]);
    wmask(s.R[1],t54,15);
    V4 t55=add(s.R[5],s.R[1]);
    wmask(s.R[5],t55,15);
    V4 t56=mad(s.R[5],s.R[8],s.C[20]);
    wmask(s.R[5],t56,15);
    V4 t57=mul(s.R[5],s.C[16]);
    wmask(s.R[5],t57,15);
    V4 t58=mad(s.R[6],s.R[9],s.R[5]);
    wmask(s.oD[0],t58,15);
    V4 t59=s.R[7];
    wmask(s.oD[1],t59,7);
}
void vs_21(VsState& s){ // 6205F0
    V4 t0=add(s.R[11],neg(s.C[40]));
    wmask(s.R[0],t0,15);
    V4 t1=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t1,1);
    V4 t2=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[2],t2,1);
    V4 t3=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[3],t3,15);
    V4 t4=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t4,15);
    V4 t5=dp3(s.R[0],s.C[44]);
    wmask(s.R[2],t5,1);
    V4 t6=d3d_rcp(swz(s.R[2],0,0,0,0).w);
    wmask(s.R[2],t6,1);
    V4 t7=slt(swz(s.R[0],1,1,1,1),swz(s.C[44],3,3,3,3));
    wmask(s.R[1],t7,1);
    V4 t8=mul(swz(s.R[2],0,0,0,0),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t8,1);
    V4 t9=dp3(s.R[3],s.C[38]);
    wmask(s.R[1],t9,1);
    V4 t10=mad(swz(s.R[1],0,0,0,0),swz(s.C[48],0,0,0,0),swz(s.C[48],1,1,1,1));
    wmask(s.R[0],t10,1);
    V4 t11=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t11,1);
    V4 t12=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t12,1);
    V4 t13=mul(swz(s.R[2],0,0,0,0),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t13,1);
    V4 t14=dp3(neg(s.R[10]),s.R[3]);
    wmask(s.R[4],t14,1);
    V4 t15=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t15,15);
    V4 t16=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t16,15);
    V4 t17=mul(s.R[0],s.C[22]);
    wmask(s.R[5],t17,15);
    V4 t18=mul(swz(s.R[2],0,0,0,0),s.C[28]);
    wmask(s.R[6],t18,15);
    V4 t19=add(s.R[11],neg(s.C[41]));
    wmask(s.R[0],t19,15);
    V4 t20=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t20,1);
    V4 t21=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[2],t21,1);
    V4 t22=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[3],t22,15);
    V4 t23=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t23,15);
    V4 t24=dp3(s.R[0],s.C[45]);
    wmask(s.R[2],t24,1);
    V4 t25=d3d_rcp(swz(s.R[2],0,0,0,0).w);
    wmask(s.R[2],t25,1);
    V4 t26=slt(swz(s.R[0],1,1,1,1),swz(s.C[45],3,3,3,3));
    wmask(s.R[1],t26,1);
    V4 t27=mul(swz(s.R[2],0,0,0,0),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t27,1);
    V4 t28=dp3(s.R[3],s.C[39]);
    wmask(s.R[1],t28,1);
    V4 t29=mad(swz(s.R[1],0,0,0,0),swz(s.C[49],0,0,0,0),swz(s.C[49],1,1,1,1));
    wmask(s.R[0],t29,1);
    V4 t30=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t30,1);
    V4 t31=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t31,1);
    V4 t32=mul(swz(s.R[2],0,0,0,0),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t32,1);
    V4 t33=dp3(neg(s.R[10]),s.R[3]);
    wmask(s.R[4],t33,1);
    V4 t34=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t34,15);
    V4 t35=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t35,15);
    V4 t36=mad(s.R[0],s.C[23],s.R[5]);
    wmask(s.R[5],t36,15);
    V4 t37=mad(swz(s.R[2],0,0,0,0),s.C[29],s.R[6]);
    wmask(s.R[6],t37,15);
    V4 t38=add(s.R[11],neg(s.C[42]));
    wmask(s.R[0],t38,15);
    V4 t39=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t39,1);
    V4 t40=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[2],t40,1);
    V4 t41=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[3],t41,15);
    V4 t42=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t42,15);
    V4 t43=dp3(s.R[0],s.C[46]);
    wmask(s.R[2],t43,1);
    V4 t44=d3d_rcp(swz(s.R[2],0,0,0,0).w);
    wmask(s.R[2],t44,1);
    V4 t45=slt(swz(s.R[0],1,1,1,1),swz(s.C[46],3,3,3,3));
    wmask(s.R[1],t45,1);
    V4 t46=mul(swz(s.R[2],0,0,0,0),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t46,1);
    V4 t47=dp3(neg(s.R[10]),s.R[3]);
    wmask(s.R[4],t47,1);
    V4 t48=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t48,15);
    V4 t49=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t49,15);
    V4 t50=mad(s.R[0],s.C[24],s.R[5]);
    wmask(s.R[5],t50,15);
    V4 t51=mad(swz(s.R[2],0,0,0,0),s.C[30],s.R[6]);
    wmask(s.R[6],t51,15);
    V4 t52=add(s.R[11],neg(s.C[43]));
    wmask(s.R[0],t52,15);
    V4 t53=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t53,1);
    V4 t54=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[2],t54,1);
    V4 t55=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[3],t55,15);
    V4 t56=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t56,15);
    V4 t57=dp3(s.R[0],s.C[47]);
    wmask(s.R[2],t57,1);
    V4 t58=d3d_rcp(swz(s.R[2],0,0,0,0).w);
    wmask(s.R[2],t58,1);
    V4 t59=slt(swz(s.R[0],1,1,1,1),swz(s.C[47],3,3,3,3));
    wmask(s.R[1],t59,1);
    V4 t60=mul(swz(s.R[2],0,0,0,0),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t60,1);
    V4 t61=dp3(neg(s.R[10]),s.R[3]);
    wmask(s.R[4],t61,1);
    V4 t62=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t62,15);
    V4 t63=mul(s.R[0],swz(s.R[2],0,0,0,0));
    wmask(s.R[0],t63,15);
    V4 t64=mad(s.R[0],s.C[25],s.R[5]);
    wmask(s.R[5],t64,15);
    V4 t65=mad(swz(s.R[2],0,0,0,0),s.C[31],s.R[6]);
    wmask(s.R[6],t65,15);
    V4 t66=dp3(neg(s.R[10]),s.C[37]);
    wmask(s.R[4],t66,1);
    V4 t67=max(swz(s.R[4],0,0,0,0),s.C[0]);
    wmask(s.R[0],t67,15);
    V4 t68=mad(s.R[0],s.C[21],s.R[5]);
    wmask(s.R[5],t68,15);
    V4 t69=mul(swz(s.R[4],0,0,0,0),s.C[26]);
    wmask(s.R[1],t69,15);
    V4 t70=add(s.R[1],s.C[27]);
    wmask(s.R[1],t70,15);
    V4 t71=add(s.R[1],s.R[6]);
    wmask(s.R[6],t71,15);
    V4 t72=mad(s.R[6],s.R[8],s.C[20]);
    wmask(s.R[6],t72,15);
    V4 t73=mul(s.R[6],s.C[16]);
    wmask(s.R[6],t73,15);
    V4 t74=mad(s.R[5],s.R[9],s.R[6]);
    wmask(s.oD[0],t74,15);
    V4 t75=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t75,15);
}
void vs_22(VsState& s){ // 620AC0
    V4 t0=swz(s.C[32],3,3,3,3);
    wmask(s.R[3],t0,8);
    V4 t1=swz(s.C[0],3,3,3,3);
    wmask(s.R[6],t1,8);
    V4 t2=add(s.R[11],neg(s.C[17]));
    wmask(s.R[0],t2,15);
    V4 t3=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t3,8);
    V4 t4=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t4,8);
    V4 t5=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[4],t5,15);
    V4 t6=add(s.R[11],neg(s.C[40]));
    wmask(s.R[0],t6,15);
    V4 t7=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t7,1);
    V4 t8=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[1],t8,2);
    V4 t9=mul(s.R[0],swz(s.R[1],1,1,1,1));
    wmask(s.R[2],t9,7);
    V4 t10=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[1],1,1,1,1));
    wmask(s.R[0],t10,15);
    V4 t11=dp3(s.R[0],s.C[44]);
    wmask(s.R[2],t11,8);
    V4 t12=d3d_rcp(swz(s.R[2],3,3,3,3).w);
    wmask(s.R[2],t12,8);
    V4 t13=slt(swz(s.R[0],1,1,1,1),swz(s.C[44],3,3,3,3));
    wmask(s.R[1],t13,1);
    V4 t14=mul(swz(s.R[2],3,3,3,3),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t14,8);
    V4 t15=dp3(swz(s.R[2],0,1,2,2),s.C[38]);
    wmask(s.R[0],t15,1);
    V4 t16=mad(swz(s.R[0],0,0,0,0),swz(s.C[48],0,0,0,0),swz(s.C[48],1,1,1,1));
    wmask(s.R[0],t16,1);
    V4 t17=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t17,1);
    V4 t18=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t18,1);
    V4 t19=mul(swz(s.R[2],3,3,3,3),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t19,8);
    V4 t20=add(swz(s.R[2],0,1,2,2),s.R[4]);
    wmask(s.R[1],t20,15);
    V4 t21=dp3(s.R[1],s.R[1]);
    wmask(s.R[0],t21,8);
    V4 t22=d3d_rsq(swz(s.R[0],3,3,3,3).w);
    wmask(s.R[0],t22,8);
    V4 t23=mul(s.R[1],swz(s.R[0],3,3,3,3));
    wmask(s.R[1],t23,15);
    V4 t24=dp3(neg(s.R[10]),s.R[1]);
    wmask(s.R[3],t24,2);
    V4 t25=dp3(neg(s.R[10]),swz(s.R[2],0,1,2,2));
    wmask(s.R[3],t25,1);
    V4 t26=d3d_lit(s.R[3]);
    wmask(s.R[0],t26,15);
    V4 t27=mul(s.R[0],swz(s.R[2],3,3,3,3));
    wmask(s.R[0],t27,15);
    V4 t28=mul(swz(s.R[2],3,3,3,3),s.C[28]);
    wmask(s.R[5],t28,15);
    V4 t29=mul(swz(s.R[0],1,1,1,1),s.C[22]);
    wmask(s.R[6],t29,7);
    V4 t30=mul(swz(s.R[0],2,2,2,2),s.C[33]);
    wmask(s.R[7],t30,15);
    V4 t31=add(s.R[11],neg(s.C[41]));
    wmask(s.R[0],t31,15);
    V4 t32=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t32,1);
    V4 t33=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[1],t33,2);
    V4 t34=mul(s.R[0],swz(s.R[1],1,1,1,1));
    wmask(s.R[2],t34,7);
    V4 t35=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[1],1,1,1,1));
    wmask(s.R[0],t35,15);
    V4 t36=dp3(s.R[0],s.C[45]);
    wmask(s.R[2],t36,8);
    V4 t37=d3d_rcp(swz(s.R[2],3,3,3,3).w);
    wmask(s.R[2],t37,8);
    V4 t38=slt(swz(s.R[0],1,1,1,1),swz(s.C[45],3,3,3,3));
    wmask(s.R[1],t38,1);
    V4 t39=mul(swz(s.R[2],3,3,3,3),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t39,8);
    V4 t40=dp3(swz(s.R[2],0,1,2,2),s.C[39]);
    wmask(s.R[0],t40,1);
    V4 t41=mad(swz(s.R[0],0,0,0,0),swz(s.C[49],0,0,0,0),swz(s.C[49],1,1,1,1));
    wmask(s.R[0],t41,1);
    V4 t42=max(swz(s.R[0],0,0,0,0),swz(s.C[0],0,0,0,0));
    wmask(s.R[0],t42,1);
    V4 t43=min(swz(s.R[0],0,0,0,0),swz(s.C[0],3,3,3,3));
    wmask(s.R[0],t43,1);
    V4 t44=mul(swz(s.R[2],3,3,3,3),swz(s.R[0],0,0,0,0));
    wmask(s.R[2],t44,8);
    V4 t45=dp3(neg(s.R[10]),swz(s.R[2],0,1,2,2));
    wmask(s.R[3],t45,1);
    V4 t46=max(swz(s.R[3],0,0,0,0),s.C[0]);
    wmask(s.R[0],t46,2);
    V4 t47=mul(s.R[0],swz(s.R[2],3,3,3,3));
    wmask(s.R[0],t47,15);
    V4 t48=mad(swz(s.R[2],3,3,3,3),s.C[29],s.R[5]);
    wmask(s.R[5],t48,15);
    V4 t49=mad(swz(s.R[0],1,1,1,1),s.C[23],s.R[6]);
    wmask(s.R[6],t49,7);
    V4 t50=add(s.R[11],neg(s.C[42]));
    wmask(s.R[0],t50,15);
    V4 t51=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t51,1);
    V4 t52=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[1],t52,2);
    V4 t53=mul(s.R[0],swz(s.R[1],1,1,1,1));
    wmask(s.R[2],t53,7);
    V4 t54=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[1],1,1,1,1));
    wmask(s.R[0],t54,15);
    V4 t55=dp3(s.R[0],s.C[46]);
    wmask(s.R[2],t55,8);
    V4 t56=d3d_rcp(swz(s.R[2],3,3,3,3).w);
    wmask(s.R[2],t56,8);
    V4 t57=slt(swz(s.R[0],1,1,1,1),swz(s.C[46],3,3,3,3));
    wmask(s.R[1],t57,1);
    V4 t58=mul(swz(s.R[2],3,3,3,3),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t58,8);
    V4 t59=dp3(neg(s.R[10]),swz(s.R[2],0,1,2,2));
    wmask(s.R[3],t59,1);
    V4 t60=max(swz(s.R[3],0,0,0,0),s.C[0]);
    wmask(s.R[0],t60,2);
    V4 t61=mul(s.R[0],swz(s.R[2],3,3,3,3));
    wmask(s.R[0],t61,15);
    V4 t62=mad(swz(s.R[2],3,3,3,3),s.C[30],s.R[5]);
    wmask(s.R[5],t62,15);
    V4 t63=mad(swz(s.R[0],1,1,1,1),s.C[24],s.R[6]);
    wmask(s.R[6],t63,7);
    V4 t64=add(s.R[11],neg(s.C[43]));
    wmask(s.R[0],t64,15);
    V4 t65=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t65,1);
    V4 t66=d3d_rsq(swz(s.R[1],0,0,0,0).w);
    wmask(s.R[1],t66,2);
    V4 t67=mul(s.R[0],swz(s.R[1],1,1,1,1));
    wmask(s.R[2],t67,7);
    V4 t68=d3d_dst(swz(s.R[1],0,0,0,0),swz(s.R[1],1,1,1,1));
    wmask(s.R[0],t68,15);
    V4 t69=dp3(s.R[0],s.C[47]);
    wmask(s.R[2],t69,8);
    V4 t70=d3d_rcp(swz(s.R[2],3,3,3,3).w);
    wmask(s.R[2],t70,8);
    V4 t71=slt(swz(s.R[0],1,1,1,1),swz(s.C[47],3,3,3,3));
    wmask(s.R[1],t71,1);
    V4 t72=mul(swz(s.R[2],3,3,3,3),swz(s.R[1],0,0,0,0));
    wmask(s.R[2],t72,8);
    V4 t73=dp3(neg(s.R[10]),swz(s.R[2],0,1,2,2));
    wmask(s.R[3],t73,1);
    V4 t74=max(swz(s.R[3],0,0,0,0),s.C[0]);
    wmask(s.R[0],t74,2);
    V4 t75=mul(s.R[0],swz(s.R[2],3,3,3,3));
    wmask(s.R[0],t75,15);
    V4 t76=mad(swz(s.R[2],3,3,3,3),s.C[31],s.R[5]);
    wmask(s.R[5],t76,15);
    V4 t77=mad(swz(s.R[0],1,1,1,1),s.C[25],s.R[6]);
    wmask(s.R[6],t77,7);
    V4 t78=dp3(neg(s.R[10]),s.C[37]);
    wmask(s.R[3],t78,1);
    V4 t79=max(swz(s.R[3],0,0,0,0),s.C[0]);
    wmask(s.R[0],t79,2);
    V4 t80=mad(swz(s.R[0],1,1,1,1),s.C[21],s.R[6]);
    wmask(s.R[6],t80,7);
    V4 t81=mul(swz(s.R[3],0,0,0,0),s.C[26]);
    wmask(s.R[1],t81,15);
    V4 t82=add(s.R[1],s.C[27]);
    wmask(s.R[1],t82,15);
    V4 t83=add(s.R[5],s.R[1]);
    wmask(s.R[5],t83,15);
    V4 t84=mad(s.R[5],s.R[8],s.C[20]);
    wmask(s.R[5],t84,15);
    V4 t85=mul(s.R[5],s.C[16]);
    wmask(s.R[5],t85,15);
    V4 t86=mad(s.R[6],s.R[9],s.R[5]);
    wmask(s.oD[0],t86,15);
    V4 t87=s.R[7];
    wmask(s.oD[1],t87,7);
}
void vs_23(VsState& s){ // 62103C
    V4 t0=dp4(s.R[9],s.C[68]);
    wmask(s.oT[0],t0,1);
    V4 t1=dp4(s.R[9],s.C[69]);
    wmask(s.oT[0],t1,2);
}
void vs_24(VsState& s){ // 621064
    V4 t0=dp4(s.R[9],s.C[68]);
    wmask(s.oT[0],t0,1);
    V4 t1=dp4(s.R[9],s.C[69]);
    wmask(s.oT[0],t1,2);
    V4 t2=dp4(s.R[9],s.C[70]);
    wmask(s.oT[0],t2,4);
}
void vs_25(VsState& s){ // 6210A0
    V4 t0=dp4(s.R[9],s.C[68]);
    wmask(s.oT[0],t0,1);
    V4 t1=dp4(s.R[9],s.C[69]);
    wmask(s.oT[0],t1,2);
    V4 t2=dp4(s.R[9],s.C[70]);
    wmask(s.oT[0],t2,4);
    V4 t3=dp4(s.R[9],s.C[71]);
    wmask(s.oT[0],t3,8);
}
void vs_26(VsState& s){ // 6210E8
    V4 t0=s.R[9];
    wmask(s.oT[0],t0,15);
}
void vs_27(VsState& s){ // 6210FC
    V4 t0=dp4(s.R[9],s.C[72]);
    wmask(s.oT[1],t0,1);
    V4 t1=dp4(s.R[9],s.C[73]);
    wmask(s.oT[1],t1,2);
}
void vs_28(VsState& s){ // 621124
    V4 t0=dp4(s.R[9],s.C[72]);
    wmask(s.oT[1],t0,1);
    V4 t1=dp4(s.R[9],s.C[73]);
    wmask(s.oT[1],t1,2);
    V4 t2=dp4(s.R[9],s.C[74]);
    wmask(s.oT[1],t2,4);
}
void vs_29(VsState& s){ // 621160
    V4 t0=dp4(s.R[9],s.C[72]);
    wmask(s.oT[1],t0,1);
    V4 t1=dp4(s.R[9],s.C[73]);
    wmask(s.oT[1],t1,2);
    V4 t2=dp4(s.R[9],s.C[74]);
    wmask(s.oT[1],t2,4);
    V4 t3=dp4(s.R[9],s.C[75]);
    wmask(s.oT[1],t3,8);
}
void vs_30(VsState& s){ // 6211A8
    V4 t0=s.R[9];
    wmask(s.oT[1],t0,15);
}
void vs_31(VsState& s){ // 6211BC
    V4 t0=dp4(s.R[9],s.C[76]);
    wmask(s.oT[2],t0,1);
    V4 t1=dp4(s.R[9],s.C[77]);
    wmask(s.oT[2],t1,2);
}
void vs_32(VsState& s){ // 6211E4
    V4 t0=dp4(s.R[9],s.C[76]);
    wmask(s.oT[2],t0,1);
    V4 t1=dp4(s.R[9],s.C[77]);
    wmask(s.oT[2],t1,2);
    V4 t2=dp4(s.R[9],s.C[78]);
    wmask(s.oT[2],t2,4);
}
void vs_33(VsState& s){ // 621220
    V4 t0=dp4(s.R[9],s.C[76]);
    wmask(s.oT[2],t0,1);
    V4 t1=dp4(s.R[9],s.C[77]);
    wmask(s.oT[2],t1,2);
    V4 t2=dp4(s.R[9],s.C[78]);
    wmask(s.oT[2],t2,4);
    V4 t3=dp4(s.R[9],s.C[79]);
    wmask(s.oT[2],t3,8);
}
void vs_34(VsState& s){ // 621268
    V4 t0=s.R[9];
    wmask(s.oT[2],t0,15);
}
void vs_35(VsState& s){ // 62127C
    V4 t0=s.V[7];
    wmask(s.R[9],t0,15);
}
void vs_36(VsState& s){ // 621290
    (void)s;
}
void vs_37(VsState& s){ // 6212A4
    V4 t0=s.V[8];
    wmask(s.R[9],t0,15);
}
void vs_38(VsState& s){ // 6212B8
    (void)s;
}
void vs_39(VsState& s){ // 6212CC
    V4 t0=s.V[9];
    wmask(s.R[9],t0,15);
}
void vs_40(VsState& s){ // 6212E0
    (void)s;
}
void vs_41(VsState& s){ // 6212F4
    V4 t0=s.V[10];
    wmask(s.R[9],t0,15);
}
void vs_42(VsState& s){ // 621308
    (void)s;
}
void vs_43(VsState& s){ // 62131C
    V4 t0=mul(s.V[7],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.V[11],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.R[9],t1,15);
}
void vs_44(VsState& s){ // 621348
    (void)s;
}
void vs_45(VsState& s){ // 621368
    V4 t0=mul(s.V[8],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.V[12],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.R[9],t1,15);
}
void vs_46(VsState& s){ // 621394
    (void)s;
}
void vs_47(VsState& s){ // 6213B4
    V4 t0=mul(s.V[9],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.V[15],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.R[9],t1,15);
}
void vs_48(VsState& s){ // 6213E0
    (void)s;
}
void vs_49(VsState& s){ // 621400
    V4 t0=mul(s.V[10],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.V[15],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.R[9],t1,15);
}
void vs_50(VsState& s){ // 62142C
    (void)s;
}
void vs_51(VsState& s){ // 62144C
    V4 t0=s.R[10];
    wmask(s.R[9],t0,15);
}
void vs_52(VsState& s){ // 621460
    V4 t0=s.R[11];
    wmask(s.R[9],t0,15);
}
void vs_53(VsState& s){ // 621478
    V4 t0=add(s.R[11],neg(s.C[17]));
    wmask(s.R[0],t0,15);
    V4 t1=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t1,8);
    V4 t2=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t2,8);
    V4 t3=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[3],t3,15);
    V4 t4=dp3(s.R[10],s.R[3]);
    wmask(s.R[0],t4,1);
    V4 t5=add(swz(s.R[0],0,0,0,0),swz(s.R[0],0,0,0,0));
    wmask(s.R[0],t5,2);
    V4 t6=mad(s.R[10],neg(swz(s.R[0],1,1,1,1)),s.R[3]);
    wmask(s.R[9],t6,15);
}
void vs_54(VsState& s){ // 6214F0
    V4 t0=add(s.R[11],neg(s.C[17]));
    wmask(s.R[0],t0,15);
    V4 t1=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t1,8);
    V4 t2=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t2,8);
    V4 t3=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[3],t3,15);
    V4 t4=dp3(s.R[10],s.R[3]);
    wmask(s.R[0],t4,1);
    V4 t5=add(swz(s.R[0],0,0,0,0),swz(s.R[0],0,0,0,0));
    wmask(s.R[0],t5,2);
    V4 t6=mad(s.R[10],neg(swz(s.R[0],1,1,1,1)),s.R[3]);
    wmask(s.R[9],t6,15);
    V4 t7=s.C[9];
    wmask(s.R[1],t7,15);
    V4 t8=max(swz(s.R[0],0,0,0,0),neg(swz(s.R[0],0,0,0,0)));
    wmask(s.R[0],t8,1);
    V4 t9=add(swz(s.C[0],3,3,3,3),neg(swz(s.R[0],0,0,0,0)));
    wmask(s.R[1],t9,2);
    V4 t10=d3d_lit(s.R[1]);
    wmask(s.R[0],t10,15);
    V4 t11=mad(swz(s.R[0],2,2,2,2),swz(s.C[9],0,0,0,0),swz(s.C[9],2,2,2,2));
    wmask(s.oD[1],t11,8);
}
void vs_55(VsState& s){ // 6215B8
    V4 t0=dp4(s.R[11],s.C[80]);
    wmask(s.oT[3],t0,1);
    V4 t1=dp4(s.R[11],s.C[81]);
    wmask(s.oT[3],t1,2);
    V4 t2=dp4(s.R[11],s.C[82]);
    wmask(s.oT[3],t2,4);
    V4 t3=dp4(s.R[11],s.C[83]);
    wmask(s.oT[3],t3,8);
}
void vs_56(VsState& s){ // 621600
    V4 t0=dp4(s.R[11],s.C[80]);
    wmask(s.oT[3],t0,1);
    V4 t1=dp4(s.R[11],s.C[81]);
    wmask(s.oT[3],t1,2);
    V4 t2=dp4(s.R[11],s.C[82]);
    wmask(s.oT[3],t2,4);
    V4 t3=dp4(s.R[11],s.C[83]);
    wmask(s.oT[3],t3,8);
}
void vs_57(VsState& s){ // 621648
    (void)s;
}
void vs_58(VsState& s){ // 621650
    (void)s;
}
void vs_59(VsState& s){ // 6216A0
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.V[7];
    wmask(s.oT[0],t1,15);
    V4 t2=s.V[8];
    wmask(s.oT[1],t2,15);
    V4 t3=s.V[3];
    wmask(s.R[2],t3,15);
    V4 t4=neg(s.V[9]);
    wmask(s.R[3],t4,15);
    V4 t5=mul(swz(s.R[3],2,0,1,1),swz(s.R[2],1,2,0,0));
    wmask(s.R[0],t5,15);
    V4 t6=mad(swz(s.R[3],1,2,0,0),swz(s.R[2],2,0,1,1),neg(s.R[0]));
    wmask(s.R[4],t6,15);
    V4 t7=mul(swz(s.R[4],2,0,1,1),swz(s.R[3],1,2,0,0));
    wmask(s.R[0],t7,15);
    V4 t8=mad(swz(s.R[4],1,2,0,0),swz(s.R[3],2,0,1,1),neg(s.R[0]));
    wmask(s.R[5],t8,15);
    V4 t9=dp3(s.R[4],neg(s.C[37]));
    wmask(s.oT[2],t9,1);
    V4 t10=dp3(s.R[5],neg(s.C[37]));
    wmask(s.oT[2],t10,4);
    V4 t11=dp3(s.R[3],neg(s.C[37]));
    wmask(s.oT[2],t11,2);
    V4 t12=add(s.V[0],neg(s.C[17]));
    wmask(s.R[0],t12,15);
    V4 t13=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t13,8);
    V4 t14=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t14,8);
    V4 t15=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[7],t15,15);
    V4 t16=add(s.R[7],s.C[37]);
    wmask(s.R[0],t16,15);
    V4 t17=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t17,8);
    V4 t18=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t18,8);
    V4 t19=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[6],t19,15);
    V4 t20=dp3(s.R[4],neg(s.R[6]));
    wmask(s.oT[3],t20,1);
    V4 t21=dp3(s.R[5],neg(s.R[6]));
    wmask(s.oT[3],t21,4);
    V4 t22=dp3(s.R[3],neg(s.R[6]));
    wmask(s.oT[3],t22,2);
}
void vs_60(VsState& s){ // 621848
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=add(s.V[0],neg(s.C[17]));
    wmask(s.R[7],t1,15);
    V4 t2=dp3(s.R[7],s.R[7]);
    wmask(s.R[1],t2,8);
    V4 t3=swz(s.C[32],3,3,3,3);
    wmask(s.R[9],t3,8);
    V4 t4=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t4,8);
    V4 t5=mul(s.R[7],swz(s.R[1],3,3,3,3));
    wmask(s.R[0],t5,15);
    V4 t6=add(s.R[0],s.C[37]);
    wmask(s.R[0],t6,15);
    V4 t7=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t7,8);
    V4 t8=swz(s.C[32],3,3,3,3);
    wmask(s.R[8],t8,8);
    V4 t9=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t9,8);
    V4 t10=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[6],t10,15);
    V4 t11=dp3(neg(s.V[3]),s.R[6]);
    wmask(s.R[9],t11,2);
    V4 t12=dp3(s.V[3],s.R[6]);
    wmask(s.R[8],t12,2);
    V4 t13=dp3(neg(s.V[3]),s.C[37]);
    wmask(s.R[9],t13,1);
    V4 t14=max(swz(s.R[9],0,0,0,0),s.C[0]);
    wmask(s.R[0],t14,15);
    V4 t15=mul(swz(s.R[9],0,0,0,0),s.C[26]);
    wmask(s.R[1],t15,15);
    V4 t16=add(s.R[1],s.C[27]);
    wmask(s.R[1],t16,15);
    V4 t17=mul(s.R[1],s.C[19]);
    wmask(s.R[1],t17,15);
    V4 t18=add(s.R[1],s.C[20]);
    wmask(s.R[1],t18,15);
    V4 t19=s.C[18];
    wmask(s.R[2],t19,15);
    V4 t20=mul(s.R[2],s.C[21]);
    wmask(s.R[2],t20,15);
    V4 t21=mad(s.R[0],s.R[2],s.R[1]);
    wmask(s.oD[0],t21,15);
    V4 t22=dp3(s.V[3],s.C[37]);
    wmask(s.R[8],t22,1);
    V4 t23=max(swz(s.R[8],0,0,0,0),s.C[0]);
    wmask(s.R[0],t23,15);
    V4 t24=d3d_lit(s.R[9]);
    wmask(s.R[0],t24,15);
    V4 t25=d3d_lit(s.R[8]);
    wmask(s.R[1],t25,15);
    V4 t26=mul(swz(s.R[0],2,2,2,2),swz(s.C[32],0,1,2,2));
    wmask(s.oD[1],t26,15);
    V4 t27=s.V[3];
    wmask(s.R[2],t27,15);
    V4 t28=s.V[9];
    wmask(s.R[3],t28,15);
    V4 t29=s.V[7];
    wmask(s.oT[0],t29,15);
    V4 t30=mul(swz(s.R[3],2,0,1,1),swz(s.R[2],1,2,0,0));
    wmask(s.R[0],t30,15);
    V4 t31=mad(swz(s.R[3],1,2,0,0),swz(s.R[2],2,0,1,1),neg(s.R[0]));
    wmask(s.R[4],t31,15);
    V4 t32=mul(swz(s.R[4],2,0,1,1),swz(s.R[3],1,2,0,0));
    wmask(s.R[0],t32,15);
    V4 t33=mad(swz(s.R[4],1,2,0,0),swz(s.R[3],2,0,1,1),neg(s.R[0]));
    wmask(s.R[5],t33,15);
    V4 t34=dp3(s.R[4],s.C[72]);
    wmask(s.oT[1],t34,1);
    V4 t35=dp3(s.R[3],s.C[72]);
    wmask(s.oT[1],t35,2);
    V4 t36=dp3(s.R[5],s.C[72]);
    wmask(s.oT[1],t36,4);
    V4 t37=neg(swz(s.R[7],0,0,0,0));
    wmask(s.oT[1],t37,8);
    V4 t38=dp3(s.R[4],s.C[73]);
    wmask(s.oT[2],t38,1);
    V4 t39=dp3(s.R[3],s.C[73]);
    wmask(s.oT[2],t39,2);
    V4 t40=dp3(s.R[5],s.C[73]);
    wmask(s.oT[2],t40,4);
    V4 t41=neg(swz(s.R[7],1,1,1,1));
    wmask(s.oT[2],t41,8);
    V4 t42=dp3(s.R[4],s.C[74]);
    wmask(s.oT[3],t42,1);
    V4 t43=dp3(s.R[3],s.C[74]);
    wmask(s.oT[3],t43,2);
    V4 t44=dp3(s.R[5],s.C[74]);
    wmask(s.oT[3],t44,4);
    V4 t45=neg(swz(s.R[7],2,2,2,2));
    wmask(s.oT[3],t45,8);
}
void vs_61(VsState& s){ // 621B38
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=add(s.V[0],neg(s.C[17]));
    wmask(s.R[7],t1,15);
    V4 t2=dp3(s.R[7],s.R[7]);
    wmask(s.R[1],t2,8);
    V4 t3=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t3,8);
    V4 t4=swz(s.C[32],3,3,3,3);
    wmask(s.R[9],t4,8);
    V4 t5=mul(s.R[7],swz(s.R[1],3,3,3,3));
    wmask(s.R[7],t5,15);
    V4 t6=s.R[7];
    wmask(s.R[0],t6,15);
    V4 t7=add(s.R[0],s.C[37]);
    wmask(s.R[0],t7,15);
    V4 t8=dp3(s.R[0],s.R[0]);
    wmask(s.R[1],t8,8);
    V4 t9=swz(s.C[32],3,3,3,3);
    wmask(s.R[8],t9,8);
    V4 t10=d3d_rsq(swz(s.R[1],3,3,3,3).w);
    wmask(s.R[1],t10,8);
    V4 t11=mul(s.R[0],swz(s.R[1],3,3,3,3));
    wmask(s.R[6],t11,15);
    V4 t12=dp3(neg(s.V[3]),s.R[6]);
    wmask(s.R[9],t12,2);
    V4 t13=dp3(s.V[3],s.R[6]);
    wmask(s.R[8],t13,2);
    V4 t14=dp3(neg(s.V[3]),s.C[37]);
    wmask(s.R[9],t14,1);
    V4 t15=max(swz(s.R[9],0,0,0,0),s.C[0]);
    wmask(s.R[0],t15,15);
    V4 t16=mul(swz(s.R[9],0,0,0,0),s.C[26]);
    wmask(s.R[1],t16,15);
    V4 t17=add(s.R[1],s.C[27]);
    wmask(s.R[1],t17,15);
    V4 t18=mul(s.R[1],s.C[19]);
    wmask(s.R[1],t18,15);
    V4 t19=add(s.R[1],s.C[20]);
    wmask(s.R[1],t19,15);
    V4 t20=s.C[18];
    wmask(s.R[2],t20,15);
    V4 t21=mul(s.R[2],s.C[21]);
    wmask(s.R[2],t21,15);
    V4 t22=mad(s.R[0],s.R[2],s.R[1]);
    wmask(s.oD[0],t22,15);
    V4 t23=dp3(s.V[3],s.C[37]);
    wmask(s.R[8],t23,1);
    V4 t24=max(swz(s.R[8],0,0,0,0),s.C[0]);
    wmask(s.R[0],t24,15);
    V4 t25=d3d_lit(s.R[9]);
    wmask(s.R[0],t25,15);
    V4 t26=mul(swz(s.R[0],2,2,2,2),swz(s.C[32],0,1,2,2));
    wmask(s.oD[1],t26,15);
    V4 t27=s.V[3];
    wmask(s.R[2],t27,15);
    V4 t28=s.V[9];
    wmask(s.R[3],t28,15);
    V4 t29=s.V[7];
    wmask(s.oT[0],t29,15);
    V4 t30=mul(swz(s.R[3],2,0,1,1),swz(s.R[2],1,2,0,0));
    wmask(s.R[0],t30,15);
    V4 t31=mad(swz(s.R[3],1,2,0,0),swz(s.R[2],2,0,1,1),neg(s.R[0]));
    wmask(s.R[4],t31,15);
    V4 t32=mul(swz(s.R[4],2,0,1,1),swz(s.R[3],1,2,0,0));
    wmask(s.R[0],t32,15);
    V4 t33=mad(swz(s.R[4],1,2,0,0),swz(s.R[3],2,0,1,1),neg(s.R[0]));
    wmask(s.R[5],t33,15);
    V4 t34=dp3(s.R[4],s.C[72]);
    wmask(s.oT[1],t34,1);
    V4 t35=dp3(s.R[3],s.C[72]);
    wmask(s.oT[1],t35,2);
    V4 t36=dp3(s.R[5],s.C[72]);
    wmask(s.oT[1],t36,4);
    V4 t37=dp3(s.R[4],s.C[73]);
    wmask(s.oT[2],t37,1);
    V4 t38=dp3(s.R[3],s.C[73]);
    wmask(s.oT[2],t38,2);
    V4 t39=dp3(s.R[5],s.C[73]);
    wmask(s.oT[2],t39,4);
    V4 t40=dp3(s.R[4],s.C[74]);
    wmask(s.oT[3],t40,1);
    V4 t41=dp3(s.R[3],s.C[74]);
    wmask(s.oT[3],t41,2);
    V4 t42=dp3(s.R[5],s.C[74]);
    wmask(s.oT[3],t42,4);
    V4 t43=s.R[7];
    wmask(s.oT[4],t43,15);
}
void vs_62(VsState& s){ // 621E10
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.V[5];
    wmask(s.R[0],t1,15);
    V4 t2=sge(s.R[0],s.R[0]);
    wmask(s.R[1],t2,15);
    V4 t3=add(s.R[1],neg(s.R[0]));
    wmask(s.R[2],t3,15);
    V4 t4=mul(s.R[0],s.C[8]);
    wmask(s.R[3],t4,15);
    V4 t5=mad(s.R[2],s.C[7],s.R[3]);
    wmask(s.oD[0],t5,15);
}
void vs_63(VsState& s){ // 621E90
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.C[18];
    wmask(s.oD[0],t1,15);
    V4 t2=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t2,15);
    V4 t3=s.V[7];
    wmask(s.oT[0],t3,15);
    V4 t4=s.V[8];
    wmask(s.oT[1],t4,15);
}
void vs_64(VsState& s){ // 621F00
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=mul(s.V[5],s.C[18]);
    wmask(s.oD[0],t1,15);
    V4 t2=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t2,15);
    V4 t3=s.V[7];
    wmask(s.oT[0],t3,15);
    V4 t4=s.V[8];
    wmask(s.oT[1],t4,15);
}
void vs_65(VsState& s){ // 621F80
    V4 t0=mul(s.V[0],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.V[13],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.R[1],t1,15);
    V4 t2=v4(dp4(s.R[1],s.C[64]).x,dp4(s.R[1],s.C[65]).x,dp4(s.R[1],s.C[66]).x,dp4(s.R[1],s.C[67]).x);
    wmask(s.oPos,t2,15);
    V4 t3=mul(s.V[5],swz(s.C[7],0,0,0,0));
    wmask(s.R[1],t3,15);
    V4 t4=mad(s.V[15],swz(s.C[7],1,1,1,1),s.R[1]);
    wmask(s.oD[0],t4,15);
    V4 t5=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t5,15);
    V4 t6=mul(s.V[7],swz(s.C[7],0,0,0,0));
    wmask(s.R[0],t6,15);
    V4 t7=mad(s.V[11],swz(s.C[7],1,1,1,1),s.R[0]);
    wmask(s.oT[0],t7,3);
}
void vs_66(VsState& s){ // 622058
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.C[18];
    wmask(s.oD[0],t1,15);
    V4 t2=dp4(s.V[0],s.C[76]);
    wmask(s.oT[2],t2,1);
    V4 t3=dp4(s.V[0],s.C[77]);
    wmask(s.oT[2],t3,2);
    V4 t4=dp4(s.V[0],s.C[78]);
    wmask(s.oT[2],t4,4);
}
void vs_67(VsState& s){ // 6220B8
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.V[5];
    wmask(s.oD[0],t1,15);
    V4 t2=dp4(s.V[0],s.C[76]);
    wmask(s.oT[2],t2,1);
    V4 t3=dp4(s.V[0],s.C[77]);
    wmask(s.oT[2],t3,2);
    V4 t4=dp4(s.V[0],s.C[78]);
    wmask(s.oT[2],t4,4);
    V4 t5=dp4(s.V[0],s.C[80]);
    wmask(s.oT[3],t5,1);
    V4 t6=dp4(s.V[0],s.C[81]);
    wmask(s.oT[3],t6,2);
    V4 t7=dp4(s.V[0],s.C[82]);
    wmask(s.oT[3],t7,4);
}
void vs_68(VsState& s){ // 622158
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.C[18];
    wmask(s.R[0],t1,15);
    V4 t2=mul(s.R[0],s.C[10]);
    wmask(s.oD[0],t2,15);
    V4 t3=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t3,15);
    V4 t4=s.V[7];
    wmask(s.oT[0],t4,15);
}
void vs_69(VsState& s){ // 6221C0
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.C[18];
    wmask(s.R[0],t1,15);
    V4 t2=mul(s.R[0],s.C[10]);
    wmask(s.oD[0],t2,15);
    V4 t3=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t3,15);
}
void vs_70(VsState& s){ // 622210
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=s.C[18];
    wmask(s.oD[0],t1,15);
    V4 t2=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t2,15);
    V4 t3=s.V[7];
    wmask(s.oT[0],t3,15);
}
void vs_71(VsState& s){ // 622268
    V4 t0=v4(dp4(s.V[0],s.C[64]).x,dp4(s.V[0],s.C[65]).x,dp4(s.V[0],s.C[66]).x,dp4(s.V[0],s.C[67]).x);
    wmask(s.oPos,t0,15);
    V4 t1=mul(s.V[5],s.C[18]);
    wmask(s.oD[0],t1,15);
    V4 t2=swz(s.C[0],0,0,0,0);
    wmask(s.oD[1],t2,15);
    V4 t3=s.V[7];
    wmask(s.oT[0],t3,15);
}
void vs_72(VsState& s){ // 623E38
    V4 t0=dp4(s.V[0],s.C[64]);
    wmask(s.oPos,t0,1);
    V4 t1=dp4(s.V[0],s.C[65]);
    wmask(s.oPos,t1,2);
    V4 t2=dp4(s.V[0],s.C[66]);
    wmask(s.oPos,t2,4);
    V4 t3=dp4(s.V[0],s.C[67]);
    wmask(s.oPos,t3,8);
}
void ps14_0(Ps14State& s){ // 61EDE8
    (void)s;
}
void ps14_1(Ps14State& s){ // 61EDF0
    (void)s;
}
void ps14_2(Ps14State& s){ // 61EDF8
    wmask(s.R[0],s.sample(0,s.T[0]),15);
}
void ps14_3(Ps14State& s){ // 61EE0C
    wmask(s.R[0],s.sample(0,s.T[0]),15);
    wmask(s.R[1],s.sample(1,s.T[1]),15);
}
void ps14_4(Ps14State& s){ // 61EE2C
    wmask(s.R[0],s.sample(0,s.T[0]),15);
    wmask(s.R[2],s.sample(2,s.T[2]),15);
}
void ps14_5(Ps14State& s){ // 61EE4C
    wmask(s.R[0],s.sample(0,s.T[0]),15);
    wmask(s.R[1],s.sample(1,s.T[1]),15);
    wmask(s.R[2],s.sample(2,s.T[2]),15);
}
void ps14_6(Ps14State& s){ // 61EE78
    wmask(s.R[3],s.sample(3,s.T[3]),15);
}
void ps14_7(Ps14State& s){ // 61EE8C
    wmask(s.R[0],s.sample(0,s.T[0]),15);
    wmask(s.R[3],s.sample(3,s.T[3]),15);
}
void ps14_8(Ps14State& s){ // 61EEAC
    wmask(s.R[0],s.sample(0,s.T[0]),15);
    wmask(s.R[1],s.sample(1,s.T[1]),15);
    wmask(s.R[3],s.sample(3,s.T[3]),15);
}
void ps14_9(Ps14State& s){ // 61EED8
    wmask(s.R[0],s.sample(0,s.T[0]),15);
    wmask(s.R[1],s.sample(1,s.T[1]),15);
    wmask(s.R[2],s.sample(2,s.T[2]),15);
    wmask(s.R[3],s.sample(3,s.T[3]),15);
}
void ps14_10(Ps14State& s){ // 61EF10
    (void)s;
}
void ps14_11(Ps14State& s){ // 61EF18
    V4 t0=add(s.PC[6],s.R[3]);
    wmask(s.R[5],t0,7);
}
void ps14_12(Ps14State& s){ // 61EF30
    V4 t0=s.VC[0];
    wmask(s.R[4],t0,7);
}
void ps14_13(Ps14State& s){ // 61EF44
    V4 t0=mul(s.VC[1],s.R[0]);
    wmask(s.R[5],t0,7);
}
void ps14_14(Ps14State& s){ // 61EF5C
    V4 t0=mul(s.VC[1],swz(s.R[0],3,3,3,3));
    wmask(s.R[5],t0,7);
}
void ps14_15(Ps14State& s){ // 61EF74
    V4 t0=mul(s.R[0],s.VC[0]);
    wmask(s.R[4],t0,7);
}
void ps14_16(Ps14State& s){ // 61EF8C
    V4 t0=mul(s.R[0],s.VC[0]);
    wmask(s.R[4],t0,7);
}
void ps14_17(Ps14State& s){ // 61EFA4
    V4 t0=mad(s.R[0],s.R[5],s.VC[0]);
    wmask(s.R[4],t0,7);
}
void ps14_18(Ps14State& s){ // 61EFC0
    V4 t0=mul(s.R[0],swz(s.R[0],3,3,3,3));
    wmask(s.R[5],t0,7);
    V4 t1=mad(s.VC[0],sub(v4(1.0),swz(s.R[0],3,3,3,3)),s.R[5]);
    wmask(s.R[4],t1,7);
}
void ps14_19(Ps14State& s){ // 61EFEC
    V4 t0=s.R[0];
    wmask(s.R[4],t0,7);
}
void ps14_20(Ps14State& s){ // 61F000
    V4 t0=mul(s.R[1],s.VC[1]);
    wmask(s.R[5],t0,7);
}
void ps14_21(Ps14State& s){ // 61F018
    V4 t0=mul(s.R[1],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_22(Ps14State& s){ // 61F030
    V4 t0=mul(s.R[1],s.R[4]);
    wmask(s.R[4],mul(t0,v4(2.0f)),7);
}
void ps14_23(Ps14State& s){ // 61F048
    V4 t0=mul(s.R[2],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_24(Ps14State& s){ // 61F060
    V4 t0=mad(s.R[1],s.R[5],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_25(Ps14State& s){ // 61F07C
    V4 t0=mul(s.R[1],swz(s.R[1],3,3,3,3));
    wmask(s.R[5],t0,7);
    V4 t1=mad(s.R[4],sub(v4(1.0),swz(s.R[1],3,3,3,3)),s.R[5]);
    wmask(s.R[4],t1,7);
}
void ps14_26(Ps14State& s){ // 61F0A8
    V4 t0=add(s.R[1],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_27(Ps14State& s){ // 61F0C0
    V4 t0=mul(s.R[4],s.R[5]);
    wmask(s.R[4],t0,7);
}
void ps14_28(Ps14State& s){ // 61F0D8
    (void)s;
}
void ps14_29(Ps14State& s){ // 61F0E0
    V4 t0=mad(s.R[3],s.PC[6],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_30(Ps14State& s){ // 61F0FC
    V4 t0=mad(swz(s.R[4],3,3,3,3),s.R[1],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_31(Ps14State& s){ // 61F118
    V4 t0=mad(swz(s.R[4],3,3,3,3),s.R[2],s.R[4]);
    wmask(s.R[4],t0,7);
}
void ps14_32(Ps14State& s){ // 61F134
    V4 t0=add(swz(s.PC[6],3,3,3,3),swz(s.R[3],3,3,3,3));
    wmask(s.R[5],t0,8);
}
void ps14_33(Ps14State& s){ // 61F14C
    V4 t0=mad(sub(v4(1.0),swz(s.VC[1],3,3,3,3)),swz(s.R[0],3,3,3,3),swz(s.VC[1],3,3,3,3));
    wmask(s.R[5],t0,7);
}
void ps14_34(Ps14State& s){ // 61F168
    V4 t0=mad(sub(v4(1.0),swz(s.VC[1],3,3,3,3)),swz(s.R[1],3,3,3,3),swz(s.VC[1],3,3,3,3));
    wmask(s.R[5],t0,7);
}
void ps14_35(Ps14State& s){ // 61F184
    (void)s;
}
void ps14_36(Ps14State& s){ // 61F18C
    V4 t0=swz(s.VC[0],3,3,3,3);
    wmask(s.R[4],t0,8);
}
void ps14_37(Ps14State& s){ // 61F1A0
    V4 t0=mul(swz(s.R[0],3,3,3,3),swz(s.VC[0],3,3,3,3));
    wmask(s.R[4],t0,8);
}
void ps14_38(Ps14State& s){ // 61F1B8
    V4 t0=mul(swz(s.R[1],3,3,3,3),swz(s.R[4],3,3,3,3));
    wmask(s.R[4],t0,8);
}
void ps14_39(Ps14State& s){ // 61F1D0
    V4 t0=swz(s.R[1],3,3,3,3);
    wmask(s.R[4],t0,8);
}
void ps14_40(Ps14State& s){ // 61F1E4
    V4 t0=swz(s.R[2],3,3,3,3);
    wmask(s.R[4],t0,8);
}
void ps14_41(Ps14State& s){ // 61F1F8
    V4 t0=mul(swz(s.R[2],3,3,3,3),swz(s.R[4],3,3,3,3));
    wmask(s.R[4],t0,8);
}
void ps14_42(Ps14State& s){ // 61F210
    (void)s;
}
void ps14_43(Ps14State& s){ // 61F218
    V4 t0=add(s.R[4],s.VC[1]);
    V4 t1=swz(s.R[4],3,3,3,3);
    wmask(s.R[0],t0,7);
    wmask(s.R[0],t1,8);
}
void ps11_0(Ps11State& s){ // 61E7C4
    V4 t0=s.VC[0];
    wmask(s.R[0],t0,15);
}
void ps11_1(Ps11State& s){ // 61E7D8
    s.T[0]=s.sample(0,s.TC[0]);
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],t0,15);
}
void ps11_2(Ps11State& s){ // 61E7F8
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],t0,15);
    V4 t1=mul(s.T[1],s.R[0]);
    wmask(s.R[0],t1,15);
}
void ps11_3(Ps11State& s){ // 61E830
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],t0,15);
    V4 t1=mul(s.T[1],s.R[0]);
    wmask(s.R[0],t1,15);
    V4 t2=mul(s.T[2],s.R[0]);
    wmask(s.R[0],t2,15);
}
void ps11_4(Ps11State& s){ // 61E880
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
    s.T[3]=s.sample(3,s.TC[3]);
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],t0,15);
    V4 t1=mul(s.T[1],s.R[0]);
    wmask(s.R[0],t1,15);
    V4 t2=mul(s.T[2],s.R[0]);
    wmask(s.R[0],t2,15);
    V4 t3=mul(s.T[3],s.R[0]);
    wmask(s.R[0],t3,15);
}
void ps11_5(Ps11State& s){ // 61E8E8
    s.T[2]=s.sample(2,s.TC[2]);
    s.T[3]=s.sample(3,s.TC[3]);
    V4 t0=sub(v4(1.0),swz(s.T[3],3,3,3,3));
    wmask(s.R[1],mul(t0,v4(4.0f)),15);
    V4 t1=s.R[1];
    wmask(s.R[1],mul(t1,v4(4.0f)),15);
    V4 t2=sub(v4(1.0),swz(s.T[3],2,2,2,2));
    wmask(s.R[0],t2,8);
    V4 t3=mad(swz(s.R[0],3,3,3,3),v4(0.0625f,0.0625f,0.0625f,0.0625f),s.R[1]);
    wmask(s.R[1],t3,15);
    V4 t4=dp3(s.R[1],v4(1.0f,0.0f,0.0f,0.0f));
    wmask(s.R[1],t4,15);
    V4 t5=s.T[2];
    V4 t6=mul(swz(s.R[1],3,3,3,3),swz(s.VC[0],3,3,3,3));
    wmask(s.R[0],t5,7);
    wmask(s.R[0],t6,8);
}
void ps11_6(Ps11State& s){ // 61E9C4
    (void)s;
}
void ps11_7(Ps11State& s){ // 61E9E4
    (void)s;
}
void ps11_8(Ps11State& s){ // 61E9EC
    s.T[0]=s.sample(0,s.TC[0]);
}
void ps11_9(Ps11State& s){ // 61E9FC
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
}
void ps11_10(Ps11State& s){ // 61EA14
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[2]=s.sample(2,s.TC[2]);
}
void ps11_11(Ps11State& s){ // 61EA2C
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
}
void ps11_12(Ps11State& s){ // 61EA4C
    s.T[3]=s.sample(3,s.TC[3]);
}
void ps11_13(Ps11State& s){ // 61EA5C
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[3]=s.sample(3,s.TC[3]);
}
void ps11_14(Ps11State& s){ // 61EA74
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[3]=s.sample(3,s.TC[3]);
}
void ps11_15(Ps11State& s){ // 61EA94
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
    s.T[3]=s.sample(3,s.TC[3]);
}
void ps11_16(Ps11State& s){ // 61EABC
    (void)s;
}
void ps11_17(Ps11State& s){ // 61EAC4
    V4 t0=add(s.PC[6],s.T[3]);
    wmask(s.R[1],t0,7);
}
void ps11_18(Ps11State& s){ // 61EADC
    V4 t0=s.VC[0];
    wmask(s.R[0],t0,7);
}
void ps11_19(Ps11State& s){ // 61EAF0
    V4 t0=mul(s.VC[1],s.T[0]);
    wmask(s.R[1],t0,7);
}
void ps11_20(Ps11State& s){ // 61EB08
    V4 t0=mul(s.VC[1],swz(s.T[0],3,3,3,3));
    wmask(s.R[1],t0,7);
}
void ps11_21(Ps11State& s){ // 61EB20
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],t0,7);
}
void ps11_22(Ps11State& s){ // 61EB38
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],t0,7);
}
void ps11_23(Ps11State& s){ // 61EB50
    V4 t0=mad(s.T[0],s.R[1],s.VC[0]);
    wmask(s.R[0],t0,7);
}
void ps11_24(Ps11State& s){ // 61EB6C
    V4 t0=mul(s.T[0],swz(s.T[0],3,3,3,3));
    wmask(s.R[1],t0,7);
    V4 t1=mad(s.VC[0],sub(v4(1.0),swz(s.T[1],3,3,3,3)),s.R[1]);
    wmask(s.R[0],t1,7);
}
void ps11_25(Ps11State& s){ // 61EB98
    V4 t0=s.T[0];
    wmask(s.R[0],t0,7);
}
void ps11_26(Ps11State& s){ // 61EBAC
    V4 t0=mul(s.T[1],s.VC[1]);
    wmask(s.R[1],t0,7);
}
void ps11_27(Ps11State& s){ // 61EBC4
    V4 t0=mul(s.T[1],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_28(Ps11State& s){ // 61EBDC
    V4 t0=mul(s.T[1],s.R[0]);
    wmask(s.R[0],mul(t0,v4(2.0f)),7);
}
void ps11_29(Ps11State& s){ // 61EBF4
    V4 t0=mul(s.T[2],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_30(Ps11State& s){ // 61EC0C
    V4 t0=mad(s.T[1],s.R[1],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_31(Ps11State& s){ // 61EC28
    V4 t0=mul(s.T[1],swz(s.T[1],3,3,3,3));
    wmask(s.R[1],t0,7);
    V4 t1=mad(s.R[0],sub(v4(1.0),swz(s.T[1],3,3,3,3)),s.R[1]);
    wmask(s.R[0],t1,7);
}
void ps11_32(Ps11State& s){ // 61EC54
    V4 t0=add(s.T[1],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_33(Ps11State& s){ // 61EC6C
    V4 t0=mul(s.R[0],s.R[1]);
    wmask(s.R[0],t0,7);
}
void ps11_34(Ps11State& s){ // 61EC84
    (void)s;
}
void ps11_35(Ps11State& s){ // 61EC8C
    V4 t0=mad(s.T[3],s.PC[6],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_36(Ps11State& s){ // 61ECA8
    V4 t0=mad(swz(s.R[0],3,3,3,3),s.T[1],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_37(Ps11State& s){ // 61ECC4
    V4 t0=mad(swz(s.R[0],3,3,3,3),s.T[2],s.R[0]);
    wmask(s.R[0],t0,7);
}
void ps11_38(Ps11State& s){ // 61ECE0
    V4 t0=add(swz(s.PC[6],3,3,3,3),swz(s.T[3],3,3,3,3));
    wmask(s.R[1],t0,8);
}
void ps11_39(Ps11State& s){ // 61ECF8
    V4 t0=mad(sub(v4(1.0),swz(s.VC[1],3,3,3,3)),swz(s.T[0],3,3,3,3),swz(s.VC[1],3,3,3,3));
    wmask(s.R[1],t0,7);
}
void ps11_40(Ps11State& s){ // 61ED14
    V4 t0=mad(sub(v4(1.0),swz(s.VC[1],3,3,3,3)),swz(s.T[1],3,3,3,3),swz(s.VC[1],3,3,3,3));
    wmask(s.R[1],t0,7);
}
void ps11_41(Ps11State& s){ // 61ED30
    (void)s;
}
void ps11_42(Ps11State& s){ // 61ED38
    V4 t0=swz(s.VC[0],3,3,3,3);
    wmask(s.R[0],t0,8);
}
void ps11_43(Ps11State& s){ // 61ED4C
    V4 t0=mul(swz(s.T[0],3,3,3,3),swz(s.VC[0],3,3,3,3));
    wmask(s.R[0],t0,8);
}
void ps11_44(Ps11State& s){ // 61ED64
    V4 t0=mul(swz(s.T[1],3,3,3,3),swz(s.R[0],3,3,3,3));
    wmask(s.R[0],t0,8);
}
void ps11_45(Ps11State& s){ // 61ED7C
    V4 t0=swz(s.T[1],3,3,3,3);
    wmask(s.R[0],t0,8);
}
void ps11_46(Ps11State& s){ // 61ED90
    V4 t0=swz(s.T[2],3,3,3,3);
    wmask(s.R[0],t0,8);
}
void ps11_47(Ps11State& s){ // 61EDA4
    V4 t0=mul(swz(s.T[2],3,3,3,3),swz(s.R[0],3,3,3,3));
    wmask(s.R[0],t0,8);
}
void ps11_48(Ps11State& s){ // 61EDBC
    (void)s;
}
void ps11_49(Ps11State& s){ // 61EDC4
    V4 t0=add(s.R[0],s.VC[1]);
    V4 t1=swz(s.R[0],3,3,3,3);
    wmask(s.R[0],t0,7);
    wmask(s.R[0],t1,8);
}
void ps11_50(Ps11State& s){ // 622348
    s.T[0]=s.sample(0,s.TC[0]);
    V4 t0=mul(swz(s.T[0],3,3,3,3),sub(mul(s.T[0],v4(2.0)),v4(1.0)));
    wmask(s.R[1],t0,7);
    V4 t1=s.PC[0];
    wmask(s.R[0],t1,15);
    V4 t2=sub(s.R[1],sub(mul(s.R[0],v4(2.0)),v4(1.0)));
    wmask(s.R[1],t2,7);
    V4 t3=s.PC[1];
    wmask(s.R[0],t3,15);
    V4 t4=dp3(s.R[1],sub(mul(s.R[0],v4(2.0)),v4(1.0)));
    V4 t5=add(neg(swz(s.R[1],2,2,2,2)),swz(v4(1.0f,1.0f,1.0f,0.5f),3,3,3,3));
    wmask(s.R[1],mul(t4,v4(2.0f)),7);
    wmask(s.R[0],t5,8);
    V4 t6=cnd(swz(s.R[0],3,3,3,3),swz(v4(0.0f,0.0f,0.0f,0.0f),3,3,3,3),s.T[0]);
    V4 t7=cnd(swz(s.R[0],3,3,3,3),v4(0.0f,0.0f,0.0f,0.0f),swz(v4(1.0f,1.0f,1.0f,0.5f),3,3,3,3));
    wmask(s.R[0],t6,7);
    wmask(s.R[0],t7,8);
    V4 t8=sub(swz(s.T[0],3,3,3,3),s.PC[2]);
    wmask(s.R[1],sat(mul(t8,v4(4.0f))),7);
    V4 t9=sub(s.R[0],sub(v4(1.0),s.R[1]));
    wmask(s.R[0],t9,7);
}
void ps11_51(Ps11State& s){ // 622428
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
    s.T[3]=s.sample(3,s.TC[3]);
    V4 t0=mul(s.T[0],v4(0.25f,0.25f,0.25f,0.25f));
    wmask(s.R[0],t0,15);
    V4 t1=mad(s.T[1],v4(0.25f,0.25f,0.25f,0.25f),s.R[0]);
    wmask(s.R[0],t1,15);
    V4 t2=mad(s.T[2],v4(0.25f,0.25f,0.25f,0.25f),s.R[0]);
    wmask(s.R[0],t2,15);
    V4 t3=mad(s.T[3],v4(0.25f,0.25f,0.25f,0.25f),s.R[0]);
    wmask(s.R[0],t3,15);
}
void ps11_52(Ps11State& s){ // 6224B4
    s.T[0]=s.sample(0,s.TC[0]);
    V4 t0=s.T[0];
    wmask(s.R[0],t0,15);
}
void ps11_53(Ps11State& s){ // 6224D0
    s.T[0]=s.sample(0,s.TC[0]);
    V4 t0=dp3(s.T[0],v4(0.29899999499320984f,0.5870000123977661f,0.11400000005960464f,1.0f));
    wmask(s.R[0],t0,15);
    V4 t1=mul(s.R[0],swz(s.T[0],3,3,3,3));
    wmask(s.R[0],t1,7);
    V4 t2=swz(v4(0.29899999499320984f,0.5870000123977661f,0.11400000005960464f,1.0f),3,3,3,3);
    wmask(s.R[0],t2,8);
}
void ps11_54(Ps11State& s){ // 623830
    s.T[0]=s.sample(0,s.TC[0]);
    V4 t0=mul(s.T[0],s.VC[0]);
    wmask(s.R[0],sat(t0),15);
    V4 t1=mul(sub(v4(1.0),swz(s.R[0],3,3,3,3)),sub(v4(1.0),swz(s.R[0],3,3,3,3)));
    wmask(s.R[0],sat(t1),8);
    V4 t2=sub(v4(1.0),swz(s.R[0],3,3,3,3));
    wmask(s.R[0],t2,8);
    V4 t3=mul(s.R[0],swz(s.R[0],3,3,3,3));
    wmask(s.R[0],t3,7);
}
void ps11_55(Ps11State& s){ // 623BB0
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
    s.T[3]=s.sample(3,s.TC[3]);
    V4 t0=dp3(sub(mul(s.T[0],v4(2.0)),v4(1.0)),sub(mul(s.T[2],v4(2.0)),v4(1.0)));
    wmask(s.R[0],sat(t0),7);
    V4 t1=mad(s.R[0],s.PC[0],s.PC[1]);
    wmask(s.R[0],t1,7);
    V4 t2=mul(s.R[0],s.T[1]);
    wmask(s.R[0],t2,7);
    V4 t3=dp3(sub(mul(s.T[0],v4(2.0)),v4(1.0)),sub(mul(s.T[3],v4(2.0)),v4(1.0)));
    wmask(s.R[1],sat(t3),7);
    V4 t4=mul(s.R[1],s.R[1]);
    wmask(s.R[1],t4,7);
    V4 t5=mul(s.R[1],s.R[1]);
    wmask(s.R[1],t5,7);
    V4 t6=mul(s.R[1],s.R[1]);
    wmask(s.R[1],t6,7);
    V4 t7=mad(s.R[1],s.PC[2],s.R[0]);
    V4 t8=swz(v4(0.0f,0.0f,0.0f,0.0f),3,3,3,3);
    wmask(s.R[0],t7,7);
    wmask(s.R[0],t8,8);
}
void ps11_56(Ps11State& s){ // 623C88
    s.T[0]=s.sample(0,s.TC[0]);
    s.M3[1]=dp3(s.TC[1],s.T[0]).x;
    s.M3[2]=dp3(s.TC[2],s.T[0]).x;
    s.T[3]=s.sample_vspec(3,s.M3[1],s.M3[2],dp3(s.TC[3],s.T[0]).x,v4(s.TC[1].w,s.TC[2].w,s.TC[3].w,0.f));
    V4 t0=mul(s.VC[0],sub(v4(1.0),swz(s.T[3],3,3,3,3)));
    wmask(s.R[1],t0,7);
    V4 t1=mad(s.T[3],swz(s.T[3],3,3,3,3),s.R[1]);
    V4 t2=swz(s.VC[0],3,3,3,3);
    wmask(s.R[0],t1,7);
    wmask(s.R[0],t2,8);
}
void ps11_57(Ps11State& s){ // 623CF0
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample_bump(1,s.TC[1],s.T[0]);
    V4 t0=mul(s.VC[0],sub(v4(1.0),swz(s.T[1],3,3,3,3)));
    wmask(s.R[1],t0,7);
    V4 t1=mad(s.T[1],swz(s.T[1],3,3,3,3),s.R[1]);
    V4 t2=swz(s.VC[0],3,3,3,3);
    wmask(s.R[0],t1,7);
    wmask(s.R[0],t2,8);
}
void ps11_58(Ps11State& s){ // 623D40
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample_bump(2,s.TC[2],s.T[0]);
    V4 t0=mul(s.VC[0],s.T[1]);
    wmask(s.R[0],t0,7);
    V4 t1=mul(s.R[0],sub(v4(1.0),swz(s.T[2],3,3,3,3)));
    wmask(s.R[0],t1,7);
    V4 t2=mad(s.T[2],swz(s.T[2],3,3,3,3),s.R[0]);
    V4 t3=swz(s.VC[0],3,3,3,3);
    wmask(s.R[0],t2,7);
    wmask(s.R[0],t3,8);
}
void ps11_59(Ps11State& s){ // 623DA8
    s.T[0]=s.sample(0,s.TC[0]);
    s.T[1]=s.sample(1,s.TC[1]);
    s.T[2]=s.sample(2,s.TC[2]);
    s.T[3]=s.sample_bump(3,s.TC[3],s.T[0]);
    V4 t0=mul(s.VC[0],s.T[1]);
    wmask(s.R[0],t0,7);
    V4 t1=mul(s.R[0],s.T[2]);
    wmask(s.R[0],t1,7);
    V4 t2=mul(s.R[0],sub(v4(1.0),swz(s.T[3],3,3,3,3)));
    V4 t3=mul(swz(s.VC[0],3,3,3,3),swz(s.T[1],3,3,3,3));
    wmask(s.R[0],t2,7);
    wmask(s.R[0],t3,8);
    V4 t4=mad(s.T[3],swz(s.T[3],3,3,3,3),s.R[0]);
    V4 t5=mul(swz(s.R[0],3,3,3,3),swz(s.T[2],3,3,3,3));
    wmask(s.R[0],t4,7);
    wmask(s.R[0],t5,8);
}
}
const PcShaderBlobFn<VsState> PcShaderBlobFns_vs[73]={vs_0,vs_1,vs_2,vs_3,vs_4,vs_5,vs_6,vs_7,vs_8,vs_9,vs_10,vs_11,vs_12,vs_13,vs_14,vs_15,vs_16,vs_17,vs_18,vs_19,vs_20,vs_21,vs_22,vs_23,vs_24,vs_25,vs_26,vs_27,vs_28,vs_29,vs_30,vs_31,vs_32,vs_33,vs_34,vs_35,vs_36,vs_37,vs_38,vs_39,vs_40,vs_41,vs_42,vs_43,vs_44,vs_45,vs_46,vs_47,vs_48,vs_49,vs_50,vs_51,vs_52,vs_53,vs_54,vs_55,vs_56,vs_57,vs_58,vs_59,vs_60,vs_61,vs_62,vs_63,vs_64,vs_65,vs_66,vs_67,vs_68,vs_69,vs_70,vs_71,vs_72};
const PcShaderBlobFn<Ps14State> PcShaderBlobFns_ps14[44]={ps14_0,ps14_1,ps14_2,ps14_3,ps14_4,ps14_5,ps14_6,ps14_7,ps14_8,ps14_9,ps14_10,ps14_11,ps14_12,ps14_13,ps14_14,ps14_15,ps14_16,ps14_17,ps14_18,ps14_19,ps14_20,ps14_21,ps14_22,ps14_23,ps14_24,ps14_25,ps14_26,ps14_27,ps14_28,ps14_29,ps14_30,ps14_31,ps14_32,ps14_33,ps14_34,ps14_35,ps14_36,ps14_37,ps14_38,ps14_39,ps14_40,ps14_41,ps14_42,ps14_43};
const PcShaderBlobFn<Ps11State> PcShaderBlobFns_ps11[60]={ps11_0,ps11_1,ps11_2,ps11_3,ps11_4,ps11_5,ps11_6,ps11_7,ps11_8,ps11_9,ps11_10,ps11_11,ps11_12,ps11_13,ps11_14,ps11_15,ps11_16,ps11_17,ps11_18,ps11_19,ps11_20,ps11_21,ps11_22,ps11_23,ps11_24,ps11_25,ps11_26,ps11_27,ps11_28,ps11_29,ps11_30,ps11_31,ps11_32,ps11_33,ps11_34,ps11_35,ps11_36,ps11_37,ps11_38,ps11_39,ps11_40,ps11_41,ps11_42,ps11_43,ps11_44,ps11_45,ps11_46,ps11_47,ps11_48,ps11_49,ps11_50,ps11_51,ps11_52,ps11_53,ps11_54,ps11_55,ps11_56,ps11_57,ps11_58,ps11_59};
std::uint32_t PcShaderBlobTokens[3452]{};
const PcShaderBlob PcShaderBlobs[177]={
    {0x61F64CU,0xFFFE0101U,0U,0U,10U},
    {0x61F67CU,0xFFFE0101U,1U,10U,6U},
    {0x61F6A0U,0xFFFE0101U,2U,16U,22U},
    {0x61F700U,0xFFFE0101U,3U,38U,12U},
    {0x61F738U,0xFFFE0101U,4U,50U,37U},
    {0x61F7D4U,0xFFFE0101U,5U,87U,9U},
    {0x61F800U,0xFFFE0101U,6U,96U,59U},
    {0x61F8F4U,0xFFFE0101U,7U,155U,9U},
    {0x61F920U,0xFFFE0101U,8U,164U,81U},
    {0x61FA6CU,0xFFFE0101U,9U,245U,9U},
    {0x61FA98U,0xFFFE0101U,10U,254U,6U},
    {0x61FAB8U,0xFFFE0101U,11U,260U,6U},
    {0x61FAD8U,0xFFFE0101U,12U,266U,3U},
    {0x61FAECU,0xFFFE0101U,13U,269U,12U},
    {0x61FB24U,0xFFFE0101U,14U,281U,6U},
    {0x61FB48U,0xFFFE0101U,15U,287U,37U},
    {0x61FBE8U,0xFFFE0101U,16U,324U,37U},
    {0x61FC88U,0xFFFE0101U,17U,361U,78U},
    {0x61FDC8U,0xFFFE0101U,18U,439U,84U},
    {0x61FF20U,0xFFFE0101U,19U,523U,194U},
    {0x620230U,0xFFFE0101U,20U,717U,237U},
    {0x6205F0U,0xFFFE0101U,21U,954U,306U},
    {0x620AC0U,0xFFFE0101U,22U,1260U,349U},
    {0x62103CU,0xFFFE0101U,23U,1609U,8U},
    {0x621064U,0xFFFE0101U,24U,1617U,12U},
    {0x6210A0U,0xFFFE0101U,25U,1629U,16U},
    {0x6210E8U,0xFFFE0101U,26U,1645U,3U},
    {0x6210FCU,0xFFFE0101U,27U,1648U,8U},
    {0x621124U,0xFFFE0101U,28U,1656U,12U},
    {0x621160U,0xFFFE0101U,29U,1668U,16U},
    {0x6211A8U,0xFFFE0101U,30U,1684U,3U},
    {0x6211BCU,0xFFFE0101U,31U,1687U,8U},
    {0x6211E4U,0xFFFE0101U,32U,1695U,12U},
    {0x621220U,0xFFFE0101U,33U,1707U,16U},
    {0x621268U,0xFFFE0101U,34U,1723U,3U},
    {0x62127CU,0xFFFE0101U,35U,1726U,3U},
    {0x621290U,0xFFFE0101U,36U,1729U,3U},
    {0x6212A4U,0xFFFE0101U,37U,1732U,3U},
    {0x6212B8U,0xFFFE0101U,38U,1735U,3U},
    {0x6212CCU,0xFFFE0101U,39U,1738U,3U},
    {0x6212E0U,0xFFFE0101U,40U,1741U,3U},
    {0x6212F4U,0xFFFE0101U,41U,1744U,3U},
    {0x621308U,0xFFFE0101U,42U,1747U,3U},
    {0x62131CU,0xFFFE0101U,43U,1750U,9U},
    {0x621348U,0xFFFE0101U,44U,1759U,6U},
    {0x621368U,0xFFFE0101U,45U,1765U,9U},
    {0x621394U,0xFFFE0101U,46U,1774U,6U},
    {0x6213B4U,0xFFFE0101U,47U,1780U,9U},
    {0x6213E0U,0xFFFE0101U,48U,1789U,6U},
    {0x621400U,0xFFFE0101U,49U,1795U,9U},
    {0x62142CU,0xFFFE0101U,50U,1804U,6U},
    {0x62144CU,0xFFFE0101U,51U,1810U,3U},
    {0x621460U,0xFFFE0101U,52U,1813U,3U},
    {0x621478U,0xFFFE0101U,53U,1816U,28U},
    {0x6214F0U,0xFFFE0101U,54U,1844U,47U},
    {0x6215B8U,0xFFFE0101U,55U,1891U,16U},
    {0x621600U,0xFFFE0101U,56U,1907U,16U},
    {0x621648U,0xFFFE0101U,57U,1923U,0U},
    {0x621650U,0xFFFE0101U,58U,1923U,0U},
    {0x6216A0U,0xFFFE0101U,59U,1923U,103U},
    {0x621848U,0xFFFE0101U,60U,2026U,186U},
    {0x621B38U,0xFFFE0101U,61U,2212U,180U},
    {0x621E10U,0xFFFE0101U,62U,2392U,30U},
    {0x621E90U,0xFFFE0101U,63U,2422U,25U},
    {0x621F00U,0xFFFE0101U,64U,2447U,29U},
    {0x621F80U,0xFFFE0101U,65U,2476U,52U},
    {0x622058U,0xFFFE0101U,66U,2528U,22U},
    {0x6220B8U,0xFFFE0101U,67U,2550U,37U},
    {0x622158U,0xFFFE0101U,68U,2587U,23U},
    {0x6221C0U,0xFFFE0101U,69U,2610U,17U},
    {0x622210U,0xFFFE0101U,70U,2627U,19U},
    {0x622268U,0xFFFE0101U,71U,2646U,23U},
    {0x623E38U,0xFFFE0101U,72U,2669U,19U},
    {0x61E7C4U,0xFFFF0101U,0U,2688U,3U},
    {0x61E7D8U,0xFFFF0101U,1U,2691U,6U},
    {0x61E7F8U,0xFFFF0101U,2U,2697U,12U},
    {0x61E830U,0xFFFF0101U,3U,2709U,18U},
    {0x61E880U,0xFFFF0101U,4U,2727U,24U},
    {0x61E8E8U,0xFFFF0101U,5U,2751U,53U},
    {0x61E9C4U,0xFFFF0101U,6U,2804U,6U},
    {0x61E9E4U,0xFFFF0101U,7U,2810U,0U},
    {0x61E9ECU,0xFFFF0101U,8U,2810U,2U},
    {0x61E9FCU,0xFFFF0101U,9U,2812U,4U},
    {0x61EA14U,0xFFFF0101U,10U,2816U,4U},
    {0x61EA2CU,0xFFFF0101U,11U,2820U,6U},
    {0x61EA4CU,0xFFFF0101U,12U,2826U,2U},
    {0x61EA5CU,0xFFFF0101U,13U,2828U,4U},
    {0x61EA74U,0xFFFF0101U,14U,2832U,6U},
    {0x61EA94U,0xFFFF0101U,15U,2838U,8U},
    {0x61EABCU,0xFFFF0101U,16U,2846U,0U},
    {0x61EAC4U,0xFFFF0101U,17U,2846U,4U},
    {0x61EADCU,0xFFFF0101U,18U,2850U,3U},
    {0x61EAF0U,0xFFFF0101U,19U,2853U,4U},
    {0x61EB08U,0xFFFF0101U,20U,2857U,4U},
    {0x61EB20U,0xFFFF0101U,21U,2861U,4U},
    {0x61EB38U,0xFFFF0101U,22U,2865U,4U},
    {0x61EB50U,0xFFFF0101U,23U,2869U,5U},
    {0x61EB6CU,0xFFFF0101U,24U,2874U,9U},
    {0x61EB98U,0xFFFF0101U,25U,2883U,3U},
    {0x61EBACU,0xFFFF0101U,26U,2886U,4U},
    {0x61EBC4U,0xFFFF0101U,27U,2890U,4U},
    {0x61EBDCU,0xFFFF0101U,28U,2894U,4U},
    {0x61EBF4U,0xFFFF0101U,29U,2898U,4U},
    {0x61EC0CU,0xFFFF0101U,30U,2902U,5U},
    {0x61EC28U,0xFFFF0101U,31U,2907U,9U},
    {0x61EC54U,0xFFFF0101U,32U,2916U,4U},
    {0x61EC6CU,0xFFFF0101U,33U,2920U,4U},
    {0x61EC84U,0xFFFF0101U,34U,2924U,0U},
    {0x61EC8CU,0xFFFF0101U,35U,2924U,5U},
    {0x61ECA8U,0xFFFF0101U,36U,2929U,5U},
    {0x61ECC4U,0xFFFF0101U,37U,2934U,5U},
    {0x61ECE0U,0xFFFF0101U,38U,2939U,4U},
    {0x61ECF8U,0xFFFF0101U,39U,2943U,5U},
    {0x61ED14U,0xFFFF0101U,40U,2948U,5U},
    {0x61ED30U,0xFFFF0101U,41U,2953U,0U},
    {0x61ED38U,0xFFFF0101U,42U,2953U,3U},
    {0x61ED4CU,0xFFFF0101U,43U,2956U,4U},
    {0x61ED64U,0xFFFF0101U,44U,2960U,4U},
    {0x61ED7CU,0xFFFF0101U,45U,2964U,3U},
    {0x61ED90U,0xFFFF0101U,46U,2967U,3U},
    {0x61EDA4U,0xFFFF0101U,47U,2970U,4U},
    {0x61EDBCU,0xFFFF0101U,48U,2974U,0U},
    {0x61EDC4U,0xFFFF0101U,49U,2974U,7U},
    {0x622348U,0xFFFF0101U,50U,2981U,54U},
    {0x622428U,0xFFFF0101U,51U,3035U,33U},
    {0x6224B4U,0xFFFF0101U,52U,3068U,5U},
    {0x6224D0U,0xFFFF0101U,53U,3073U,19U},
    {0x623830U,0xFFFF0101U,54U,3092U,23U},
    {0x623BB0U,0xFFFF0101U,55U,3115U,51U},
    {0x623C88U,0xFFFF0101U,56U,3166U,23U},
    {0x623CF0U,0xFFFF0101U,57U,3189U,17U},
    {0x623D40U,0xFFFF0101U,58U,3206U,23U},
    {0x623DA8U,0xFFFF0101U,59U,3229U,34U},
    {0x61EDE8U,0xFFFF0104U,0U,3263U,0U},
    {0x61EDF0U,0xFFFF0104U,1U,3263U,0U},
    {0x61EDF8U,0xFFFF0104U,2U,3263U,3U},
    {0x61EE0CU,0xFFFF0104U,3U,3266U,6U},
    {0x61EE2CU,0xFFFF0104U,4U,3272U,6U},
    {0x61EE4CU,0xFFFF0104U,5U,3278U,9U},
    {0x61EE78U,0xFFFF0104U,6U,3287U,3U},
    {0x61EE8CU,0xFFFF0104U,7U,3290U,6U},
    {0x61EEACU,0xFFFF0104U,8U,3296U,9U},
    {0x61EED8U,0xFFFF0104U,9U,3305U,12U},
    {0x61EF10U,0xFFFF0104U,10U,3317U,0U},
    {0x61EF18U,0xFFFF0104U,11U,3317U,4U},
    {0x61EF30U,0xFFFF0104U,12U,3321U,3U},
    {0x61EF44U,0xFFFF0104U,13U,3324U,4U},
    {0x61EF5CU,0xFFFF0104U,14U,3328U,4U},
    {0x61EF74U,0xFFFF0104U,15U,3332U,4U},
    {0x61EF8CU,0xFFFF0104U,16U,3336U,4U},
    {0x61EFA4U,0xFFFF0104U,17U,3340U,5U},
    {0x61EFC0U,0xFFFF0104U,18U,3345U,9U},
    {0x61EFECU,0xFFFF0104U,19U,3354U,3U},
    {0x61F000U,0xFFFF0104U,20U,3357U,4U},
    {0x61F018U,0xFFFF0104U,21U,3361U,4U},
    {0x61F030U,0xFFFF0104U,22U,3365U,4U},
    {0x61F048U,0xFFFF0104U,23U,3369U,4U},
    {0x61F060U,0xFFFF0104U,24U,3373U,5U},
    {0x61F07CU,0xFFFF0104U,25U,3378U,9U},
    {0x61F0A8U,0xFFFF0104U,26U,3387U,4U},
    {0x61F0C0U,0xFFFF0104U,27U,3391U,4U},
    {0x61F0D8U,0xFFFF0104U,28U,3395U,0U},
    {0x61F0E0U,0xFFFF0104U,29U,3395U,5U},
    {0x61F0FCU,0xFFFF0104U,30U,3400U,5U},
    {0x61F118U,0xFFFF0104U,31U,3405U,5U},
    {0x61F134U,0xFFFF0104U,32U,3410U,4U},
    {0x61F14CU,0xFFFF0104U,33U,3414U,5U},
    {0x61F168U,0xFFFF0104U,34U,3419U,5U},
    {0x61F184U,0xFFFF0104U,35U,3424U,0U},
    {0x61F18CU,0xFFFF0104U,36U,3424U,3U},
    {0x61F1A0U,0xFFFF0104U,37U,3427U,4U},
    {0x61F1B8U,0xFFFF0104U,38U,3431U,4U},
    {0x61F1D0U,0xFFFF0104U,39U,3435U,3U},
    {0x61F1E4U,0xFFFF0104U,40U,3438U,3U},
    {0x61F1F8U,0xFFFF0104U,41U,3441U,4U},
    {0x61F210U,0xFFFF0104U,42U,3445U,0U},
    {0x61F218U,0xFFFF0104U,43U,3445U,7U},
};
const std::size_t PcShaderBlobCount=177;
const std::size_t PcShaderBlobCounts[3]={73,60,44}; // vs, ps11, ps14
// Shader bytecode tokens: copied from the player's EXE image at each blob
// address (version token excluded, END excluded) when the image is installed.
void build_shader_blob_tokens(){
    for(std::size_t i=0;i<PcShaderBlobCount;++i){
        const auto& b=PcShaderBlobs[i];
        std::memcpy(PcShaderBlobTokens+b.token_offset,exe_image_bytes(b.va+4u,b.token_count*4u),b.token_count*4u);
    }
}
OR2_EXE_BIND(build_shader_blob_tokens);
}
