// Generated by tools/extract_race_robots_data.py from the unpacked Steam build of OR2006C2C (same data as the pinned OR2006C2C.EXE).
#include "system/exe_image.hpp"
#include "platform/race_robots.hpp"
namespace outrun::platform {
// robot module .data 654568..6549C8 (driver records, tables, 6546C0 hand-motion list)
alignas(16) std::uint8_t RaceRobotsDataImage[0x460]{}; OR2_EXE_COPY(RaceRobotsDataImage,0x654568u,0x460u);
namespace {
// 005A91BC..005A91C0 488AF0 network offset scale
const std::uint8_t Table0[0x4]={
    0x89,0x88,0x08,0x3d,
};
// 005B0CB8..005B2FE0 46BC10 per-model character position tables (5B2F68 pointer list)
alignas(4) static std::uint8_t Table1[0x2328]{}; OR2_EXE_COPY(Table1,0x5B0CB8u,0x2328u);
// 005B4320..005B4324 488DD0 steering frame scale
const std::uint8_t Table2[0x4]={
    0x80,0x00,0x80,0x37,
};
// 005C0B80..005C1630 robot motion tables 5C0B80..5C162C
alignas(4) static std::uint8_t Table3[0xab0]{}; OR2_EXE_COPY(Table3,0x5C0B80u,0xAB0u);
// 00619A34..00619A38 zero constant
const std::uint8_t Table4[0x4]={
    0x00,0x00,0x00,0x00,
};
// 006280C4..006282A8 487A30/488DD0 float constants 6280C4, 628254, 6282A4
alignas(4) static std::uint8_t Table5[0x1e4]{}; OR2_EXE_COPY(Table5,0x6280C4u,0x1E4u);
}
const PcRaceRobotTable RaceRobotTables[6]={
    {0x5a91bcu,Table0,sizeof Table0},
    {0x5b0cb8u,Table1,sizeof Table1},
    {0x5b4320u,Table2,sizeof Table2},
    {0x5c0b80u,Table3,sizeof Table3},
    {0x619a34u,Table4,sizeof Table4},
    {0x6280c4u,Table5,sizeof Table5},
};
}
