// Generated by tools/extract_race_area_data.py from the unpacked Steam build of OR2006C2C (same data as the pinned OR2006C2C.EXE).
#include "system/exe_image.hpp"
#include <cstddef>
#include <cstdint>
namespace outrun::platform {
// area module .data 635F2C..636BC4
extern std::uint8_t RaceAreaDataImage[0xc98];
alignas(16) std::uint8_t RaceAreaDataImage[0xc98]{}; OR2_EXE_COPY(RaceAreaDataImage,0x635F2Cu,0xC98u);
// sky module .data 638664..638674
extern std::uint8_t RaceSkyDataImage[0x10];
alignas(16) std::uint8_t RaceSkyDataImage[0x10]{}; OR2_EXE_COPY(RaceSkyDataImage,0x638664u,0x10u);
}
