#pragma once
#include <array>
#include <cstdint>
#include <cstring>
#include "system/exe_image.hpp"
// Immutable 4A5830 model data, built from the player's EXE image when it is
// installed (formerly generated by tools/build_vehicle_constructor_tables.py).
// 46BBF0: four xyz wheel positions; 4866C0: words +C/+10/+14/+1C/+20/+24/+28/+2C.
// Model-ID order, NOT menu order. Float fields retain exact source bits.
namespace outrun::platform {
inline std::array<std::array<std::uint32_t,20>,30> VehicleConstructorData{};
// 520950 collision descriptors (5E8A88 + model*0x3C), including unused source bytes.
inline std::array<std::array<std::uint8_t,60>,30> VehicleCollisionData{};
inline void build_vehicle_constructor_tables(){
    constexpr std::uint32_t Records=0x650500u;   // 4866C0 car records, 0x44 bytes each
    for(std::uint32_t model=0;model<30u;++model){
        auto& w=VehicleConstructorData[model];
        const auto definition=exe_image_u32(0x5B2F68u+model*4u);
        for(std::uint32_t wheel=0;wheel<4u;++wheel)
            std::memcpy(&w[wheel*3u],exe_image_bytes(definition+0x98u+wheel*0x20u,12),12);
        std::memcpy(&w[12],exe_image_bytes(Records+model*0x44u+0x0Cu,12),12);
        w[15]=exe_image_u32(Records+model*0x44u+0x1Cu);
        std::memcpy(&w[16],exe_image_bytes(Records+model*0x44u+0x20u,16),16);
        std::memcpy(VehicleCollisionData[model].data(),exe_image_bytes(0x5E8A88u+model*0x3Cu,0x3C),0x3C);
    }
}
OR2_EXE_BIND(build_vehicle_constructor_tables);
}
